Add:  dependency page to guide
pyOpenSci/python-package-guide pull request #106
Opened 2023-10-11 18:58 UTC by lwasser

This is a file generated via discussion in our community slack with a lot of feedback from folks there.  all review is welcome.

2023-10-11 18:59 UTC, lwasser commented
@all-contributors please add @Zeitsperre for code, review 

thanks for the input on this trevor!

2023-10-11 22:15 UTC, ucodery requested changes

2023-10-11 22:15 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
`yourPackage.` is not a valid target name. It can be `yourPackage` or `.` but the `.` makes more sense here as the proper name usually won't install from local disk.

2023-10-11 22:15 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`yourPackage.[all]`
This is not a valid target. The example pyproject.toml above could include an additional `all` table that references the other optional-dependencies, or the multi extras syntax could be used here (`.[tests,docs,lint]`)

2023-10-11 22:15 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +# Python package dependency declaration
The title of this page would make me come here to find out how to declare install dependencies, but that is not actually covered (entirely different `project.dependencies` table). Is there somewhere else in the guide we can link to show that as well?

2023-10-11 22:38 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
I would rather see these examples as all `python -m pip install ...` (actually every pip example anywhere. I would prefer this to be a style rule for the entire guide)

2023-10-12 00:40 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
Running pip as a callable module rather than a stand alone command can reduce a lot of issues and confusion on the part of the user. There is nothing about the lookup of the pip command that guarantees it is installed for (and so installs other packages for) the python interpreter that is also resolved as a command. This means that when the pip and python commands get out of sync (and they always seem to eventually when you are least on guard) then pip acts on an environment unrelated to where you are actually running code.

There can be other reason to use pip this way too, many have been written about elsewhere as well https://snarky.ca/why-you-should-use-python-m-pip/

2023-10-12 01:37 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +# Python package dependency declaration
great question - i actually did just add a section on that [at the top](https://output.circle-artifacts.com/output/job/6a2d033e-06eb-4710-bb12-538a0bb200d6/artifacts/0/html/package-structure-code/declare-dependencies.html) following this comment! we also show that in the [previous page that covers pyproject.toml files](https://output.circle-artifacts.com/output/job/6a2d033e-06eb-4710-bb12-538a0bb200d6/artifacts/0/html/package-structure-code/pyproject-toml-python-package-metadata.html)

have a look at the built pages and let me know if this configuration makes sense. looking at the pyproject.toml page after working with folks in our slack on moving from setup.py to pyproject also has been wondering if that page needs to have a bit more info. i have a tutorial on this topic in google docs but i'm curious what you think about what we have now and whether it's clear.

2023-10-12 01:41 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
great point. i fixed this. i think i actually got confused by some of the documentation around this. i've removed yourPackage throughout (i hope) in the last commit. thanks!

i still have a question however. 

i was playing around with gemgis and below - doesn't work

```
[project.optional-dependencies]
build = ["twine", "build"]
deps = ["stravalib"]
dev = [".[build,deps]"]
```

but this does:

```
[project.optional-dependencies]
build = ["twine", "build"]
deps = ["stravalib"]
dev = ["gemgis.[build,deps]"]
```

and i'm not sure if this is still my not fully understanding all of the nuances of extras in the pyproj file OR you have to declare the project name for grouped extras (i hope that makes sense?)

2023-10-12 01:43 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
ok i really would love folks to chime in on this so i / we can understand and agree on what best practice should be here. i would love to understand why this would be a better approach. my understanding is that similar to how build operates, this would run pip as a module? which maybe means it would run from the current active environment? i'm guessing here... and welcome clarification!

2023-10-12 01:47 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`yourPackage.[all]`
i learned that the hard way. what is really odd - is that i got this from some nox example. and somehow it worked for me locally. but it must have been by mistake (i really don't know how it could have worked after testing this). i've removed and fixed as you suggested here.

2023-10-12 16:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
I'm not sure why one of your examples works but the other does not. If I try either in a test project I get errors for both about a dependency not following PEE-508. I think, but didn't look into it too far, this doesn't work because `.` is an illegal package name, but some nicity for pip to specify the local project, but that's not legal in a pyproject.

2023-10-12 17:00 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
yes, precisely. This way always runs pip as a module, meaning you select the python you want to install for, not the pip that is associated with the python you want to install for. And in virtual environments this always picks up the project python. (It can pick up the project pip too, but not always! Virtualenvs don't always have a pip so you might break out and use a system pip).

2023-10-12 17:50 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
ok i'm convinced between this conversation and feedback in our slack! 

1. i will fix all examples to use `python -m pip` and have a small breakout with a link to [brett's blog post ](https://snarky.ca/why-you-should-use-python-m-pip/) about why this is better.

Question for your both here. @Zeitsperre , you mention above that there might be differences between mac/windows/linux. Is that explicelty with using `python3 -m pip`  ? so we can presume that `python -m pip` (without the "3") should work universally across operating systems? or do we have a warning tip related to cross operating system implementations?

2. Trevor - i'm trying to follow the second part of your statement above. it sounds like it would be good to have a breakout tip about linux distributions but i don't fully understand what it would look like or how someone would encounter a mixed environment with both pip installed dependencies AND linux libraries already installed. Would this happen perhaps in a case where python shipped with someone's linux install and had existing packages and a user doesn't use some sort of virtual environment?

if you can help me understand or perhaps write a short blurb i can make a note of this. And it might be the the high level take away is always use virtual environments be it venv, conda etc. 

thank you both! this is super helpful feedback!

2023-10-12 17:58 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
Unfortunately true @Zeitsperre. There is no universal way to call python that will always work in every situation. Python from python.org only ships `python3` and `python3.X` commands for Linux and Mac, but only a `python` for Windows. Meanwhile virtualenvs redirect the `python` command for all platforms. And if you build python yourself you might only have a `python3.X` command for that version. This is all very confusing and why we have an assortment of python runners in the community. IMO it is too confusing and off-topic to get slotted into documentation about project dependencies.

But this is why **not** using `pip` is better. If you get an error "python: command not found" you can probably figure out what the correct name is. But in that same situation `pip` might exist and point to the wrong python environment.

2023-10-12 18:00 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
oh neither work for you? I wonder if it's because i have gemgis already installed in that environment?

Below doesn't work for me either locally:
```
[project.optional-dependencies]
build = ["twine", "build"]
deps = ["stravalib"]
dev = ["[build,deps]"]
```

i don't know how to actually group dependency-groups into a new group at this point if neither work for you and only gemgis.[group1, group2] work for me.

i get a value error otherwise

```
ValueError: invalid pyproject.toml config: `project.optional-dependencies.dev[0]`.
      configuration error: `project.optional-dependencies.dev[0]` must be pep508
```

2023-10-12 18:01 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
actually [here](https://hynek.me/articles/python-recursive-optional-dependencies/), they suggest this: 

```
[project]
name = "my-pkg"

[project.optional-dependencies]
tests = ["pytest"]
docs = ["sphinx"]
dev = [
    "my-pkg[tests,docs]",
    "pdbpp",
]
```

2023-10-12 18:19 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
> Question for your both here. @Zeitsperre , you mention above that there might be differences between mac/windows/linux. Is that explicelty with using `python3 -m pip` ? so we can presume that `python -m pip` (without the "3") should work universally across operating systems? or do we have a warning tip related to cross operating system implementations?

Echoing Jeremy here, that since `$ python` isn't always the naming convention depending on your environment, it might make sense to have some warning about that trip-fall early on. Maybe something about ensuring that your environment is activated (definitely the case for `virtualenv` and `conda`)?

> I'm trying to follow the second part of your statement above. it sounds like it would be good to have a breakout tip about linux distributions but i don't fully understand what it would look like or how someone would encounter a mixed environment with both pip installed dependencies AND linux libraries already installed. Would this happen perhaps in a case where python shipped with someone's linux install and had existing packages and a user doesn't use some sort of virtual environment?

Thankfully, most Linux environments emit a bunch of warnings if you as a user start trying to install `pip` libraries into your system Python installation. I can see this happening if a user comes across some bad advice that suggests running ~`$ sudo pip install xyz`~ (strikethrough since you should never run this command).

The "bad stuff" that could happen could be that a systemd/runit service depends on a particular version of `pyyaml` in order to parse a configuration file to properly run. Perhaps this service is tied to your fan control curves, or to the hardware temperature sensors, or something else that interfaces with hardware. This service could fail to start and worse, it could cause actual damage to the hardware. Alternatively, if the Python library is in any way tied to package binary compilations, it could render your system unable to compile libraries and effectively break your installation. Either way, not good.

> if you can help me understand or perhaps write a short blurb i can make a note of this. And it might be the the high level take away is always use virtual environments be it venv, conda etc.

Essentially, you're absolutely right about the take-away; You should always be using virtualenv (or conda) unless you're working on a system-level package (i.e.: something that would be installed via `apt` (Debian) or `dnf` (Fedora) or `xbps-install` (Void Linux), etc.). Let me know if you'd like a blurb and I'll see what I can offer!

2023-10-12 18:42 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
That looks good. After getting the PEP508 errors I assumed you had to use the published name of the package.

2023-10-12 18:48 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
I had no idea that you could reference other `optional-dependency` recipes from within. Neat!

2023-10-12 18:55 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
It's not really like a local reference. You are telling pip that installing `my-pkg[dev]` depends on `my-pkg[tests]` to be installed, same as `pdbpp`; it initially looks like any other external dependency. It's only when dependencies have been solved that it figures out that the dependencies under `[dev]` and `[tests]` are different, and merges those graphs. And because you have to have exactly one version of any package in an environment, the `my-pkg` in `my-pkg[tests]` must be the same version as that in `my-pkg[dev]`.

2023-10-16 09:49 UTC, cmarmo commented on package-structure-code/declare-dependencies.md
> +`pip install .[docs]`
Nitpick: I recently stumbled upon a shell issue... Mac ships `zsh` as default shell and
```
pip install .[docs]
```
fails on `zsh`. Double quotes are needed for the interpreter to understand the command:
```
pip install ."[docs]"
```
This has the advantage of working on `bash` and the other *ix shells (not tested on PowerShell).

2023-12-06 01:34 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[docs]`
ok resolving this! as i have made the change and pushed it here!

2023-12-06 01:42 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
ok friends.

1. i've updated every instance of pip on this page to `python -m pip` NOTE - there are likely other instances in our guide - but i don't want to fix this everywhere in this pr to keep the scope tight. Maybe we can go through the guide and fix all other instances in another pr? 
<img width="854" alt="Screenshot 2023-12-05 at 6 41 49 PM" src="https://github.com/pyOpenSci/python-package-guide/assets/7649194/72391691-66d7-43e0-8b7e-12c2509a85b3">

2. i've added the above breakout  to explain why we did this. i'll push the fixes soon in case you want to copy edit or rewrite my brief summary of the above discussion. or just let me know if i missed something critical!

2023-12-06 01:43 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install .[docs]`
i'll fix this and leave a comment. are there any instances where the quotes might break things for users? @cmarmo @ucodery @Zeitsperre ? if so we should provide a breakout about this as well.

2023-12-06 01:45 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install .[docs]`
Actually i just saw we added this breakout. Is it better to use the quotes throughout and tell users in some cases they may not need them? or is it better to remove the quotes and tell users to add them if needed? 

<img width="866" alt="Screenshot 2023-12-05 at 6 44 56 PM" src="https://github.com/pyOpenSci/python-package-guide/assets/7649194/bb6fec45-9153-4d48-bcd0-86523ffd6780">

2023-12-06 05:08 UTC, sneakers-the-rat commented
I feel bad because I pick on the ToC literally every time, but i rely on them to skim and read on the internet! in this case making it hard for me to tell which section goes with which (eg. is the "If you are using a front-end build tool like PDM, Hatch, or Poetry" section a top-level section as a global alternative to everything above, or it just a note about the preceding readthedocs section?

Currently toc is:

```
Declaring Development Dependencies - Python Packaging
|- How to declare documentation, test, and other dependencies
|- Direct project dependencies
|- Development dependencies
|- How to declare development dependencies
|- How to install dependencies from your pyproject.toml
|  |- Combining sets of dependencies
|- Where does conda fit in ?
|- Read the Docs & project dependencies
|- If you are using a front-end build tool like PDM, Hatch or Poetry
```

But without changing the content the ToC could be

```
Dependencies
|- Declaring Dependencies
|  |- Required Dependencies
|  |- Optional Dependencies
|  |- Combining Optional Dependencies
|- Conda Environments
|- CI Environments
|  |- Read The Docs
```

which is very skimmable, groups similar content together, and gives us clear points of expansion in the future should someone like to contribute eg. guides on using different tools like PDM/Hatch/etc. (change "Conda Environments" into "Other Formats" and then Conda becomes one of several other examples) or other CI environments.

Just an example, i get how this is not obvious while writing. You mentioned previously wanting to have big long titles for SEO, but i think SEO mostly cares about the `<title>` metadata element not the actual displayed title on the page, so since `sphinexect-opengraph` is already being used here, one can just set that metadata separately, eg.

```markdown
:og:title: Big Long SEO Title To Appear In Search Engine Results

# More Manageable Title

For In-page and ToC display
```

Or I think that might be `{og}{title}`Title` in myst-md. not sure.

2023-12-06 06:02 UTC, sneakers-the-rat reviewed
Lovely! Thanks as always for your work Leah :) 

Good with p much all of this. Most of my comments are for clarity, tried to keep them useful and not nitpicky.

The main thing that's missing here is a discussion of version specifications. That's the thing i spend the most time fiddling with by far, and so I think we need
- Why you specify them
- How to specify them
- When you use different specifiers

as a baseline. Couple paras tops, doesn't need to be exhaustive, and i can draft something for this.

I also think it would be lovely to add tabbed examples for each of the major package managers here so ppl can stick with default complexity or also check out the other equivalent tabs if they're curious/for their reference if they end up on different tools. i've already made an example like that in a previous PR: https://github.com/pyOpenSci/python-package-guide/pull/104#discussion_r1341925025 and would be happy to put it in the same tab groups format as setuptools uses here: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

Thanks again again!

2023-12-06 19:31 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +approach then you may still need to use a requirements.txt or a conda environment file for your dependency installs.
This is true, but if you have special build recipes that depend on projects in development (`main|master` branches) this won't work. When bundling source packages, I'll add a "requirements_upstream.txt` with these listed, but not list them in the `pyproject.toml`, but rather have them installed in a Makefile recipe (e.g. `$ make upstream-dev`).

2023-12-06 22:15 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +your package infrastructure.
it is. honestly i haven't even thought about that - good point!! this was setup a year+ ago and i never even thought about it!

 can you use a pyproject.toml for a sphinx book / site? i guess you could and just update the noxfile instructions for installing deps? prs are always welcome!!

2023-12-06 22:17 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +a user requires to install your package, can be stored in a
fixed!! thanks!

2023-12-06 22:21 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +## Development dependencies
ahhhh i see what you mean. i'll rename it to be Optional Dependencies!

2023-12-06 22:25 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +Dependencies for building your documentation, running your tests and building your package's distribution files are often referred to as development dependencies. These are the dependencies that a us
great point! i've added this

*******
Ideally, you should only list the packages that are 
necessary to install and use your package in the `[dependencies]` section. This minimized the number of additional packages that both your users and packages that depend upon your package have to install. 

Remember that fewer dependencies to install reduces the likelihood of version mismatches in user environments.

2023-12-06 22:30 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +
fixed!
*****

It's important to note that within the `optional.dependencies` table, you can store additional, optional dependencies within named sub-groups. This is a different table than the dependencies section discussed above which contains a single array with a single list of required packages.

2023-12-06 22:31 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +The requirements.txt file used to be the default way to store dependencies. However in recent years, the ecosystem has moved to storing all of this information in a single **pyproject.toml** file. Yo
i hear you! moved to the top!!

2023-12-06 22:35 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +The requirements.txt file used to be the default way to store dependencies. However in recent years, the ecosystem has moved to storing all of this information in a single **pyproject.toml** file. Yo
i hear you... 
****
😆 
now that i read that i think my head was stuck because i was helping someone at the time that had both conda yml files and requirements.txt.
i didn't fully understand optional.dependencies at the time.

SO i've changed the block to this text which i think is more accurate!! great catch!

*****
The `requirements.txt` file used to be the default way to store dependencies. However in recent years, the ecosystem has moved to storing all of this information in a single **pyproject.toml** file. Some projects still maintain a `requirements.txt` file either for specific local development needs.

2023-12-06 22:43 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +[Learn more: View PyPA's overview of declaring optional dependencies](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies)
weird @sneakers-the-rat it works for me. could you try again please?

2023-12-06 22:47 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +install just the dependencies needed to run your tests:
fixed!!

2023-12-06 22:58 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +
totally- great catch! fixed locally!

2023-12-06 22:59 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +that your package needs / has declared in your pyproject.toml file.
i do - fixed!

2023-12-07 00:00 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +The above workflow assumes that you want to publish your package on PyPI. And then you plan to publish to conda-forge (optionally), [by submitting a recipe using greyskull](https://www.pyopensci.org/
in the meantime i've renamed the next section.

2023-12-07 00:03 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +If you want to support conda users, you may want to also maintain a conda environment that they can use to install your package. Maintaining a conda environment will also help you test that your pack
so looking at this further i'm not sure if we want the conda info above here. in my mind, this section was more for contributors who might use conda environments and are less aware of venv, etc.  i'll keep this open but it feels a like a bit too much for this specific page.

2023-12-07 00:05 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +## Read the Docs & project dependencies
much better!! fixed!

2023-12-07 00:09 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +If you are using another front-end build tool such as PDM, Hatch or Poetry to manage dependencies, then your approach to installing dependencies may be different. Each tool has its own, slightly diff
ok i revisited this and realized this came up when i was working with someone and trying to get deps to install on RTD. so it's not about installing rather RTD has some specific instructions for other tools to be aware of. SO

1. i created a small breakout about other tools and RTD 
2. simplied the text to just say - if you are using another tool , be sure to check the RTD documentation - then i linked to it. 
i hope that is better / easier now to follow!

2023-12-07 00:10 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +Alternatively, you can install your package using `pip install -e . --no-deps` to only install the package. And install the rest of your dependencies using a conda environment file.
fixed!!

2023-12-07 00:13 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +# Python package dependency declaration
perfect - i'll resolve this comment for now!

2023-12-07 00:16 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
i just am reviewing comments and noticed that i missed the - be sure to activate your dev envt first. so i added that to the breakout box as well!

2023-12-07 00:18 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage.[tests]`
also @sneakers-the-rat thank you for the kind words. i definitely can't do everything!! and i'm super grateful to everyone here helping ensure the content in this guide is accurate AND (beginner) user-friendly! 

 i have moved everything over to `python -m pip install`. one thing we could do is see how users respond to this. if we get a lot of questions / confusion we can  modify as needed too. this is a living document after all. 

i am going to resolve this comment for the time being BUT welcome re-opening it if we need to / if y'all aren't ok with edits ive made to the page at any time!

2023-12-07 00:19 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +approach then you may still need to use a requirements.txt or a conda environment file for your dependency installs.
that's a great and simple comment that i think users will understand in the case they have github hosted deps! thank you @Zeitsperre !!

2023-12-07 00:23 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +approach then you may still need to use a requirements.txt or a conda environment file for your dependency installs.
ok i now have this in the breakout!!

```
:::{admonition} Installing packages from GitHub / Gitlab
:class: tip

If you have dependencies that need to be installed directly from GitHub using 
a `git+https` installation approach, you can do so using the pyproject.toml 
file like so:

```toml
dependencies = [
"my_dependency >= 1.0.1 @ git+https://git.server.example.com/mydependency.git"
]
```

IMPORTANT: For security reasons, if your library depends on a GitHub-hosted 
project, you will need to point to a specific commit/tag of that repository in 
order to upload your project to PyPI
:::
```

i think one of my favorite parts of working on these pages is that i'm learning a lot! for whatever reason i had it in my brain that you couldn't install from github in a pyproject.toml dep section! of course my brain was wrong as usual! :) thank you all!!

2023-12-07 00:36 UTC, lwasser commented
> I feel bad because I pick on the ToC literally every time, but i rely on them to skim and read on the internet! in this case making it hard for me to tell which section goes with which (eg. is the "If you are using a front-end build tool like PDM, Hatch, or Poetry" section a top-level section as a global alternative to everything above, or it just a note about the preceding readthedocs section?
> 
> Currently toc is:
> 
> ```
> Declaring Development Dependencies - Python Packaging
> |- How to declare documentation, test, and other dependencies
> |- Direct project dependencies
> |- Development dependencies
> |- How to declare development dependencies
> |- How to install dependencies from your pyproject.toml
> |  |- Combining sets of dependencies
> |- Where does conda fit in ?
> |- Read the Docs & project dependencies
> |- If you are using a front-end build tool like PDM, Hatch or Poetry
> ```
> 
> But without changing the content the ToC could be
> 
> ```
> Dependencies
> |- Declaring Dependencies
> |  |- Required Dependencies
> |  |- Optional Dependencies
> |  |- Combining Optional Dependencies
> |- Conda Environments
> |- CI Environments
> |  |- Read The Docs
> ```
> 
> which is very skimmable, groups similar content together, and gives us clear points of expansion in the future should someone like to contribute eg. guides on using different tools like PDM/Hatch/etc. (change "Conda Environments" into "Other Formats" and then Conda becomes one of several other examples) or other CI environments.
> 
> Just an example, i get how this is not obvious while writing. You mentioned previously wanting to have big long titles for SEO, but i think SEO mostly cares about the `<title>` metadata element not the actual displayed title on the page, so since `sphinexect-opengraph` is already being used here, one can just set that metadata separately, eg.
> 
> ```
> :og:title: Big Long SEO Title To Appear In Search Engine Results
> 
> # More Manageable Title
> 
> For In-page and ToC display
> ```
> 
> Or I think that might be `{og}{title}`Title` in myst-md. not sure.

Hey @sneakers-the-rat i love how you think about structure of a page. it's important. i've restructured - it's not exactly what you suggested but very close! to me RTD is not just CI it's a publication platform. so i just adjusted the wording a bit but followed your suggestions!

i do have questions about this part -- 
```
> :og:title: Big Long SEO Title To Appear In Search Engine Results
```

i keep reading that you can have front matter in sphinx but i haven't seen a good example of how you add that in myst-md. i've looked. 

if someone could help me understand that (i see this [page here](https://github.com/wpilibsuite/sphinxext-opengraph#per-page-overrides) for instance but don't know how to translate that to the top of a .md file) -- id' greatly appreciate it. maybe i can ask on slack even?

2023-12-07 01:24 UTC, sneakers-the-rat commented on package-structure-code/declare-dependencies.md
> +approach then you may still need to use a requirements.txt or a conda environment file for your dependency installs.
ya i thought i had mentioned this in this or another comment but the downside is basically git dependencies are a no-go on PyPI as @Zeitsperre says. I didn't even know that you were allowed to point to a specific commit hash in a PyPI package. 

For the sake of completeness of the example, the syntax for specifying a commit is this:

```
"my_dependency >= 1.0.1 @ git+https://git.server.example.com/mydependency.git@GITREF"
```

pip gives these examples ( https://pip.pypa.io/en/latest/topics/vcs-support/#vcs-support ) 

```
MyProject @ git+https://git.example.com/MyProject.git@master
MyProject @ git+https://git.example.com/MyProject.git@v1.0
MyProject @ git+https://git.example.com/MyProject.git@da39a3ee5e6b4b0d3255bfef95601890afd80709
MyProject @ git+https://git.example.com/MyProject.git@refs/pull/123/head
```

so ya u can use any git ref *in the project dependencies* but only IG specific commit hashes/tags are allowed *on PyPI* 

abstractly

```
<pkg_name> <version_specifier> @ <protocol>+<url>@<ref>
```

and i assume the behavior there would be for pypi to clone the given repo at the specific ref and then try and check it against the version specifier after cloning, as pip loves to do. I wonder if you specify the ref as a branch if it walks backwards through commits until it finds a matching one? i literally love watching pip do that, very comical

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +The `requirements.txt` file used to be the default way to store dependencies. However in recent years, the ecosystem has moved to storing all of this information in a single **pyproject.toml** file.
Was there another side to that "either"?
Also, is this Admonition _too_ soon? It seems jarring to have a detour before the first line of this guide; maybe right after the opening section.

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +necessary to install and use your package in the `[dependencies]` section. This minimized the number of additional packages that both your users and packages that depend upon your package have to ins
Just to use. Dependencies are what are needed by the package while it is running. If there are installation dependencies, those would be specified in `build-system.requires`

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +a user needs to install and use your package. Dependencies can be stored in a
This sentence sounds too active to me. The user doesn't need to take action or even know about the dependencies to use the package. Dependencies simply must be present in the environment for the project to run.

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Some versions of shell including all of the modern Macs that now use zsh shell, support the square bracket syntax. In those cases you will need to add
Can we just say "shells" instead of versions of shell? (and on the last line of the tip) These are totally different programs, different programming languages, in some cases sharing no common ancestry.

Also, IMO "support the square bracket syntax" makes it sound like zsh supports _pip_ using `[]` and it's the other shells that can't handle it.

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Above we reviewed how to install dependencies from your pyproject toml. In some cases you may want to group sets of dependencies like so:
s/pyproject toml/pyproject.toml/

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +```{tip}
I think this is now covered by the earlier introduction.

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage`
`python -m pip` 😉

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Python package published on PyPI (or on GitHub/ GitLab) as a dependency. Once create this file, declare dependencies, [build your package](python-package-distribution-files-sdist-wheel.md) and [publi
s/Once/Once you/

2023-12-07 04:46 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +:::{admonition} Dependencies using other front-end build tool like PDM, Hatch or Poetry
It shouldn't be. The example you gave used pip to install the readthedocs dependencies. pip can install any PDM, Hatch, etc project, including any optional dependencies they specify. Even if specified in a metadata format other than `project.optional-dependencies`. (but not, I suppose, if they are specified as a type of environment and not an optional)

2023-12-07 06:20 UTC, sneakers-the-rat commented on package-structure-code/declare-dependencies.md
> +The above workflow assumes that you want to publish your package on PyPI. And then you plan to publish to conda-forge (optionally), [by submitting a recipe using greyskull](https://www.pyopensci.org/
agreed. same thought as here: https://github.com/pyOpenSci/python-package-guide/pull/106#discussion_r1418439337

put conda on its own page, just allude to it here <3

2023-12-07 06:25 UTC, sneakers-the-rat commented on package-structure-code/declare-dependencies.md
> +your package infrastructure.
you definitely can! either make a dummy package with just an `__init__` file or else with poetry i install it with `--no-root` (but i don't think it really matters i was mostly joking)

2023-12-07 06:33 UTC, sneakers-the-rat commented
Copying reply from slack just for the sake of having it public in the issue:

re: this comment - https://github.com/pyOpenSci/python-package-guide/pull/106#issuecomment-1843942078

Put this at the top of the file:

````
```{eval-rst}
:og:title: my fancy title
```
````

it turns out they aren’t actually sphinx roles, but that extension’s parser looks for strings matching that pattern that sorta looks like a role, but if myst gets to it first then it misses them, so you need to wrap in the eval-rst block

without the extension you would use this https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#html-meta

````
```{meta}
:og:title: My title
:description: whatever other meta tags you want
```
````

gets you
```html
<meta name="og:title" content="My title">
<meta name="description" content="whatever other meta tags you want>
```

2023-12-07 16:09 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +If you want to support conda users, you may want to also maintain a conda environment that they can use to install your package. Maintaining a conda environment will also help you test that your pack
that is a great idea. i do think it's important information!!

2023-12-07 16:13 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +The `requirements.txt` file used to be the default way to store dependencies. However in recent years, the ecosystem has moved to storing all of this information in a single **pyproject.toml** file.
agreed. @ucodery i just reorganized the top of the page - have a look at the newest version. i lead now with "what is a dependency" THEN there are different types of dependencies - optional / development and required... 
then i left space for @sneakers-the-rat to add more about how to specify dep versions in a TODO (which will be a later PR). 

see what you think about the new intro. i think it's much more user friendly but i bet the text could use other sets of eyes beyond mine.

2023-12-07 16:41 UTC, lwasser reviewed
looks good - i'm suggesting a few changes! (select request changes if you can!(

2023-12-07 16:41 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +A Python package dependency refers to an external package or
comment here

2023-12-07 16:41 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +software that your Python project requires to function properly.
another comment. once you are done - you have to finish your review!

2023-12-07 17:25 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +Some versions of shell including all of the modern Macs that now use zsh shell, support the square bracket syntax. In those cases you will need to add
new text

> There are different shell applications that you and your package contributors might use.
> * zsh is the shell that comes with most Mac OS computer 
> * Windows users may use a tool such as git bash 
> 
> Many shells don't support the bracket `[tests]` syntax which is why we add 
> quotes to the command in this guide like this:
> 
> `python -m pip install ".[tests]"`
> 
> In some cases you may see syntax without the quotes in guidebooks or contributing 
> guides like the example below:
> 
> `python -m pip install yourPackage[tests]`
> 
> Calling yourPackage[tests] without the double quotes will work on some shells but not all.

2023-12-07 17:26 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install yourPackage`
good catch - fixed!

2023-12-07 17:26 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +Python package published on PyPI (or on GitHub/ GitLab) as a dependency. Once create this file, declare dependencies, [build your package](python-package-distribution-files-sdist-wheel.md) and [publi
fixed!

2023-12-07 17:29 UTC, lwasser commented
@sneakers-the-rat (i always chuckle a bit because your username is so awesome). 

i added an intro at the top of the page titled "What are dependencies". that is like guidebook / tutorial 101 that i forgot! but i left a TODO admonition for you to work on the specifiers related to adding deps!! 

i THINK i captured everyone's comments here - but if you re-read the page and i missed something please do call it out. when you get above 100+ comments in a review - github starts hiding things and it's really easy to miss comments. but hopefully i caught them all. really great work everyone catching issues / typos / mistakes etc! thank you.

2023-12-07 17:51 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Above we reviewed how to install dependencies from your pyproject toml. In some cases you may want to group sets of dependencies like so:
AH, I forget all the time you can now do this in github. All these fancy cloud features 😃

2023-12-07 19:53 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +Above we reviewed how to install dependencies from your pyproject toml. In some cases you may want to group sets of dependencies like so:
right? so many fancy cloud features. it's no worry i just didn't want you to feel like you couldn't make corrections if you want to. comments are find but inline corrections are always welcome! :)

2023-12-07 19:57 UTC, lwasser commented
i just made a few more fixes following review comments And i added a graphic to explain optional vs required dependencies given we've reorganized that section a bit to be more clear. 
![python-package-dependencies](https://github.com/pyOpenSci/python-package-guide/assets/7649194/35ead625-1038-487f-b02a-1101ea37db53)

i think we are super close. i'll stop working on this for now and let me comments roll in before working on it again.

2023-12-07 20:22 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +necessary to install and use your package in the `[dependencies]` section. This minimized the number of additional packages that both your users and packages that depend upon your package have to ins
```suggestion
necessary to install and use your package in the `[dependencies]` section. This minimizes the number of additional packages that your users must install as well as the number of packages that depend upon your package must also install.
```

2023-12-07 20:25 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +Below we've created 3 sets of optional dependencies named: tests, docs and lint:
```suggestion
Below we've created three sets of optional dependencies named: tests, docs and lint:
```

2023-12-07 20:26 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +project, you will need to point to a specific commit/tag of that repository in
```suggestion
project, you will need to point to a specific commit/tag/hash of that repository in
```

2023-12-07 20:26 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +Calling pip using `python -m` ensures that the pip that you are using to install your package comes from your current active Python
```suggestion
Calling pip using `python -m` ensures that the `pip` that you are using to install your package comes from your current active Python
```

2023-12-07 20:27 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +* dependencies needed for your documentation,
```suggestion
* dependencies needed for your documentation (`docs`),
```

2023-12-07 20:28 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +Calling yourPackage[tests] without the double quotes will work on some shells but not all.
```suggestion
Calling yourPackage[tests] without the double quotes will work on some shells *but not all*.
```

2023-12-07 20:32 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +Thus, if you are running a conda environment, installing your package in editable mode risks dependency conflicts. This is particularly important if you have a spatial package that required GDAL or h
```suggestion
Thus, if you are running a conda environment, installing your package in "editable" mode risks dependency conflicts. This is particularly important if you have a spatial package that requires geospatial system libraries like GDAL or another system-level dependency.
```

2023-12-07 20:34 UTC, Zeitsperre commented on package-structure-code/declare-dependencies.md
> +Read the Docs is a documentation platform with a continuous integration / continuous deployment service that automatically builds and publishes your documentation.
```suggestion
[Read the Docs](https://readthedocs.org) is a documentation platform with a continuous integration / continuous deployment service that automatically builds and publishes your documentation.
```

2023-12-07 22:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +This means that in order for plotMe to work in a users `environment` when installed, you also need to ensure that they have both of those required `dependencies` installed in their environment too.
```suggestion
This means that in order for plotMe to work in a user's `environment` when installed, you also need to ensure that they have both of those required `dependencies` installed in their environment too.
```

2023-12-07 22:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Declaring a dependency in your `pyproject.toml` file will ensure that it is listed as a required dependency when published to PyPI and that it is automatically installed by pip or conda into a users
```suggestion
Declaring a dependency in your `pyproject.toml` file will ensure that it is listed as a required dependency when your package is published to PyPI and that a package manager (`pip` or `conda`) will automatically install it into a user's environment alongside your package:
```

2023-12-07 22:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +* zsh is the shell that comes with most Mac OS computer
```suggestion
* zsh is the shell that comes by default on newer Mac OS computers
```

2023-12-07 22:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Many shells don't support the bracket `[tests]` syntax which is why we add
```suggestion
Some shells don't support unquoted brackets (`[tests]`) which is why we add
```

2023-12-07 22:53 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +In some cases you may see syntax without the quotes in guidebooks or contributing
```suggestion
In some cases you may see commands without the quotes in guidebooks or contributing
```

2023-12-08 17:49 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +:::{admonition} Dependencies using other front-end build tool like PDM, Hatch or Poetry
you are right. i was confusing things, @ucodery i think what i noticed is that PDM, hatch poetry add dependencies to the pyproject.toml differently (hatch may not add them yet actually). but installation (with pip) could be similar. this is what i just don't know. poetry has it's own tables i think - can pip still install from them?

but i think a bigger takeaway for me here potentially is that we don't need to confuse our readers with the nuances of all of these tools here - they can read the docs. and we can link to the RTD docs for builds that use other tools such as poetry if users want to use those tools. hopefully the changes i've made make this all more clear and address your comments!!

2023-12-08 20:07 UTC, jhkennedy commented
Looks great!

2023-12-08 20:19 UTC, lwasser commented
@all-contributors please add @jhkennedy for code, review

2023-12-11 06:48 UTC, mknorps commented
Looks great and will help a lot of people :heart: @

2023-12-14 23:54 UTC, lwasser commented
@all-contributors please add @mknorps for code, review

2023-12-15 18:27 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install .[docs]`
ok so my goal today is to get this PR merged. BUT if we decide on another approach to the quotes we can ALWAYS open a new pr. here is where i am with this

* we are using double quotes throughout the guide as based upon @ucodery analysis of various shells, that seems to be something that works in most (but not all shells)
* I do have a breakout about the quotes and zsh users where i talk about single vs double quotes - it is below:
<img width="839" alt="Screenshot 2023-12-15 at 11 24 19 AM" src="https://github.com/pyOpenSci/python-package-guide/assets/7649194/a534aef8-33a3-4794-aa5e-a53ccf8ca4bf">

Where i am with this
1. it occured to me that MANY MANY beginner users will have no idea what zsh is. honestly bash / shell is a really confusing topic to MANY scientists and even getting them started on windows with something like gitBash was something we'd really have to walk people through. So we may want to think about a bit more information around bash even if it's a separate lesson. i'm going to open a issue with this same language where we can discuss -  but wanted to mention that here. 
2. @sneakers-the-rat some people may be interested in .zshrc customization as you highlighted below. i didn't know that was possible. i wonder if that could be added to a page on setting up shell and being aware of what type of shell you are using -  somewhere 

i know that this topic will be a potential stumbling block for a subset of our users.

2023-12-15 18:30 UTC, lwasser commented on package-structure-code/declare-dependencies.md
> +`pip install .[docs]`
ok [issue opened here](https://github.com/pyOpenSci/python-package-guide/issues/134). 

i'll resolve this thread for now but we can revisit after gaining a better understanding of guidance community folks might need around various shell options.

2023-12-15 18:48 UTC, lwasser commented
ok y'all!! i'm thrilled! i believe i've incorporated EVERYONE's feedback both from slack (where we discussed graphics) and here. i feel good about merging this for now. we have had extensive review and discussion and have landed i think on some good content. 

Given this is a living community guidebook, we can always adjust / fix / make better through pr's.

I opened an issue  (#134) around the shell discussion which actually was fairly extensive. I think will be a user pain point for some but it's out of scope for this specific PR so let's revisit it! 

All checks are now passing. i am going to merge this!

2023-12-15 18:49 UTC, merged

2023-12-15 21:55 UTC, sneakers-the-rat commented
Nice work every1 :)

2023-12-16 03:08 UTC, ucodery reviewed
II realize this already merged so I just left some copy edits 😆

2023-12-16 03:08 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +When a user installs your package locally using python -m pip install your-package only your package and it's core dependencies get installed. When they install your package `[tests]` pip will instal
```suggestion
When a user installs your package locally using `python -m pip install your-package` only your package and it's core dependencies get installed. When they install `your-package[tests]` pip will install both your package and its core dependencies plus any of the dependencies listed within the tests array of your `[optional.dependencies]` table.

2023-12-16 03:08 UTC, ucodery commented on package-structure-code/declare-dependencies.md
> +Within those 2 groups, there are three use cases that you can think about. 1. Core dependencies are **required** for a user to use your package. 2. Development dependencies are optional and only need
```suggestion
Within those two groups, there are three use cases that you can think about. 1. Core dependencies are **required** for a user to use your package. 2. Development dependencies are optional and only needed if someone wants to work on your package locally. 3. Finally feature dependencies are optional and add additional functionality to your package. Not all packages will have feature dependencies.
```