ADD: Documentation section to our packaging guide
pyOpenSci/python-package-guide pull request #14
Opened 2022-11-30 18:12 UTC by lwasser

2022-12-02 13:30 UTC, SimonMolinsky commented on documentation/contributing-file.md
> +* A link to a development guide if you have one
What else:

* Information about licensing, especially if someone pulls a code into a package,
* A link to social networks or forms where contributions can be made.

2022-12-02 13:31 UTC, SimonMolinsky commented on documentation/contributing-file.md
> +The root of your GitHub repository sshould also have a License.txt file.
Typo:

Is: `The root of your GitHub repository sshould also have a License.txt file.`

Should be: `The root of your GitHub repository should also have a License.txt file.`

2022-12-02 13:32 UTC, SimonMolinsky commented on documentation/contributing-file.md
> +
Maybe here it would be nice to point out that license is needed if package is published on PyPI and conda :) So no license == no publication!

2022-12-02 13:36 UTC, SimonMolinsky commented on documentation/index.md
> +how to use the tools in your package, then they won't use your tool.
I'm not sure if there are too many **tools** in here, maybe this sounds slightly better:

Is: `However, if users don't understand how to use the tools in your package, then they won't use your tool.`

Could be: `However, if users don't understand how to use your package, then they won't use it.`

OR

Could be: `However, if users don't understand how to use the tools in your package, then they won't use it.`

2022-12-02 13:43 UTC, SimonMolinsky commented on documentation/index.md
> +3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user facing in your package. This mean means that your packa
Proposition of change:

`3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that the user is facing in your package. This means that your package methods and classes have docstrings that are formatted with explanations of each variable. Even better is to use short vignettes that demonstrate how to use the function or class. If you don't know what API documentation means, this section is for you!`

2022-12-02 14:14 UTC, SimonMolinsky commented on documentation/package-documentation-sphinx.md
> +Both of the above themes support [myst](https://myst-parser.readthedocs.io/) which allows you to build your package
Wow, I've learned a new useful thing. Thank you! :)

2022-12-02 14:18 UTC, SimonMolinsky commented on documentation/package-documentation-sphinx.md
> +documentation in `markdown` rather than `.rst`.
Maybe it will be nice to add one sentence more, for example:

---

Why `markdown` instead of `restructured text`? There are three reasons. Most of your core text files within a project are in `.md` format, and GitHub / Jupiter Notebook styling uses this format.

2022-12-02 14:22 UTC, SimonMolinsky commented on documentation/readme-file-best-practices.md
> +* Your file on package manager landing pages like PyPI and Anaconda
Is:

`* Your file on package manager landing pages like PyPI and Anaconda`

Should be:

`* Your package landing page on a package manager services like PyPI and Anaconda`

2022-12-02 14:25 UTC, SimonMolinsky commented on documentation/readme-file-best-practices.md
> +* and included in package health landing pages such as snyk
Maybe URL to snyk? so it will look like:

`* and included in package health landing pages such as [snyk](https://snyk.io/advisor/python)`

2022-12-02 14:26 UTC, SimonMolinsky commented on documentation/readme-file-best-practices.md
> +- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you do'nt know what a wrapper is - this probably doesn't apply to you!)
A typo:

`- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you don't know what a wrapper is - this probably doesn't apply to you!)`

2022-12-02 14:30 UTC, SimonMolinsky commented on documentation/readme-file-best-practices.md
> +###  ✔️ Badges for current package version, continuous integration and test coverage
Could be a badge with a license too (?)

2022-12-02 14:30 UTC, SimonMolinsky commented on documentation/readme-file-best-practices.md
> +### ✔️ A Community Section with Links to Contributing Guide, Code of Conduct
a link to the license?

2022-12-02 14:33 UTC, SimonMolinsky requested changes
I've put some comments to change/fix small typos in docs.

2022-12-13 22:32 UTC, lwasser commented on documentation/index.md
> +how to use the tools in your package, then they won't use your tool.
Great suggestion! thanks!

2022-12-13 22:35 UTC, lwasser commented on documentation/index.md
> +3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user facing in your package. This mean means that your packa
ok that paragraph was totally confusing. i changed it to this:

```
3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user-facing (*available for a user to see*) in your package. This mean means that your package methods and classes have [docstrings](https://pandas.pydata.org/docs/development/contributing_docstring.html). These docstrings should describe both the purpose of the code element and each input and output. To help your users better understand how to use your package, you can include short code examples that demonstrate how to use the function or class in each docstring. If you don't know what API documentation means this section of the pyOpenSci Python packaging guide is for you!
```

Let me know what you think!

2022-12-13 22:47 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +Both of the above themes support [myst](https://myst-parser.readthedocs.io/) which allows you to build your package
yahoo!!

2022-12-13 22:49 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +documentation in `markdown` rather than `.rst`.
excellent suggest! fixed!

2022-12-13 23:03 UTC, lwasser commented on documentation/package-documentation-sphinx.md
>  # Python Package Documentation
After setting this up myself for the first time in a while i'm reminded of HOW confusing this ecosystem is. I think that this packaging guide is not enough. And we need some complementary tutorials to go along with it. These tutorials need to explain what extensions to use and how to set things up.

An example conf.py file in a repo with some documentation is probably ideal with tutorials that explain all of the parts. otherwise it's a huge rabbit hole.

2022-12-14 00:01 UTC, lwasser commented on documentation/contributing-file.md
> +# Contributing, License and Code of Conduct Files in your Python Open Source Package
TODO: [this file](https://github.com/pyOpenSci/python-package-guide/blob/1a827fe85aeec1a0878e850770a2a256d75bf8e8/package-structure-code/collaboration.md) in an open PR that i will close once i'm sure all of the content is moved here needs to be considered when updating this file. there is some good stuff about the contributors covenent website and such there

2022-12-15 15:05 UTC, Batalex commented on documentation/readme-file-best-practices.md
> +This description ideally includes a quick start vignette that provides a code sample demonstrating use of our package.
for consistency

```suggestion
This description ideally includes a quick start vignette that provides a code sample demonstrating use of your package. 
```

2022-12-15 15:05 UTC, Batalex commented on documentation/readme-file-best-practices.md
> +Include descriptive links to to:
```suggestion
Include descriptive links to:
```

2022-12-20 14:55 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
> +* **API  documentation:** API documentation is generated from [docstrings](https://pandas.pydata.org/docs/development/contributing_docstring.html) found in your code. Ideally you have docstrings for
Probably we should define what API stands for and explain how that relates to docstrings, i.e. the docstrings are closest to the API itself so it makes sense to that a significant portion of the API documentation can be generated from the in an automated fashion

2022-12-21 16:56 UTC, NickleDave reviewed
Looks great, our documentation guide is well documented :stuck_out_tongue:  
Feels like we are almost ready to start reviewing a lot of packages!!! :grinning: 
Hope this feedback helps some

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
> +### Python docstring format best-practices
```suggestion
### Python docstring format best practices 
```
Above you do not hyphenate best practices. Changing here for consistency.
Not sure a hyphen is needed here and if possible I would reword to avoid the noun stack, maybe just "Python docstring formats"?

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
> +your package. We suggest using [numpy-style docstrings](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).
We should probably list the other two common formats and link to them as well.  
Then we should give a rationale for why we suggest using NumPy.  
I'm guessing the rationale is something like "because most other scientific packages adopt the NumPy format".
I also suggest writing "NumPy format" as the Napoleon documentation does, with NumPy capitalized as the developers write it, and without a hyphen:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html

There is also a link to the Google docstring format spec in the Napoleon index (https://google.github.io/styleguide/pyguide.html#Comments)

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
> +If you are using `numpy-style` docstrings, be sure to include the sphinx napoleon
```suggestion
If you are using NumPY format docstrings, be sure to include the sphinx napoleon 
```

change `numpy-style` -> NumPy format (remove monospace or be consistent with monospace throughout)

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
Is this copied verbatim from geopandas?
I think there's usually line breaks between the short description, Parameters, and Returns.
And it should be "Returns" with an "s", not "Return".
See example here:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy

```Python
def extent_to_json(ext_obj):
    """Convert bounds to a shapely geojson like spatial object.
    This format is what shapely uses. The output object can be used
    to crop a raster image.

    Parameters
    ----------
    ext_obj: list or geopandas geodataframe
        If provided with a geopandas geodataframe, the extent
        will be generated from that. Otherwise, extent values
        should be in the order: minx, miny, maxx, maxy.

    Returns
    ------
    extent_json: A GeoJSON style dictionary of corner coordinates
    for the extent
```

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
I know this didn't change in the review but I would also update the following

```
Notice that this function's 
docstring includes all parameter inputs and outputs. The description of the function 
is short and to the point (2 to 3 sentences). And the return of the function is 
specified. 
```

to:

```
Notice that this function's 
docstring includes all parameters and return values. The description of the function 
is short and to the point (2 to 3 sentences). And the return of the function is 
specified. 
```

2022-12-21 16:56 UTC, NickleDave commented on documentation/package-documentation-sphinx.md
> +Using the above numpy-style docstring in sphinx, the autodoc extension will
```suggestion
This image shows how the sphinx autodoc extension converts the example docstring above in NumPy format into an entry in the API documentation for the `extent_to_json` function. The output of ...
```

I would rewrite the image caption this way to make explicit the link to the example above and to explain this is API documentation

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +* community health by github
Add a link here to GitHub docs on community health? I have no idea what this means (except I know you just taught yourself a bunch about it) so I'm guessing a person totally new to this won't take much from it either

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +* and included in package health landing pages such as snyk
:+1: yes a link to snyk would be good too

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +* and included in package health landing pages such as snyk
Revise so that bullet points are consistent?

```
The README is also often used as part of a measure of package and community health. For example:
* [GitHub community health](link)
* [Snyk package health](link)
```

Or possibly just write as a single sentence? I'm not sure how bullet points help a reader here since they seem to arbitrarily break up the train of thought

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for [Pandera](https://github.com/unionai-oss/pandera), a pyOpenSci vetted package. *(screen shot
```suggestion
Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for the pyOpenSci package [Pandera](https://github.com/unionai-oss/pandera). *(screen shot taken Nov 23 2022)*
```
Just say say "pyOpenSci package" or "a package that has gone through pyOpenSci review"?
"a pyOpenSci vetted package" sounds a bit off to me. We did more than vet it, I think

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you do'nt know what a wrapper is - this probably doesn't apply to you!)
```suggestion
- [ ] If your package is a [wrapper](https://en.wikipedia.org/wiki/Wrapper_library) (that provides an interface to another library), link to the library that it wraps and any associated documentation.
```
suggest briefly defining wrapper instead of saying "thing you don't know about doesn't apply to you"

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you do'nt know what a wrapper is - this probably doesn't apply to you!)
also suggest "library" over "package" since wrappers are likely to not be a Python package

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +- [ ] Links to your packages documentation / website.
```suggestion
- [ ] Links to your package's documentation / website.
```

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +Consider writing for a 12th grade reading level which is an ideal level for more scientific content that serves a broad user base. The goal of this description to maximize accessibility of your **REA
:+1: agreed that "12th grade" sounded a bit specific when I read it although I know what you mean

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +This description ideally includes a quick start vignette that provides a code sample demonstrating use of our package.
```suggestion
This description ideally includes a brief code snippet demonstrating use of your package. 
```

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +A short quick-start vignette that shows a user how to use your package is plenty for the README file. All other tutorials and documentation should be presented as descriptive links.
```suggestion
A short quick-start guide that shows someone how to use your package is plenty for the README file. All other tutorials and documentation should be presented as descriptive links. 
```
suggest revising to avoid repeating "user", "use"

2022-12-21 16:56 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +* your code of conduct.
```suggestion
* your code of conduct
```
suggest either removing period for consistency with other bullet points or adding periods to all of them
https://www.instructionalsolutions.com/blog/bulleted-list-punctuation

2022-12-21 17:26 UTC, NickleDave commented
@lwasser adding suggestion from Slack discussion to explain how to write vignettes, and outline tools: sphinx-gallery, nbsphinx + myst-nb

I have an example of using jupytext + myst-nb here
https://raw.githubusercontent.com/vocalpy/crowsetta/main/doc/howto/howto-user-format.md
Basically a matter of adding yaml front matter and then running the notebook with 
This is nice because you can run and test in Jupyter lab **and** have the myST directives in your vignette, for when you will want to ref other parts of the docs.
A slight gotcha is that you need to use `myst-nb` in your extensions and **not** `myst_parser`, as I'm doing here:
https://github.com/vocalpy/crowsetta/blob/28fd13613c3d08d0592ca522b86b87e669efd3b8/doc/conf.py#L42

2022-12-22 00:40 UTC, lwasser commented
This Pr is missing a section about accessibility related to documentation. just noting that and once it's merged i can create a new pr on top of it to address accessibility.

2022-12-22 00:42 UTC, lwasser commented
@NickleDave does that example approach actually run the code tutorial code and render it? if it doesn't i'd suggest we just suggest sphinx gallery.

2022-12-22 00:45 UTC, lwasser commented
@NickleDave i love adding this content. i was thinking... so this pr doesn't get huge like the peer review guide did:) what do you think about focusing just on what's here. And what i can do is open an issue to add both tutorials and accessibility which is totally missing from this pr. that way we can get this merged and work on that separately.

2022-12-23 11:05 UTC, arianesasso commented on documentation/readme-file-best-practices.md
> +Consider writing for a 12th grade reading level which is an ideal level for more scientific content that serves a broad user base. The goal of this description to maximize accessibility of your **REA
I made the same comment above. Even high school might be too specific for certain countries. I would go with a child's age, e. g. 14 years old (I am not sure which age people enter high school in the US 😆).

2022-12-23 11:05 UTC, arianesasso commented on documentation/readme-file-best-practices.md
> +This description ideally includes a quick start vignette that provides a code sample demonstrating use of our package.
A quick start guide?

2022-12-23 11:05 UTC, arianesasso commented on documentation/readme-file-best-practices.md
> +* your code of conduct.
I have been adding bullet points everywhere haha, I am not sure what is the overall consensus here 😅

2022-12-27 20:28 UTC, lwasser commented on documentation/package-documentation-sphinx.md
>  # Python Package Documentation
moved this over to slack as you saw :) i love looking at simpler options. it seems like most are using sphinx right now so we might have to start there to be consistent across the ecosystem and watch to see if things change. it looks like a really nice platform and if it's rooted in MD it's probably simpler to config from the start. i think most of the sphinx extensions are ones that kind of work around .rst.

2022-12-27 20:29 UTC, lwasser commented on documentation/index.md
> +1. [A clear and to the point **README.md** file](readme-files)
good catch!

2022-12-27 20:31 UTC, lwasser commented on documentation/contributing-file.md
> +* A link to a development guide if you have one
gosh yes - i thought i had added this website but obviously not! https://www.contributor-covenant.org/ 

but we do ask for the license information in the readme file rather than the contributor file. Maybe look at that section and see what you think?.

2022-12-27 20:37 UTC, lwasser commented on documentation/contributing-file.md
> +The root of your GitHub repository sshould also have a License.txt file.
thanks!

2022-12-27 20:40 UTC, lwasser commented on documentation/contributing-file.md
> +
good point. i think we have a few complex use cases to consider with licensing. In some of our open forums in the past some have mentioned that adding specific licenses can be hard in some environments... agency or government came up specifically. So while i think we want to strongly encourage it, it is also important to consider those use cases. We are not a publisher at the end of the day but we do want software to get cited.

2022-12-27 20:42 UTC, lwasser commented on documentation/contributing-file.md
> +
this is what we wrote related to this

`To be reviewed by pyOpenSci your project should use an open source 
software license that is approved 
by the Open Software Initiative (OSI).` 

i do think however if push came to shove and adding a formal license was not possible we would have a discussion. i might ask ropensci how they deal with that.

2022-12-27 20:43 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* Your file on package manager landing pages like PyPI and Anaconda
fixed!

2022-12-27 20:43 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* community health by github
fixeD

2022-12-27 20:47 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* and included in package health landing pages such as snyk
fixed!

2022-12-27 20:48 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you do'nt know what a wrapper is - this probably doesn't apply to you!)
fixed!

2022-12-27 20:49 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +###  ✔️ Badges for current package version, continuous integration and test coverage
huh good point. i haven't seen license badges used too widely given there is a file in the repo called LICENSE. id say if someone really wants that it could be optional. I think the tests, CI docs building etc and python versions are probably more important.

2022-12-27 20:51 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +### ✔️ A Community Section with Links to Contributing Guide, Code of Conduct
what do you think about that going in the section related to citation? license and citation?

2022-12-27 20:53 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +### ✔️ A Community Section with Links to Contributing Guide, Code of Conduct
ok i added it here. it does make sense. thank you for being so on top of license items!!!

2022-12-27 21:03 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +Consider writing for a 12th grade reading level which is an ideal level for more scientific content that serves a broad user base. The goal of this description to maximize accessibility of your **REA
😆 y'all rock. will change this. appreciate the feedback.

2022-12-27 21:07 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* community health by github
because of the other changes i am not going to merge this as it now conflicts! but did make the fix locally :) thanks!

2022-12-27 21:37 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +* **API  documentation:** API documentation is generated from [docstrings](https://pandas.pydata.org/docs/development/contributing_docstring.html) found in your code. Ideally you have docstrings for
Great idea. also added how it's important for user facing docs ie `help()` !

2022-12-27 21:38 UTC, lwasser commented
> Looks great, our documentation guide is well documented 😛 Feels like we are almost ready to start reviewing a lot of packages!!! 😀 Hope this feedback helps some

Thanks. I'm actually a bit embarrassed looking at this now. i feel like i was writing it when i was stressed and at home as i see a lot of mistakes. But i do think that we are getting there!! And i'm eternally grateful to have so many different sets of eyes on this stuff!! so thank you!

2022-12-27 21:40 UTC, lwasser commented
y'all becuase there are so many comments here i'm resolving all of them except maybe a few. this is ONLY because i keep losing track of what i've looked at not because i'm not allowing any more feedback. i welcome more feedback as it's useful!

2022-12-27 21:41 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +This description ideally includes a quick start vignette that provides a code sample demonstrating use of our package.
definitely! look at my typos everywhere. 🙈

2022-12-27 21:43 UTC, lwasser commented
https://github.com/pyOpenSci/python-package-guide/pull/14#discussion_r1056245150 
@arianesasso trying to understand this comment. i can't find the Y in question. can you kindly help me understand what i need to fix i must just be missing it.

2022-12-27 21:44 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +* Consider writing writing instructions for a 12th grade level reader.
totally. not commit this only because i made both edits locally. thanks! fixed!

2022-12-27 21:47 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +### What tools to use to build your documentation: sphinx
ok one thing to consider here is that 
1. we don't want to provide too many tools as examples. especially if the community is largely using sphinx. 
2.  we will tutorials that cover the specifics of all of this. this is a guide for what tools people should use. 
Finally myst is a plugin for sphinx so it's really different than (tell me if i'm wrong) mkdocs is a different engine altogether right? my understanding is it's a static site generator kind of like jekyll. so it's a whole different animal / engine than sphinx

2022-12-27 21:49 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +### What tools to use to build your documentation: sphinx
if a student was new only knew about markdown (i think about my students) and markdown worked, probably it would be cognitive overload to teach both rst and md. or i wouldn't chose to teach both! 

i think a simple breakout mentioning rst is warranted but i wouldn't go into detail in a guide as it risks serious cognitive overload in an already complicated ecosystem!

2022-12-27 22:40 UTC, lwasser commented on documentation/contributing-file.md
> +# Contributing, License and Code of Conduct Files in your Python Open Source Package
ALSO TODO: add a note about github issue templates in this section...

2022-12-27 22:43 UTC, lwasser commented on documentation/contributing-file.md
> +* A code of conduct file
fixed!

2022-12-27 22:44 UTC, lwasser commented on documentation/contributing-file.md
> +* allow technically inclined contributors to make thoughtful and useful code based pull requests to your repository
fixed. i'm fighting with github today so just making changes locally ;(

2022-12-27 22:45 UTC, lwasser commented on documentation/contributing-file.md
> +The root of your GitHub repository sshould also have a License.txt file.
fixed!

2022-12-27 22:47 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +
this is the get started landing page. i'll add a screen shot of what this looks like. it's a basic landing page approach that everyone i think should use.  we use it on all of our guides as well. so there is no pip install they are literally all cards with links to key areas. it addresses the issue if guiding a user  where to go... 
<img width="906" alt="Screen Shot 2022-12-27 at 3 46 48 PM" src="https://user-images.githubusercontent.com/7649194/209731663-0a2baed1-7a2a-4c44-bd9a-c60c4adcbe6b.png">

2022-12-27 22:48 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +
making a note to add a screenshot for what this looks like to the guide. in our tutorials we will show them how to create the cards.

2022-12-27 22:50 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +- [ ] If it's your package is a wrapper, link to the package that it is wrapping and any associated documentation. (If you do'nt know what a wrapper is - this probably doesn't apply to you!)
so weird. i had edits on this section from other people too. i've merged them in and no longer use the word wrapper.

2022-12-27 22:51 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +This description ideally includes a quick start vignette that provides a code sample demonstrating use of our package.
fixed!

2022-12-27 22:52 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +A short quick-start vignette that shows a user how to use your package is plenty for the README file. All other tutorials and documentation should be presented as descriptive links.
fixed!

2022-12-27 22:53 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* your code of conduct.
i'm a fan of bullets - BUT maybe not as many as ropensci uses in their guides (which are all bullets). i think breaking up text allows someone to more easily skim.

2022-12-27 22:54 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* your code of conduct.
locally none have periods now. github really messed up some of the comments on the same lines of text here... bare with me...

2022-12-28 00:06 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +Sphinx has documentation themes that are easy to apply and help you quickly and easily build an easy-to navigate website.
ok! fixed locally!

2022-12-28 00:07 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +All of the above themes support [myst](https://myst-parser.readthedocs.io/)
reworded the entire section!

2022-12-28 00:09 UTC, lwasser commented on documentation/package-documentation-sphinx.md
>  1. [myST:](https://myst-parser.readthedocs.io/en/latest/intro.html) myST is a fusion of markdown and rST. It is a nice option if you are more comfortable writing markdown. But more flexible than mark
i'm pretty sure the second element here was rst. but i actually rewrote this entire thing to include vanilla markdown as well. frankly that was my first step into sphinx rst + md to support some md files (like readme).

2022-12-28 00:27 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +If you are using `numpy-style` docstrings, be sure to include the sphinx napoleon
oh now i see where your comment came from. my goodness GitHub really did some weird things today with all of these comments. i just saw this @arianesasso by itself in a list of other comments. i've made this change throughout  except where do you see the Y capitalized? https://numpy.org/ i don't see that in the numpy docs :) i almost wrote dogs :)

2022-12-28 00:29 UTC, lwasser commented on documentation/package-documentation-sphinx.md
no this is from earthpy. but yes i just copied it over so its likely that we made a mistake there or i made a mistake copying! the lack of spaces is definitely from me here. we gave geopandas some of our code but not this guy. before we knew about rioxarray and all of it's magic powers.

2022-12-28 00:33 UTC, lwasser commented on documentation/package-documentation-sphinx.md
ok fixed! combo of leah-error and maybe leah-error like 5 years ago with the returns but normally i catch that!  
what's really interesting is that it's wrong in the code

https://github.com/earthlab/earthpy/blob/main/earthpy/spatial.py

but the docs print fine - they print _returns_. (not return) 🤷‍♀️

2022-12-28 00:35 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +- [ ] Links to your packages documentation / website.
fixed!

2022-12-28 00:38 UTC, lwasser commented on documentation/index.md
> +3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user-facing (*available for a user to see*) in your package.
let me see - do you mean to that page in the documentation on docstrings?
i wonder if these should be cards... i'm going to keep going and come back to this comment to re-evaluate that landing page. sometimes having things on separate pages is nice because it's easier to direct people to specific content ... and it keeps pages shorter / more skimmable.

2022-12-28 00:42 UTC, lwasser commented on documentation/index.md
> +3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user-facing (*available for a user to see*) in your package.
fixed!!

2022-12-28 00:43 UTC, lwasser commented on documentation/package-documentation-sphinx.md
> +your package. We suggest using [numpy-style docstrings](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).
i'll add it in a breakout. NOTE i'm intentionally trying to not list everything. i just think it's additional weight that a reader doesn't need especially if they are a beginner. it would be like my teaching my earth analytics course and trying to teach both r and python - both can do the same thing but they are different. there are a few other formats out there as well.

2022-12-31 10:40 UTC, arianesasso commented on documentation/index.md
> +3. **Package API documentation.** Package API documentation refers to documentation for each class, function, method and attribute that is user-facing (*available for a user to see*) in your package.
Yes, somehow, I couldn't see the link before 😅 .

2023-01-06 00:11 UTC, lwasser commented
@all-contributors
please add @arianesasso  for documentation, design. 
please add @SimonMolinsky for documentation, design

2023-01-06 00:15 UTC, lwasser commented
https://github.com/all-contributors
please add @arianesasso for documentation, design.
please add @SimonMolinsky for documentation, design.

2023-01-06 00:17 UTC, lwasser commented
https://github.com/all-contributors
please add @lwasser for documentation, design.

2023-01-06 00:17 UTC, lwasser commented
@all-contributors
please add @arianesasso for documentation, design.

2023-01-06 00:19 UTC, lwasser commented
@all-contributors
please add @Batalex  for documentation, design.
please add @SimonMolinsky  for documentation, design.

2023-01-06 00:22 UTC, lwasser commented
@all-contributors
please add @SimonMolinsky for documentation, design.

2023-01-19 16:56 UTC, lwasser commented
closing this PR as all comments from #19 have been addressed and it's merged!

2023-01-19 16:56 UTC, closed without merging