[Review round 2] Enh: Add tests pages - run tests in ci and locally to guide
pyOpenSci/python-package-guide pull request #145
Opened 2024-01-03 22:37 UTC by lwasser

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +environment managers such as `conda` and `pip`.
`pip` is really not an environment manager. Did you mean `virtualenv`? Or were you calling out testing different package indexes?

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +Note that for the code below to work, you need to have all 3 versions of Python installed on your computer for `venv` to find.
```suggestion
Note that for the code below to work, you need to have all 4 versions of Python installed on your computer for `nox` to find.
```

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +can understand](../package-structure-code/declare-dependencies.md). And example of that setup is below.
```suggestion
can understand](../package-structure-code/declare-dependencies.md). An example of that setup is below.
```

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +[project]
Maybe `project.name` `project.version` and `build-system` should also be put in this example, so it is fully self-contained.

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +
It might be worth having an admonition clarifying
> Although nox is a python package and must be installed in a Python environment, it does not have to be installed in all (or any) of the Pythons used for testing. Nox is capable of managing these Python environments externally.

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +your tests on 3 different Python environments (Python 3.9, 3.10, 3.11, and 3.12).
```suggestion
your tests on 4 different Python environments (Python 3.9, 3.10, 3.11, and 3.12).
```

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +To run the above you'd use the command where `-s` stands for
you could also just use the long option `--session`

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +session. Your function above is called test there for
```suggestion
session. Your function above is called test, therefore
```

2024-01-04 18:33 UTC, ucodery commented on tests/run-tests.md
> +An example of using nox to run tests in `venv` environments for Python versions 3.9, 3.10 and 3.11 is below.
```suggestion
An example of using nox to run tests in `venv` environments for Python versions 3.9, 3.10, 3.11 and 3.12 is below.
```

2024-01-04 18:33 UTC, ucodery commented on tests/tests-ci.md
> +
The file name should probably be specified, with links to github docs, as git hub will magically pick up this action or not depending on where in the repository it lives.

2024-01-04 18:33 UTC, ucodery commented on tests/tests-ci.md
> +          python -m pip install nox
With a cache, this install should probably also be an --upgrade

2024-01-08 12:27 UTC, Midnighter reviewed
Added some smaller comments.

Was there a larger discussion on discourse around promoting nox? I didn't see anything on Slack. It's, of course, a fine choice and I'm very late to the party, but I'm personally against nox for the simple reason that I need to write Python code that I may introduce bugs in rather than simply configuring the tool as I would for tox, for example.

2024-01-08 12:27 UTC, Midnighter commented on tests/run-tests.md
> +`pytest filename.py`
For slightly more realism, I would call it `test_module.py`, as that is the default prefix that pytest recognizes.

```suggestion
Or if you want to run a specific test file - let's call this file "test_module.py" - you can run:

`pytest test_module.py`
```

2024-01-08 12:27 UTC, Midnighter commented on tests/run-tests.md
> +session.run("pytest")
I believe indentation is necessary here, otherwise you get a syntax error.

```suggestion
    # install
    session.install(".[tests]")

    # Run tests
    session.run("pytest")
```

2024-01-08 12:27 UTC, Midnighter commented on tests/tests-ci.md
> +          # fetch more than the last single commit to help scm generate proper version
It is never mentioned what `scm` is.

2024-01-08 12:27 UTC, Midnighter commented on tests/tests-ci.md
> +          # fetch more than the last single commit to help scm generate proper version
Also 20 seems like a magic number to me. I personally never had an issue as long as the depth is >1.

2024-01-08 12:27 UTC, Midnighter commented on tests/tests-ci.md
> +          cache: pip # By adding cache here, you are telling actions to reuse installed dependencies rather than re-downloading and installing them each time. This speeds up your workflow
I'm somewhat doubtful about caching. All files that you cache still have to be transferred from GH's storage to the worker machine. That is faster than fetching from a random internet source, but still is a network request. Secondly, I actually like to not cache because then I get the latest versions installed with every run. That way I can discover new versions of dependencies that somehow break my package faster.

2024-01-08 12:27 UTC, Midnighter commented on tests/tests-ci.md
> +        uses: codecov/codecov-action@v3
I disagree, if my code contains platform- or Python version-specific logical branches, I exactly want to upload coverage multiple times so that all branches are covered.

2024-01-08 22:24 UTC, lwasser commented on tests/run-tests.md
> +2. **Automation tools** allow you to automate running workflows such as tests in specific ways using user-defined commands. For instance it's useful to be able to run tests across different Python ve
really good point! i do see nox as an automation tool that happens to be AWESOME at running tests too. and we will show using it to build docs and such too so... let's call it an automation tool for all things packaging. does that land well with you?

2024-01-08 23:23 UTC, lwasser commented on tests/run-tests.md
> +Note that for the code below to work, you need to have all 3 versions of Python installed on your computer for `venv` to find.
i always conflate nox and venv because it's so seamless but this is a way more accurate fix that you've implemented here given nox is using venv not actually creating the envt!

2024-01-09 00:46 UTC, lwasser commented on tests/run-tests.md
> +session.run("pytest")
oh indentation is definitely needed! great catch!

2024-01-09 00:54 UTC, lwasser commented on tests/run-tests.md
> +
good call. i've adjusted the text just a bit 

```
:::{note} Nox Installations 
When you use nox to run tests across different Python versions, nox will create and manage individual `venv` environments for each Python version that you specify in the nox function. It will setup everything that you need to run tests in each environment for you. 
:::
```

2024-01-09 00:58 UTC, lwasser commented on tests/run-tests.md
> +environment managers such as `conda` and `pip`.
i hear you. Maybe package manager. i'm not sure what words are correct here. 

there are PyPI installs and conda installs. But conda is an environment manager and a package manager i think whereas pip is a package manager / build tool. 🤯 

i think what i'm trying to get at here is that you can run nox in conda envts for conda packages and pypi / pip / venv ...add all of the other envt tools that are on the pypi / non conda side of things here... 

what words would you use for that? maybe 

> testing across various
packaging ecosystems such as `conda` and `pip`.

2024-01-09 00:59 UTC, lwasser commented on tests/run-tests.md
> +environment managers such as `conda` and `pip`.
or

> Nox can also be used for other development tasks such as building
> documentation, creating your package distribution, and testing installations 
> across both PyPI related environments (e.g. venv, virtualenv) and `conda` (e.g. `conda-forge`).

2024-01-09 01:02 UTC, lwasser commented on tests/run-tests.md
> +[project]
fixed!!

2024-01-09 01:06 UTC, lwasser commented on tests/run-tests.md
> +To run the above you'd use the command where `-s` stands for
fixed!

2024-01-09 01:26 UTC, lwasser commented on tests/tests-ci.md
> +          # fetch more than the last single commit to help scm generate proper version
it is totally random and magic and will vary based upon people's commit and release cadence.

but here is what i'm thinking about now based on your comments here and below. 

this action is REALLY COMPLEX with the cache and fetch depth pieces. AND we will cover fetch depth when we cover SCM based release / versioning - not here. so what if we remove both caching (and add it as an admonition perhaps??) And the SCM fetch depth stuff so we can focus ONLY on running tests here. that is what my gut is telling me would be most beginner friendly. so i'll go ahead and do it and we can always add. the other stuff back OR have an example in our package repo with the more complex example of the action that supports scm (and maybe caching??)

2024-01-09 01:29 UTC, lwasser commented on tests/tests-ci.md
> +          cache: pip # By adding cache here, you are telling actions to reuse installed dependencies rather than re-downloading and installing them each time. This speeds up your workflow
ok - from my perspective the issue of caching on this page is beyond the scope of this page. so i wrote this above - i'm leaning towards removing it altogether just to keep the example simple. we could have another page on more complex test builds too! 

@namurphy does that seem reasonable to you for this page? to just start simpler because most of our users will be on the newer end of packaging? 

we could then have a page devoted to more efficient CI workflows or add sections to these pages with those more complex concepts covered. The code in this action is a bit tricky to follow and explain. And i don't know enough in terms of how much efficiency it does or does not provide. i'll post in slack as well in case folks want to discuss.

2024-01-09 02:00 UTC, lwasser commented on tests/tests-ci.md
> +          python -m pip install nox
ok that makes a lot of sense. @ucodery i asked this question in slack since it came up in the review as well. the caching part of this workflow is really complex. i think for a beginner it will be overwhelming. i'm curious what people think about how much efficiency caching really adds especially for someone new to packaging. what are your thoughts on that?

even if it adds considerable benefit it feels like cognitive overload to me in a beginner friendly tutorial but might be good in a more advanced tutorial (ie series part 2?)

2024-01-09 02:10 UTC, lwasser commented on tests/tests-ci.md
> +        uses: codecov/codecov-action@v3
i hear you! this guide is really focused on pure python builds and this tutorial needs to be beginner friendly! I think those newer to packaging likely need a simple point of entry BUT it's important to point out more complexity could be on the horizon! so i just edited the comment to say You only need to upload once unless you have a more complex build.

2024-01-09 08:35 UTC, Midnighter commented
Very fair points on nox, and I agree it is a great tool 🙂. I guess, I'm just scared of the power it provides by allowing you to write Python code 😆.

2024-01-10 00:06 UTC, lwasser commented on tests/run-tests.md
> +2. **Automation tools** allow you to automate running workflows such as tests in specific ways using user-defined commands. For instance it's useful to be able to run tests across different Python ve
Ok here is what i did! that diagram was messy so i turned it into a table that we can easily update. i moved nox into a separate automation tool column and we can go back and forth on the final version to ensure we're happy with it once i have pushed all of the new edits from this review up! i'll mark this as resolved for now and we can revisit if need be when looking at hte final version of the edited pages.

2024-01-10 00:06 UTC, lwasser commented on tests/run-tests.md
> +run tests. Test runners automate processes such as creating isolated environments to run your tests in, and running tests across Python versions with a single command. Finally Continuous integrate (C
agreed. it's been removed since i now have a table here!

2024-01-10 00:10 UTC, lwasser commented on tests/tests-ci.md
> +          python -m pip install nox
ok we have collectively decided to remove the caching part in this ppage just to keep things simple.

i [opened an issue to capture this here](https://github.com/pyOpenSci/python-package-guide/issues/161) and we can revisit it once the core pieces of the guidebook are all pulled together.

2024-01-10 21:15 UTC, willingc approved these changes
Looks good!

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +1. A **test framework**, is a package that provides a particular syntax and set of tools for _both writing and running your tests_. Some test frameworks also have plugins that add additional features
```suggestion
1. A **test framework**, is a package that provides a particular syntax and set of tools for _both writing and running your tests_. Some test frameworks also have plugins that add additional features such as evaluating how much of your code the tests cover. Below you will learn about the **pytest** framework which is one of the most commonly used Python testing frameworks in the scientific ecosystem. Testing frameworks are essential but they only serve to run your tests. These frameworks don't provide a way to easily run tests across Python versions without the aid of additional automation tools.
```

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +TODO: add note about running tests in vscode, breakpoints and –no-cov flag. Then link to tutorial that explains how to deal with this.
```suggestion
Your editor or IDE may add additional convenience for running tests, setting breakpoints, and toggling the `–no-cov` flag. Check your editor's documentation for more information.
```

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +TODO: add note about running tests in vscode, breakpoints and –no-cov flag. Then link to tutorial that explains how to deal with this.
Instead of leaving as a todo, let's give some guidance. We can always expand later.

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +Or if you want to run a specific test file - let's call this file "test_module.py" - you can run:
```suggestion
Or if you want to run a specific test file - let's call this file "`test_module.py`" - you can run:
```

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +Learn more from the [get started docs here](https://docs.pytest.org/en/7.1.x/getting-started.html).
```suggestion
Learn more from the [get started docs](https://docs.pytest.org/en/7.1.x/getting-started.html).
```

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +This is a great start to making your Python package more robust! However, your users may be using your package on different
Perhaps remove this paragraph completely. It seems repetitive and may add reader confusion. The next paragraph sums it up nicely.

2024-01-10 21:15 UTC, willingc commented on tests/run-tests.md
> +Both `nox` and `tox` can create an isolated virtual environment that you define. This allows you to easily run your tests in multiple environments and across Python versions.
```suggestion
Both `nox` and `tox` can create an isolated virtual environments. This allows you to easily run your tests in multiple environments and across Python versions.
```

2024-01-10 21:15 UTC, willingc commented on tests/tests-ci.md
> +Running your [test suite locally](run-tests) is useful as you develop code and also test new features or changes to the code base. However, you also will want to setup Continuous Integration (CI) to
```suggestion
Running your [test suite locally](run-tests) is useful as you develop code and also test new features or changes to the code base. However, you also will want to setup Continuous Integration (CI) to run your tests online. CI allows you to run all of your tests in the cloud. While you may only be able to run tests locally on a specific operating system, using CI you can specify tests to run both on various versions of Python and across different operating systems.
```

2024-01-10 21:17 UTC, willingc commented on conf.py
> +ogp_site_url = "http://www.pyopensci.org/python-package-guide/"
@lwasser Maybe use https

2024-01-11 16:09 UTC, lwasser commented on conf.py
> +ogp_site_url = "http://www.pyopensci.org/python-package-guide/"
```suggestion
ogp_site_url = "https://www.pyopensci.org/python-package-guide/"
```

2024-01-11 18:15 UTC, willingc approved these changes

2024-01-11 18:15 UTC, ucodery commented on tests/run-tests.md
> +environment managers such as `conda` and `pip`.
Hmm, I like that second edit a lot. It's still conflating PyPI with the environment manager, but that might be okay here. Also, you don't have the tools ordered the same way - it should be "virtualenv (PyPI) and conda (conda-forge)" (or the other way around).

Maybe we can take the best of both your edits
> Nox can also be used for other development tasks such as building
documentation, creating your package distribution, and testing installations
across different package ecosystems, such as PyPI (using venv) and conda-forge (using conda).

(I dropped `virtualenv` because there is no other mention of it in this guide; it could just confuse new readers. Though it might be good somewhere to have a cheat sheet for `venv`, `virtualenv`, `pipenv`, `pipx`, etc. It's a very common confusion for new Pythonistas)

2024-01-11 19:11 UTC, ucodery commented on tests/run-tests.md
> +the mamba-forge installation.
I couldn't find any mention of this in the nox project. It seems to only require `conda` or `mamba` be pre-installed. But I haven't used it as the env manager before - is this advice coming from elsewhere?

2024-01-11 19:11 UTC, ucodery commented on tests/run-tests.md
> +nox -s test_mamba
```suggestion
nox --session test_mamba
```

2024-01-11 19:11 UTC, ucodery commented on tests/tests-ci.md
> +efficient so your dependencies aren't downloaded multiple times.
```suggestion
3.9-3.11.
```

2024-01-12 00:43 UTC, willingc commented on tests/tests-ci.md
> +[Learn more about Continuous Integration and how it can be used, here.](ci)
Let's fix the link or remove the note since this is causing HTMLProofer to be grumpy.

2024-01-12 15:08 UTC, lwasser commented on tests/run-tests.md
> +TODO: add note about running tests in vscode, breakpoints and –no-cov flag. Then link to tutorial that explains how to deal with this.
good idea. i ran into this with setting up vscode to troubleshoot bugs in our tests and wanted to atlest acknowledge it!

2024-01-12 15:19 UTC, lwasser commented on tests/run-tests.md
> +the mamba-forge installation.
@ucodery that may be coming from me and it also may be wrong. i always have a conda version of python installed so i may be confused! 

For nox to work across python versions i had to download and install python 3.x, 3.x+1 etc from python.org. so i think i made the jump that for conda to work you'd need to have a conda installation of Python. But you are saying that if you have the packages installed (`conda` or `mamba`) with a python.org installation of python that conda will be able to produce a new environment accordingly?

2024-01-12 15:28 UTC, lwasser commented on tests/run-tests.md
> +There are three types of tools that will make is easier to setup and run your tests in various environments:
fixed! i went with categories :)

2024-01-12 15:32 UTC, lwasser commented on tests/run-tests.md
> +This is a great start to making your Python package more robust! However, your users may be using your package on different
ok i've cleaned this up. i added a small admonition about the next page covering running tests across operating systems!

2024-01-12 15:34 UTC, lwasser commented on tests/run-tests.md
> +:::{note} Nox Installations
good point. i'm not sure if a beginner would get confused with that additional information or whether it would be useful. i hadn't thought about that before because nox just always worked! if you have suggestions for how to word it in a way that it doesn't make  the user more confused i'm open to that!

2024-01-12 15:35 UTC, lwasser commented on tests/run-tests.md
> +    session.install(".[tests]")
fixed! i missed the conda_install method in the docs!

2024-01-12 15:37 UTC, lwasser commented on tests/tests-ci.md
> +[Learn more about Continuous Integration and how it can be used, here.](ci)
ok! what i've been doing to avoid having to figure out where to relink everything is adding the links in admonition todo's. that will make adding the links back into the guidebook throughout much easier for me as i can do a search for them and fix them! :)

2024-01-15 14:00 UTC, Batalex requested changes

2024-01-16 17:22 UTC, lwasser commented on tests/run-tests.md
> +```python
Gosh very good catch! that was totally missing. i just added it in a few places!

2024-01-16 17:24 UTC, lwasser commented on tests/run-tests.md
> +the mamba-forge installation.
ok i have fixed this. i removed the conda installation and just said - you need to have conda or mamba installed on your computer. it's really funny how we create mental models of how things work that aren't necessarily based on how they actually do work. but that model works for us until someone asks the right question! :)

2024-01-16 17:30 UTC, lwasser commented
ok everyone! i've fixed / responded to all suggested changes and this is now ready to merge!! it should be live in the next 5-10 minutes! 🚀

2024-01-16 17:31 UTC, lwasser commented
i'm also confused as to why htmlproofer is passing given we have new pages here but we shall see!

2024-01-16 17:31 UTC, merged