Mention copyleft in license guide!
pyOpenSci/python-package-guide pull request #189
Opened 2024-03-02 00:59 UTC by sneakers-the-rat

Currently the license guide only mentions permissive licenses without discussing what the alternative might be. I think this is a relatively balanced discussion that provides some links to further readings and also grounds the discussion in some history. Software is political! and we should at least mention copyleft, even if we have elected to recommend permissive licenses - I think we should do so in a way that anyone who reads our guides can make an informed choice.

- L73, L79 - Softened language about "core" and "our" to not suggest that "everyone uses permissive licenses" or "pyopensci reviewed packages should be permissively licensed"
- L79 - Rephrased based on goal of author and compatibility
- Added discussion on compatibility with table
- Added references using `sphinxcontrib-bibtex`

2024-03-02 02:31 UTC, InessaPawson commented on documentation/repository-files/license-files.md
> +Copyleft licenses are "sticky," in that they are designed to ensure that more free software is created.
```suggestion
Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created.
```
@sneakers-the-rat Please disregard my suggestion if it's not a typo.

2024-03-02 02:34 UTC, InessaPawson commented on documentation/repository-files/license-files.md
> +The difference between copyleft vs. permissive licenses is an important cultural divide in free and open source software (eg. see {footcite}`hunterReclaimingComputingCommons2016`, {footcite}`gnuproje
```suggestion
The difference between copyleft vs. permissive licenses is an important cultural divide in free and open source software (e.g., see {footcite}`hunterReclaimingComputingCommons2016`, {footcite}`gnuprojectWhatFreeSoftware2019`, {footcite}`gnuprojectWhatCopyleft2022`),
```

2024-03-02 04:03 UTC, InessaPawson reviewed
@sneakers-the-rat Important points and excellent explanation of a rather complex topic! I made a few minor suggestions to clarify some parts of the text. Feel free to disregard those that you don't find helpful.

2024-03-02 06:36 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
>  This means that technically, if you copy code from the Stack Overflow website, and use it in your package. And your packages uses a different license such as a MIT license, you are violating Stack Ov
thanks for these suggestions, merging now<3

2024-03-04 21:19 UTC, ctb commented
Looks good to me on a quick skim! Nice work!

Do we want to mention things like the Affero GPL as a further copyleft license, that prevent companies from taking your software and running it as a service w/o releasing the source? https://www.gnu.org/licenses/why-affero-gpl.en.html

2024-03-04 21:47 UTC, sneakers-the-rat commented
> Do we want to mention things like the Affero GPL as a further copyleft license, that prevent companies from taking your software and running it as a service w/o releasing the source? https://www.gnu.org/licenses/why-affero-gpl.en.html

I think it would be worth expanding this out into a separate "reference" style page that addresses the history and purposes for different licenses, that's something that I don't know of a concise reference for really. I think in this page it might be a little bit too much detail - i feel like "there are permissive and copyleft licenses" and the top-level differences between them, but yes, the cool thing about our guides being websites is we can make infinitely many extra pages <3

2024-03-20 15:46 UTC, lwasser commented
ok!! i'll put this on my list to review this week! thanks @willingc for pinging me!

2024-03-20 21:14 UTC, lwasser commented
@all-contributors please add @ctb for code, review

2024-03-21 16:42 UTC, lwasser commented
@sneakers-the-rat i suspect the conflicts here relate to the pr's i merged yesterday where you fixed our requirements and such. can you kindly rebase when you have a chance? in the meantime i'll review today/tomorrow!

2024-03-21 16:46 UTC, lwasser commented on documentation/repository-files/license-files.md
> +The other major category of licenses are ["copyleft" licenses](https://en.wikipedia.org/wiki/Copyleft).
```suggestion
:::{admonition} Copyleft vs Permissive Licenses
While we suggest that you use a permissive license for your Python package, you may also see packages that use ["copyleft" licenses](https://en.wikipedia.org/wiki/Copyleft). 
```

2024-03-21 16:48 UTC, lwasser commented on documentation/repository-files/license-files.md
> +These are licenses that require that anyone that uses your work redistributes it with the same (or greater) rights to modify, copy, share, and redistribute it.
```suggestion
Copy left licenses requires people that use your work to redistribute it with the same (or greater) rights to modify, copy, share, and redistribute it.
```

2024-03-21 16:49 UTC, lwasser commented on documentation/repository-files/license-files.md
> +Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created.
```suggestion
Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created. If your work has a copyleft license, it prohibits someone taking it, making a proprietary version of it, and redistributing it without providing the source code for others to use and share.

```

2024-03-21 16:50 UTC, lwasser commented on documentation/repository-files/license-files.md
> +Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created.
i'm not sure if this is quite right but just trying to simplify the words a bit :)

2024-03-21 16:51 UTC, lwasser commented on documentation/repository-files/license-files.md
> +that you should be aware of when choosing your license - the lineage of copyleft represents the "free" part of "free and open source software".
```suggestion
The difference between copyleft and permissive licenses is an important cultural divide in free and open source software (e.g., see {footcite}`hunterReclaimingComputingCommons2016`, {footcite}`gnuprojectWhatFreeSoftware2019`, {footcite}`gnuprojectWhatCopyleft2022`).
It is important to understand this difference when choosing your license. Copyleft licenses represents the "free" part of "free and open source software".
```

2024-03-21 16:55 UTC, lwasser commented on documentation/repository-files/license-files.md
> +Free and open source software is intrinsically political, and it is important to be aware of power dynamics in computing as well as the practical problems of license compatibility (discussed below).
This is al great @sneakers-the-rat , thank you!! I have a few thoughts and questions here. 

1. i think for someone who is new to software and OSS the political part will seem "out of no where" and potentially scary even tho it is truth. i wonder if there is a way to make this statement a bit more clear to someone that is new. i feel like there is a leap here from - let's add a license to your package to - there are power dynamics at play and licenses can be play a role in these dynamics. i'm not sure what language we should use but i just wonder if we can make this more clear to someone who is newer to the space. It's especially confusing as projects like numpy ahd choosealicense.org suggest that we use MIT. so i'd be asking - well it seems like everyone should use GNU then. Why are we using MIT? why are we suggesting MIT.
do you see where i'm going here? can we adjust to consider those types of questions and thoughts / concerns? (honestly i'm thinking the same right now as we decided on MIT as a community but copyleft does sound compelling the way it's described here.

2024-03-21 16:56 UTC, lwasser commented on documentation/repository-files/license-files.md
> +If your primary goal is for your code to be used by other, major packages in the scientific ecosystem, we also recommend
see this conflicts with the breakout above. and i totally understand why we want that breakout above.  but a new user will be confused by this after reading about copyleft! so how can we create a text bridge between the two?

2024-03-21 17:05 UTC, lwasser commented on documentation/repository-files/license-files.md
> +A useful way to think about license compatibility is the distinction between **"inbound"** and **"outbound"** compatibility.
i feel like some of this would be useful above. what is we thought about re-organizing this page jonny? 

at the top we have 

## Where to store your license

### Use open permissive licenses when possible

what is instead we do something like this

```
## Where to store your license
keep text as is 

##Types of licenses: permissive vs copyleft 

explain inbound vs outbound restrictions here to frame the text below

### Overview of permissive licenses

### Overview of copyleft licenses (make your breakout into this section)

 ## How to chose a license 

* we suggest mit or bsd-3 for compatibilty with the scientific Python ecosystem
* scipy text as a reference 

## Following license guidelines

more about how to follow and how that impacts permissive vs copyleft (which by now it's clear how these are different). and yo've already explain inbound vs outbound permisions above so you can just have a little table even and demonstrate how the licenses are different.

2024-03-21 17:06 UTC, lwasser commented on documentation/repository-files/license-files.md
> +|                                                      Compatible | Dependency <br> ("Inbound") | Your Package | Downstream Package <br> ("Outbound") |
OMG you have a table - yes! i was thinking a table would be great. [myst tables](https://myst-parser.readthedocs.io/en/latest/syntax/tables.html) are pretty create btw. simpler syntax / easier to read :)

2024-03-21 17:07 UTC, lwasser commented on documentation/repository-files/license-files.md
> +This would not be true with a GPL licensed package - `GPL-3` packages can include code licensed by `CC-BY-SA` {footcite}`creativecommonsShareAlikeCompatibilityGPLv32015`.
```suggestion
This would not be true with a GPL licensed package. `GPL-3` packages can include code licensed by `CC-BY-SA` {footcite}`creativecommonsShareAlikeCompatibilityGPLv32015`.
```

2024-03-21 17:09 UTC, lwasser requested changes
@sneakers-the-rat this is awesome. I feel like we just need to reorganize a bit now that we have new important concepts introduced!! i love it all, let's just clarify so we don't scare off new users. So i'm suggesting a reorg that allows us to introduce concepts higher up on the back such as 

permissive vs copy left and 
inbound vs outbound permissions. 

then it will be easier to digest i think lower down and flow better.

are we swapping rolls for this pr 😆?! i love it!

2024-03-22 02:13 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +The other major category of licenses are ["copyleft" licenses](https://en.wikipedia.org/wiki/Copyleft).
The previous line is "We generally suggest that you use a permissive license" so i think that it's reasonably clear copyleft is being presented as an alternative? i would worry that the language 'you may also see copyleft' is like 'you shouldn't use it but should be aware of it' rather than 'the other option you have is copyleft' - esp for new programmers i think it's fine to make a recommendation (that's the purpose of the guide!) but i wouldn't want it to come across as like 'don't use copyleft'. does that make sense? delicate balance i think

2024-03-22 02:14 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +These are licenses that require that anyone that uses your work redistributes it with the same (or greater) rights to modify, copy, share, and redistribute it.
i like this, revise to "Copyleft licenses require" and i'll commit?

2024-03-22 02:19 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created.
Hmm ya you're right there needs to be a little more glue between these ideas bc it's not quite clear how they encourage more free software from this alone. I think the order of explaining what they are -> what 'stickiness' means makes sense, but maybe like "This requirement makes copyright licenses "sticky" - they are designed to encourage more free, copyleft licensed software to be created."

2024-03-22 02:24 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +If your primary goal is for your code to be used by other, major packages in the scientific ecosystem, we also recommend
how do you mean? like we should have a parallel "otherwise, if your goal is..." for copyleft? I read it as previous section recommending permissive licenses, and then this section further explaining why that would be the case - there are lots of major packages that use permissive, and if you use copyleft then your work can't be used in them. can you tell me more about what's reading as discordant?

2024-03-22 02:28 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +|                                                      Compatible | Dependency <br> ("Inbound") | Your Package | Downstream Package <br> ("Outbound") |
you mean the list table directive? i can swap it to that if you'd prefer :)

2024-03-22 02:31 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +A useful way to think about license compatibility is the distinction between **"inbound"** and **"outbound"** compatibility.
I think this should probably come after we give definitions of what the categories of licenses are, but i'm definitely game to making a separate section for each type, that is def clearer and might help above comment re: ordering. 

I see this thought as being part of all three 'what are the types of licenses,' 'why might i choose one vs another,' and 'how do i follow license guidelines' so idk! I think it's nicely paired with the example of stack overflow. so i could see this part going one of a few places...

```
- Where to store license
- Types of licenses
  - permissive
  - copyleft
  - comparison <--- maybe here???
- choosing a license
  - suggestion
  - scipy thing
  - considerations to weigh <--- maybe here???
- following license guidelines
  - when you can and can't use software given your license <--- maybe here???
  - stack overflow example
```

i don't rly have a strong preference, but i think you're right maybe sooner is good :)

2024-03-22 02:41 UTC, sneakers-the-rat commented on documentation/repository-files/license-files.md
> +Free and open source software is intrinsically political, and it is important to be aware of power dynamics in computing as well as the practical problems of license compatibility (discussed below).
Maybe we can say something like "This set of tutorials is primarily intended to teach you to program, but an important part of learning to be a programming is learning about the history and culture of open source software. Licensing is a decision about who can do what with your code, which is intrinsically political ... {rest of text} ... there are legitimate differences in goals and context for open source software, and each category of licenses has their uses, supporters, and detractors"

2024-03-22 02:43 UTC, sneakers-the-rat commented
> So i'm suggesting a reorg that allows us to introduce concepts higher up on the back such as

agreed :) replied above thinking about places to move that section!

> are we swapping rolls for this pr 😆?! i love it!

may all hierarchies be forever fluid <3

2024-04-03 15:44 UTC, lwasser commented on documentation/repository-files/license-files.md
> +The other major category of licenses are ["copyleft" licenses](https://en.wikipedia.org/wiki/Copyleft).
it makes sense @sneakers-the-rat let's leave as is for now. so sorry it's taken me 2 weeks to get back to this.

2024-04-03 15:44 UTC, lwasser commented on documentation/repository-files/license-files.md
> +These are licenses that require that anyone that uses your work redistributes it with the same (or greater) rights to modify, copy, share, and redistribute it.
Fixed!

2024-04-03 15:47 UTC, lwasser commented on documentation/repository-files/license-files.md
> +Copyleft licenses are "sticky" in that they are designed to ensure that more free software is created.
i think i follow!! i updated the revision.

2024-04-03 15:49 UTC, lwasser commented on documentation/repository-files/license-files.md
> +Free and open source software is intrinsically political, and it is important to be aware of power dynamics in computing as well as the practical problems of license compatibility (discussed below).
i think that makes a lot of sense to frame it . do you want to make that change to the file? This is also making me think that we should either have a blog post on this topic (probably preferred) OR add a page to the guide about the culture of open source software. Or both. that way we can link to that content rather than adding too much to individual pages. how about that?  i can open this as a new issue in this repo and we can decide whether it should be a blog or a  page in the guide. and maybe we can get the community to help write it if someone starts it. 

i'll open the issue now and we can discuss separately

2024-04-03 16:01 UTC, lwasser commented on documentation/repository-files/license-files.md
> +A useful way to think about license compatibility is the distinction between **"inbound"** and **"outbound"** compatibility.
i think what you have above is fine. i just think all of the overview should be in one section and then choosing should be it's own section with limited additional info but definitely a considerations section

2024-04-03 16:05 UTC, lwasser commented
here is the [current rendered page](https://output.circle-artifacts.com/output/job/8e6e6112-7d16-476e-8f26-55095fd1ccea/artifacts/0/html/documentation/repository-files/license-files.html) i think a clean reorganiation is the key piece as right now a new user is going to be really confused. but i also think we have a lot of great information in this pr!!

2024-04-08 17:08 UTC, lwasser commented
ok let's see - what do we need to do to get this PR merged? I think 

1. a small re-org to make it easier for the reader to follow [see here](https://github.com/pyOpenSci/python-package-guide/pull/189#discussion_r1534962518)
2. and then [this comment](https://github.com/pyOpenSci/python-package-guide/pull/189#discussion_r1550033094) around ensuring we don't confuse readers trying to navigate the scientific vs broader ecosystem when selecting licenses.

2024-10-07 17:58 UTC, willingc approved these changes
To reboot this PR, I recommend we merge this as is. I opened #415 and #416 to cover additional tasks.

2024-10-07 17:58 UTC, willingc commented on documentation/repository-files/license-files.md
> +The other major category of licenses are ["copyleft" licenses](https://en.wikipedia.org/wiki/Copyleft).
Marking this as resolved.

2024-10-07 17:58 UTC, willingc commented on documentation/repository-files/license-files.md
> +A useful way to think about license compatibility is the distinction between **"inbound"** and **"outbound"** compatibility.
Opened issue #415.

2024-10-07 17:58 UTC, willingc commented on documentation/repository-files/license-files.md
> +|                                                      Compatible | Dependency <br> ("Inbound") | Your Package | Downstream Package <br> ("Outbound") |
Opened #416 as a task for post-merge.

2024-10-07 18:05 UTC, sneakers-the-rat commented
Good with that if others are :)

2024-10-07 19:05 UTC, lwasser approved these changes
awesome @willingc thank you!! i've wanted to get back to this one. let's merge. thank you @sneakers-the-rat we can always sprint on the other issues at a later date. in fact maybe that's what we need to do periodically is organizing packaging guide sprints to look for updates and to merge open prs. thank you both.

2024-10-07 19:06 UTC, merged