Review 2 (reviews open): Add: documentation section to package guide
pyOpenSci/python-package-guide pull request #19
Opened 2022-12-29 18:22 UTC by lwasser

This pr builds on top of https://github.com/pyOpenSci/python-package-guide/pull/14 which will be closed. It contains a lot of new and re-organized information based upon feedback.

2023-01-02 16:06 UTC, tupui reviewed
Great write up! I have a few suggestions if I may 😃

2023-01-02 16:06 UTC, tupui commented on documentation/readme-file-best-practices.md
> +- [ ] Badges for the packages current published version, documentation and test suite build. (OPTIONAL: test coverage)
Personal take, I don't like badges about CI because it does not represent what users would get. Most users would get a stable release, hence this has little value. I even think that it can send a wrong message to some people if they see a red badge for some time. Depending on the CI jobs, that does not necessarily mean the project is broken all the time.

2023-01-02 16:06 UTC, tupui commented on documentation/readme-file-best-practices.md
> +* DOI (for citation) Example: [![DOI](https://zenodo.org/badge/556814582.svg)](https://zenodo.org/badge/latestdoi/556814582)
Also now on GitHub you can add a citation file with their format.

2023-01-02 16:06 UTC, tupui commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
I would not talk about Google Analytics as they are not GDPR compliant. Instead Plausible is better (also the solution we choose for Scientific Python, we use a self hosted instance.)

2023-01-02 16:27 UTC, NickleDave commented on documentation/readme-file-best-practices.md
> +* DOI (for citation) Example: [![DOI](https://zenodo.org/badge/556814582.svg)](https://zenodo.org/badge/latestdoi/556814582)
:+1: we should definitely mention citation.cff here!  
https://citation-file-format.github.io/

The GitHub integration is really nice because you can click on the right hand side of the repo landing page to copy a ctiation in APA/BibTex/whatever to the clipboard

minor point: it was developed by research software engineers at Netherlands eScience institute, Software Sustainability Institute and elsewhere. But there is for sure integration with GitHub, Zenodo, and Zotero!

2023-01-04 22:48 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +# Python Package Documentation
NOTE: could be worth revisiting this and adding nbgallery as a front end with nbsphinx - will provide a much nicer front end for peope to use https://nbsphinx.readthedocs.io/en/0.8.11/subdir/gallery.html thanks to @astrojuanlu for the tip!

2023-01-07 20:02 UTC, NickleDave requested changes
Huge step forward for our docs docs :slightly_smiling_face:   

This review was spread out over three days, I promise I did try to remove any of the extra grumpiness from late-night reviewing. Hope that it's helpful

2023-01-07 20:02 UTC, NickleDave requested changes
Huge step forward for our docs docs :slightly_smiling_face:   

This review was spread out over three days, I promise I did try to remove any of the extra grumpiness from late-night reviewing. Hope that it's helpful

2023-01-09 17:39 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
oh wow. wait i had no idea about SO licensing. i just googled and found this 

https://stackoverflow.com/help/licensing CC share alike licensing. Those are both incompatible with BSD and MIT? 

So would you like to see some language here around those specific points. 

something like: 
`If you borrow code from other tools / locations make sure that code's license complies with the OSI-approved license that you select.`

Are there other notes you'd like to see here around that topic / point? many thanks @tupui

2023-01-09 17:56 UTC, tupui commented
Thanks 😊

2023-01-09 18:02 UTC, sneakers-the-rat commented on documentation/index.md
> +## Quick Takeaways: Documentation must haves
I feel like the box, while cool, is a lil redundant with the body of the page. Overview of an overview and when i read the whole page i'm like wait i just read this. 

If it stays i think it would b nice to have it in the same order as the main list in the page (and maybe also having the tutorials bit)

2023-01-09 18:07 UTC, lwasser commented on documentation/contributing-license-coc.md
> +* Build documentation locally
added:

The development guide should also have guidelines for:
* code standards including docstring style, code format and any specific code approaches that the package follows. 

@tupui does that address your comment sufficiently?

2023-01-09 18:08 UTC, tupui commented on documentation/contributing-license-coc.md
> +* Build documentation locally
Yes 👍 thanks

2023-01-09 18:11 UTC, tupui commented on documentation/index.md
> +1. [**LICENSE.txt file & Citation instructions:**](contributing-license-coc.html#your-repository-should-have-a-license-md-file) A license file declaring the OSI-approved license that you select and i
> and then github implemented those CITATION.cff files, idk how widespread those are, but ya having specific recommendations for how to include citation instructions even if that means just "have a bibtex block in your readme"

Difficult to say. But a lot of "big" libraries have implemented it. This does provide a nice citation UI element. I am not sure but that might be noticeable for screen readers as it's a dedicated element.

But yes, in the end it's a GitHub thing and we never know if this stays or is just a short lived initiative which will add some maintenance down the line.

2023-01-09 18:11 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +* All of its functions and classes (the API) documented
Ahhhh ok perfect. makes perfect sense - fixed. 

but also question for you. As someone who has recently stepped into maintaining a package with a 10 year old code base, i've found it to be difficult when private / _functions_ and methods don't have docstrings. it just makes it harder for me to get to know the code base as a contributor and maintainer. Do you have any thoughts on that?

i don't need examples and such but do appreciate input and output var types being specified and a clear docstring. thoughts?

In the meantime i've changed this to:

```
* All of its public (user-facing) functions and classes (the API) documented
```

2023-01-09 18:13 UTC, lwasser commented on documentation/contributing-license-coc.md
> +* Build documentation locally
perfect! resolving!

2023-01-09 18:19 UTC, tupui commented on documentation/package-documentation-best-practices.md
> +* All of its functions and classes (the API) documented
I do agree here that it's also important to document, but maybe not with the same requirements in terms of quality. In the end you are not targeting the same public (users vs maintainers).

E.g. in my projects I don't necessarily document all private functions if the name is clear and the function small. And when I do, I don't require to have examples and describe all parameters.

For types, I found myself using typing. Here I have 2 modes: i.e. if the CI is using mypy I have no choice and I have to comply and at the moment it's painful to be honest. Or I do "pragmatic" typing. Mypy would certainly complain, but my IDE is happy so types are mostly good. An example would be typing floats. In SciPy we added a helper type which is not just `float` but: `Union[float, np.floating, np.integer]`.

2023-01-09 18:22 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +    """
ok i've looked at scipy and fixed: I'm a bit unclear regarding what text would go after but i totally see how you have text after - if you could clarify that would be wonderful!


```
Parameters
    ----------
    ext_obj: list or geopandas.GeoDataFrame
        If provided with a `geopandas.GeoDataFrame`, the extent
        will be generated from that. Otherwise, extent values
        should be in the order: minx, miny, maxx, maxy.
    Return
    ------
    extent_json: A GeoJSON style dictionary of corner coordinates
    for the extent
        A GeoJSON style dictionary of corner coordinates representing
        the spatial extent of the provided spatial object.
    
    Example
    -------
    Convert a `geopandas.GeoDataFrame` to an extent dictionary:

    >>> import geopandas as gpd
    >>> import earthpy.spatial as es
    >>> from earthpy.io import path_to_example
    >>> rmnp = gpd.read_file(path_to_example('rmnp.shp'))
    >>> es.extent_to_json(rmnp)
    {'type': 'Polygon', 'coordinates': (((-105.4935937, 40.1580827), ...),)}

    """
```

2023-01-09 18:23 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +        If provided with a geopandas.GeoDataFrame, the extent
is this by chance an extension that you use that then links back to the APi docs? intersphinx or something like that?i'm unclear about the single vs double back ticks in terms of what to add here but if i understood the extension or could see what you mean I could probably add some notes about it! it's useful for people to know about sphinx extensions or options that cross reference in the docs. Many thanks,

2023-01-09 18:28 UTC, tupui commented on documentation/package-documentation-best-practices.md
> +    """
Maybe this?

```
    Parameters
    ----------
    ext_obj : list or geopandas.GeoDataFrame
        If provided with a `geopandas.GeoDataFrame`, the extent
        will be generated from that. Otherwise, extent values
        should be in the order: minx, miny, maxx, maxy.
    Return
    ------
    extent_json : A GeoJSON style dictionary of corner coordinates
    for the extent
        A GeoJSON style dictionary of corner coordinates representing
        the spatial extent of the provided spatial object.
    
    Example
    -------
    Convert a `geopandas.GeoDataFrame` to an extent dictionary:

    >>> import geopandas as gpd
    >>> import earthpy.spatial as es
    >>> from earthpy.io import path_to_example

	We start by loading a Shapefile.

    >>> rmnp = gpd.read_file(path_to_example('rmnp.shp'))

	And then use `extent_to_json` to do the conversion from `shp` to
    `geopandas.GeoDataFrame`.

    >>> es.extent_to_json(rmnp)
    {'type': 'Polygon', 'coordinates': (((-105.4935937, 40.1580827), ...),)}

    """
```

2023-01-09 18:35 UTC, tupui commented on documentation/package-documentation-best-practices.md
> +        If provided with a geopandas.GeoDataFrame, the extent
That's a good question. I had a look and yes this is with `sphinx.ext.intersphinx` and it uses a mapping dict in the configuration to look into other packages so you can use objects from these libraries. e.g.

```python
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/devdocs', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
}
```

Speaking about extensions. With numpydoc you also get the ability to have nice reference for the literature.

```
    As seen in [1]_, ...

    References
    ----------
    .. [1] ...
```

And while I am at it, an FYI which could interest you too. In SciPy we have some custom extensions to add a ``` :doi:`10...` ``` or ```:arxiv:`10...` ```

2023-01-09 18:42 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +1. Runs the code in each tutorial: this acts as a check to ensure your package is working as you think it is!
added this:

````
## Using doctest to run docstring examples in your packages methods and functions

If you wish, you can also add the [doctest](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) extension to your Sphinx build. 
Doctest, runs the example code in your docstring `Examples` checking 
that the expected output is in fact correct. Similar to running
tutorials in your documentation, doctest can be a useful step that 
assures that your packages code (API) runs as you expect it to.

Below is an example of a docstring with an example. 
doctest will run the example below and test that if you provide 
`add_me` with the values 1 and 3 it will return 4.  


```python
def add_me(aNum, aNum2):
    """A function that prints a number that it is provided. 
    
    Parameters
    ----------
    aNum : int
        An integer value to be printed
    
    Returns 
    -------
        Prints the integer that you provide the function.
    
    """
   return aNum + aNum2

Examples
--------
Below you can see how the `print_me` function will print a number that 
you provide it.

>>> add_me(1+3)
4

```
````

2023-01-09 18:49 UTC, tupui commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
Sadly yes it's incompatible due to the share alike clause. Here is what we say about licensing in SciPy https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#licensing

That addition is fine I think, or maybe advise people to really do some homework to understand what it means to respect licenses. Licensing is a really tough topic.

In the end it's the responsibility of the maintainer to watch out for this. e.g. in SciPy we are really careful if someone opens a PR and say they had a look at some R or Matlab and we see the code is not compatible, we close directly the PR and warn everyone to not have a look at the PR and mentioned code. Just the act of having a look is a breach of the licensing... I suspect that a lot of OSS packages are breaking licenses all the time...

2023-01-09 18:53 UTC, tupui commented on documentation/python-package-documentation-tools.md
> +1. Runs the code in each tutorial: this acts as a check to ensure your package is working as you think it is!
Nice, I would just add a small note to stress that it should not replace or complement the test suite.

2023-01-09 19:08 UTC, sneakers-the-rat reviewed
I like :) thanks for all your work writing this. Hopefully these are useful, sorry if they are all very persnickety, thus is the nature of feedback. 

My big global comment is that some macro-level reorganization would be nice: as is the order feels a little random and I am not left with a clear picture of what is required by pyOpenSci re: documentation since it's buried around on a few pages. I see that several files were removed and combined here, and so not sure what the deal is there but I suggested a simple 2-layer nested structure in one of my comments that I feel like would be helpful to keep the docs expandable and also be able to navigate around for someone interested in submitting.

thanks again :) all my comments 'optional' to take or leave as they're useful or not.

2023-01-09 19:08 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +## What a CONTRIBUTING.md file should contain
Same thing with each of these headings

`Contributing`
`License`
`Code of Conduct`

2023-01-09 19:08 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +Your Python open source package should include a file called **CONTRIBUTING.md** located in the
An example would be nice!

2023-01-09 19:08 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +## What the development guide for your Python package should contain
Not clear how this is different than the Contributing.md and makes me feel like i'm supposed to write another guide. I would make this a subheading underneath contributing and shorten the header to `Developer Docs` or something

2023-01-09 19:08 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +[handy tool](https://choosealicense.com/) for choosing a license.
Linking to the tool is great. Maybe broad strokes description of the basic "big cuts" differences in licenses and perhaps a recommendation or a statement about which licenses are most common/expected by pyOpenSci

2023-01-09 19:08 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +## The CODE_OF_CONDUCT.md file
a lil more on what the code of conduct should do/what is typically in them would also be nice.

2023-01-09 19:14 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
Wow - ok i just learned something important. i had never considered that share alike point being problematic for open source. i just thought of it as it keeps the code open - i have used that in most of my tutorials and i think maybe these guides too... maybe PyOS needs to use a different license for our tutorials too. I am going to link to your scipy docs here as it's very clear.

Ok this (sub)section now is more verbose:

```
### Important: make sure that you closely follow the guidelines outlines by the License that you chose

Every license has different guidelines in terms of what code 
you can use in your package and also how others can (or can not) use the code in your package. 

If you borrow code from other tools or online sources, make 
sure that the license for the code that you are using also complies 
with the license that you selected for your package. 

```{note} 
An example of code that would not comply with a BSD or MIT license would be any code copied from StackOverflow website. 
[Stack overflow users a Creative Commons Share Alike license.](https://stackoverflow.com/help/licensing) The sharealike license requires you to use the same sharealike license when you reuse any code from stackoverflow. Thus, if you use code from stack overflow in your package and have a MIT license applied to your package, you are violating stack overflow's license requirements! Proceed with caution here!
```

[The SciPy documentation has an excellent license discussion that is worth reading and considering for your project's development guide.](https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#licensing)
```
THANK YOU for calling this to my attention as I really had no idea that CC SA license could conflict with open source.

2023-01-09 19:27 UTC, tupui commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
Looks great thanks 😃 

In practice I am not sure people would really complain with StackOverflow for instance. But better be on the safe side. Same with R and Matlab. If you would go to court, you could make the argument that equations cannot be copyrighted, etc. Also different countries would rule things differently. A mess 😅 

About documentation. Some advice to use a different license than code. It's apparently advisable to use a CC one for the doc and something else like MIT/BSD for the code. e.g. in the GNU world they make this distinction: https://www.gnu.org/doc/doc.html
I don't recall any example in the Python sphere though.

Just adding this for completeness (at least what I know). I would not add that to your text which is good I think.

2023-01-09 19:37 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +* All of its functions and classes (the API) documented
this all makes sense! I appreciate this feedback and insight !!! THANK YOU! i think i've captured most of this in the guide!! (not including typing for now but am going to personally look at mypy a bit more closely. :)

2023-01-09 19:38 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +    """
OHHHHH i follow now. i'll add that. didn't understand where you wanted text after. thank you.

2023-01-09 19:48 UTC, tupui commented on documentation/python-package-documentation-tools.md
> +1. Runs the code in each tutorial: this acts as a check to ensure your package is working as you think it is!
Reads good to me thank you 😃

2023-01-09 19:52 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* DOI (for citation) Example: [![DOI](https://zenodo.org/badge/556814582.svg)](https://zenodo.org/badge/latestdoi/556814582)
awesome suggestion. adding. 

question:

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Lisa"
  given-names: "Mona"
  orcid: "https://orcid.org/0000-0000-0000-0000"
- family-names: "Bot"
  given-names: "Hew"
  orcid: "https://orcid.org/0000-0000-0000-0000"
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2017-12-18
url: "https://github.com/github/linguist"
```

the example that GH uses is above. zenodo has a blanket identifier that you can use for all versions btu then has dated sub identifiers for releases. If you add `date-released` do you have to then remember to update that? or can you skip that and let zenodo do the work? or automate it some other way? otherwise that file will be really hard to maintain i think as it's too easy to forget to update it.

2023-01-09 19:56 UTC, lwasser commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
great insight. i hadn't considered this. i noticed that ropensci uses matomo - it asks for your permission when you go to their site. but it looks like plausible is privacy friendly so doesn't need permission. i'll ask stefan if i could have a look at the dashboard for us to see if it has what we need. that's a no brainer. 

on this guide's front - I don't think many maintainers will want to self host analytics for their package but i think your point is super important. maybe there is another option that doesn't require self-hosting to suggest here?

2023-01-09 20:02 UTC, tupui commented on documentation/readme-file-best-practices.md
> +* DOI (for citation) Example: [![DOI](https://zenodo.org/badge/556814582.svg)](https://zenodo.org/badge/latestdoi/556814582)
I am not sure, I could not find it from a quick glance in the spec https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#date-released

2023-01-09 20:02 UTC, lwasser commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
Super helpful! so what is a free option for people (for pyos this is a no brainer) but what do we guide maintainers towards to use that they don't have to pay for to setup?

2023-01-09 20:04 UTC, tupui commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
Scientific Python does want to provide this service for large packages. For the rest, plausible could be considered but there is no free tier.

2023-01-09 20:05 UTC, lwasser commented on documentation/index.md
> +as the code itself. Quality code is of course valuable as it gets the tasks
not sure if GITHUB is being weird with commit suggestions again but i only see `as the code itself. Quality code is of course valuable as it gets the tasks` as the change so i'll make this change locally with the full sentence you're suggesting!

2023-01-09 20:08 UTC, lwasser commented on documentation/contributing-license-coc.md
> +
i posted on discourse. i'm really struggling with getting targets to work - especially from one page to another. i think i get how they should work maybe but they aren't building for me locally. can you look on discourse?

2023-01-09 20:09 UTC, lwasser commented on documentation/contributing-license-coc.md
> +
https://pyopensci.discourse.group/t/struggling-with-target-headers-in-sphinx-build-myst/297

2023-01-09 20:14 UTC, lwasser commented on index.md
> +Host & Help People Find Your Docs <documentation/website-hosting-optimizing-your-docs>
Oh this is a side bar title. it needs to be short really short. that is too long. it's already too long as it is 
<img width="281" alt="Screen Shot 2023-01-09 at 1 13 41 PM" src="https://user-images.githubusercontent.com/7649194/211399351-fa7f6016-5087-46c3-9ae4-60766c0697f0.png">

Maybe host your docs ? host & optimize your docs but optimize is really generic

2023-01-09 20:30 UTC, lwasser commented
@all-contributors please add @sneakers-the-rat for code, design

2023-01-10 01:27 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +1. Runs the code in each tutorial: this acts as a check to ensure your package is working as you think it is!
thank you. and now i've done a massive organization overhaul and i totally see where i DID say that sphinx gallery and doctest add to the test suite. so i better understand this convo. I've removed and edited that so it's clear that running tutorials and docstrings simply ensures the API works as expected but is not a part of formal testing! (testing doesn't exist as a section yet! thank you again!

2023-01-10 01:29 UTC, lwasser commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
huh shoot... maybe most maintainers don't need analytics? i always geek out on it and use it. but i'm maybe weird.  i'm not sure what to say in this section. i could say GA is not GDPR compliant so it may not be advisable to use it (even tho it's baked into a bunch of our scientific themes)

2023-01-10 01:33 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* DOI (for citation) Example: [![DOI](https://zenodo.org/badge/556814582.svg)](https://zenodo.org/badge/latestdoi/556814582)
ok so here is what i've done. because this PR is really getting huge and i've just down a bit overhaul of the struture - i've created a ISSUE here: https://github.com/pyOpenSci/python-package-guide/issues/34 and tagged it as help wanted. Once we merge this - maybe someone else can take a stab at expanding the license page! it is it's own page now so there is space to add content there. i hope that works for y'all! this is a LOT of new content!!

2023-01-10 01:36 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +# Python Package Documentation
TODO: this is a really important item but i'm going to add this as an issue #35  so we can circle back and work on it given the size if this pr currently is massive

2023-01-10 01:37 UTC, lwasser commented on documentation/index.md
> +1. [**LICENSE.txt file & Citation instructions:**](contributing-license-coc.html#your-repository-should-have-a-license-md-file) A license file declaring the OSI-approved license that you select and i
ok i have yet to add citation.CFF files. I propose that we make this into an issue and add it after we have some time to experiment with how it works and integrates into ... see #34 with help wanted tag

2023-01-10 01:37 UTC, lwasser commented on documentation/index.md
> +1. [**LICENSE.txt file & Citation instructions:**](contributing-license-coc.html#your-repository-should-have-a-license-md-file) A license file declaring the OSI-approved license that you select and i
i did separate out these pages however and did a big overhaul of the structure.

2023-01-10 01:38 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +def extent_to_json(ext_obj):
i love this idea... i am going to make this an issue too... we can then go back and add a section about type hints and add it to the examples.

i also added doctest to this page - it's a new separate page following your suggestion above.

2023-01-10 01:41 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## The CODE_OF_CONDUCT.md file
i wasn't sure what to add on this page. Right now i have contributing and COC as one page because they are both short sections. Maybe we can pull this out as an issue as well and add more to it once this PR is merged? i appreciate this feedback .

2023-01-10 01:42 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## The CODE_OF_CONDUCT.md file
created an issue here #37  that we can then circle back on - great suggestion!

2023-01-10 01:43 UTC, lwasser commented on documentation/contributing-license-coc.md
> +[handy tool](https://choosealicense.com/) for choosing a license.
@sneakers-the-rat are you open to writing a bit more about licenses and COC directly via a pr? we could either add it here OR we could add it once this is merged. When i push my latest revisions up this PR is going to get messy but id' welcome your making direct content additions to it or in a new pr when this is merged.

2023-01-10 06:23 UTC, sneakers-the-rat commented on documentation/contributing-license-coc.md
> +[handy tool](https://choosealicense.com/) for choosing a license.
sure! of course. lmk when it's in a more settled state to add to

2023-01-10 07:28 UTC, astrojuanlu commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
And beyond the GDPR compliance, most people in the target audience block it so it doesn't really give accurate results (at least according to its competitor, Plausible) https://plausible.io/blog/google-analytics-adblockers-missing-data

2023-01-10 17:24 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
cool. thanks. i'm going to add that piece as an issue. I have heard about having license for docs vs code. I mean even in tutorials i've seen separate licenses (maybe would address the SO issue??). but i'll open an issue so it can be discussed a bit more and added if we need to!

2023-01-10 17:28 UTC, lwasser commented on documentation/website-hosting-optimizing-your-docs.md
> +### Google Analytics
ok i added this:

````

```{important} 
Google analytics [is not compliant with the European General Data Protection Regulation (GDPR)](https://matomo.org/blog/2022/05/google-analytics-4-gdpr/). While there are many components to this regulation, one of the core elements is that you have to let users know on your site that you are collecting data and they have to consent. WHile it is possible to add infrastructure around Google Analytics to make it close to following GDPR regulations, the community is slowly shifting away from Google using open tools such as [Plausible](https://plausible.io/), [Cloudflare Web Analytics](https://www.cloudflare.com/web-analytics/) and [Matomo](https://matomo.org) for web analytics. 

pyOpenSci is currently looking into free options for open source 
developers. 
```
````

Essentially i'm not comfortable fully removing GA yet because we don't have an alternative and it is baked into some of our themes. i'm looking into cloudflare web analytics too... but this language should atleast advise folks on GA issues and we can do more research into what tools we could suggest here. i just don't think that most package maintainers would want to pay for analytics as they aren't paid themselves already.

2023-01-10 17:29 UTC, lwasser commented on documentation/index.md
> +## Quick Takeaways: Documentation must haves
i ended up pulling boxes because i've restructured the content. i started adding them because i was uncomfortable with how much info was on each page. we could add it back as a TLDR element in the future BUT... for now they are done and we have a much more clear file structure thanks to @sneakers-the-rat !! :)

2023-01-10 17:30 UTC, lwasser commented on documentation/contributing-license-coc.md
> +
resolving this until i get these targets figured out. i do have headings configured as anchors across the entire site so i'm also confused as to why we'd need a target too ... confused about what sphinx supports here!

2023-01-10 17:31 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## Your repository should have a LICENSE.md file
resolving as there was a big restructure!

2023-01-10 17:32 UTC, lwasser commented on documentation/contributing-license-coc.md
> +A well thought-out continuous integration setup in your repository
fixed

2023-01-10 17:32 UTC, lwasser commented on documentation/contributing-license-coc.md
> +* Any guidelines that you have in place for users submitting issues, pull requests or asking questions.
feel free to fix as you see issues like this!

2023-01-10 17:36 UTC, lwasser commented on documentation/index.md
> +
this entire page has been rewritten but i think i've captured this now.

2023-01-10 17:43 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +* Your package should use numpy-style docstrings
i think this is commented out ... doesn't render on the pages! will go back and add take aways again later given the big overhaul!

2023-01-10 17:45 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +    * Your user facing documentation should also include [short tutorials that show a user how to quickly get started using your package](python-package-documentation-tools.html#create-python-package
it was here in this massive PR! talking with Pamphile. i think i did restructure the language in a few places to clarify tests vs running code / checking the API!

2023-01-10 17:46 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +your Python package. We will discuss API's and docstrings in greater detail below.
fixed!

2023-01-10 17:47 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +User-facing documentation should be published on a easy-to-navigate website. All language should be written with non-developer users in mind. This means
fixed!

2023-01-10 17:47 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +* Your documentation landing page should direct users to 4 core sections: get started, documentation content, about and community.
commented out now!

2023-01-10 17:59 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +API stands for **A**pplied **P**rogramming **I**nterface. When
i don't love linking to wikipedia because they always are asking for contributions. i understand why but i find it really frustrating to always get those big banners at the top when i'm trying to learn something.

2023-01-10 18:25 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +If you are using `NumPy format` docstrings, be sure to include the [sphinx napoleon
i'm following what sphinx uses - https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html  NumPy style for consistency since i tell them to use napoleon.

2023-01-10 18:28 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +(2 to 3 sentences). And the return of the function is specified.
yes i'm most familiar with a single line and then you can have a few lines below (with a space in between). this example was just missing the space!  i think i had removed spaces to make the page shorter as i see a bunch of spacing issues now

2023-01-10 18:28 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +    This format is what shapely uses. The output object can be used
yup done - many mistakes in this example actually!

2023-01-10 18:30 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +* Use sphinx gallery to write tutorials using .py files that automagically have downloadable .py and jupyter notebook files. Use nbsphinx if you prefer writing tutorials in jupyter notebook format an
feel free to open a PR about that! i'm still not clear on all of the extensions and when to use which one. it's not well documented. but i am in contact with Chris so i can ping him. for now i don't want to add more to this already big PR but a new pr with specific types of content after some discussion is welcome

2023-01-10 18:34 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +The functionality of sphinx can be extended using extensions and themes. A few
fixed everywhere.

2023-01-10 18:36 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +This book is created using sphinx and the `furo` theme.
i think in the future - rather than having so many capitalization fixes just fixing throughout in one PR to the open PR would be better. there are literally hundreds of corrections here but i can fix a capitalization with just a single find and replace in VSCode. would make the PR much easier to manage if that was done in the future

2023-01-10 18:39 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +## Create python package tutorials that both help users and test your package's code
fixed throughout

2023-01-10 18:41 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* [snyk - moving pandas example)
yup. they are really well known in the security business!

2023-01-10 18:44 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +
@sneakers-the-rat this guide servers a few purposes. 

We have a checklist for people in our peer review guide to follow that has explicit requirements.
This guide is supposed to help someone understand the requirements (and apply them in some cases). But it's not a requirements guide.

I wonder how we could make that more clear for you - you have fresh eyes here. i've been looking at these guides in a different format, for 4 years. so my eyes are much less fresh :)

2023-01-10 18:44 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +
BTW someone else had a question about who this guide is for too... so you are not the only one with that question.

2023-01-10 18:50 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +the package on both PyPI and Conda be sure to include instructions for both.
Anaconda Cloud is what i've been using!

2023-01-10 18:51 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* The package's documentation page.
will come back to this in another PR. struggling with these links throughout the package not building properly!

2023-01-10 18:51 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +* Contributing to your package
every header is an anchor but the build isn't working. i may ask pradyun in slack about it.

2023-01-10 18:52 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +
added an issue about this - can be added once we better understand how the release date works and how it interfaces with .zenodo files. this can be a future feature in the docs

2023-01-10 18:55 UTC, lwasser commented
> I like :) thanks for all your work writing this. Hopefully these are useful, sorry if they are all very persnickety, thus is the nature of feedback.
> 
> My big global comment is that some macro-level reorganization would be nice: as is the order feels a little random and I am not left with a clear picture of what is required by pyOpenSci re: documentation since it's buried around on a few pages. I see that several files were removed and combined here, and so not sure what the deal is there but I suggested a simple 2-layer nested structure in one of my comments that I feel like would be helpful to keep the docs expandable and also be able to navigate around for someone interested in submitting.
> 
> thanks again :) all my comments 'optional' to take or leave as they're useful or not.

@sneakers-the-rat i really appreciate your thoughts on this and the suggested reorg. it's much cleaner now. i think i was stuck working in an old structure but also trying to move a lot of content across into a new format. i needed your fresh eyes to reconsider organization. THANK YOU for the huge contribution here.  i am SO SO SO appreciative.

2023-01-10 18:57 UTC, lwasser commented on documentation/contributing-license-coc.md
> +[handy tool](https://choosealicense.com/) for choosing a license.
awesome! i'm about to push a really big set of fixes. and then however you want to contribute you are welcome to. You could either submit a PR on top of this pr? Or you can add inline changes here ! however you'd like to do this i'm open . I now have a coc page and a license page. (I may be missing sufficient information around citation.)

2023-01-10 18:59 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +have 4 elements on the home page of their documentation:
i totally understand why. I suspect the new organization will be more clear. I tried to clarify the sections... but let me know what you think.

2023-01-10 19:00 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +def extent_to_json(ext_obj):
issue here - https://github.com/pyOpenSci/python-package-guide/issues/36 i think if we do type hinting we'd want to also discuss it so people understand how to use it and what it does. i think it's a great idea but want to add it with some care!

2023-01-10 19:02 UTC, lwasser commented
ok y'all. i've gotten through MANY of the comments. 
Tomorrow (well if jury duty doesn't consume my day) i'll work through the rest. The current state of this PR is that the entire flow has been improved and updated. so i had to manually update many of the small syntax fixes. it's possible i missed some but i did my very best to get everything!

2023-01-10 19:03 UTC, lwasser commented
I think the last BIG picture comment that i don't feel confident on is how we make it clear what pyos REQUIRES vs just guidance and best practices following @sneakers-the-rat comments. as such i'll open an issue about that as well.

2023-01-10 21:04 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +have 4 elements on the home page of their documentation:
oh and also this is just a suggest for design of package landing page. i added an image below it. (From geopandas)

2023-01-10 21:06 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +    for the extent
@sneakers-the-rat i don't understand this comment and what image you are referring to. what are you referring to ? do you mean in the return when you run `help()`?

2023-01-10 21:06 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +```{figure} ../images/sphinx-rendering-extent-to-json-earthpy.png
i could this is from earthpy i could pull from docs and such - we did run doctest ... let me look at this.

2023-01-10 21:11 UTC, lwasser commented on documentation/package-documentation-best-practices.md
> +```{figure} ../images/sphinx-rendering-extent-to-json-earthpy.png
oh i think i see what you're saying.  i no longer maintain earthpy. we could add this to our examplePy package repo... not in this PR but it's a good idea for the future. then we have full control and can use it for doc updates. i'll make a note of this

2023-01-10 21:12 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +# Python Package Documentation
good point! i've restructured so now the title has sphinx in the name for the sphinx page!

2023-01-10 21:14 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +While you can chose to use any of the syntaxes listed above, we suggest using
@sneakers-the-rat i'm curious - for the package i'm working on now we are using napoleon and myst and autodoc is working fine. can you clarify what you mean here as maybe i don't understand the extent of what MyST-parser does in this context. i saw it as a tool for parsing the text content rather than docstrings. napoleon is what we'd use for numpy-style docstrings + autodoc ?

2023-01-10 21:15 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +## Create python package tutorials that both help users and test your package's code
this is it's own page now AND i've removed the test code part so it's not conflated with tutorials. subheading is now:

`## Create Python package tutorials that run when you build your docs`

2023-01-10 21:17 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +## Create python package tutorials that both help users and test your package's code
ahh good point. i'm trying to balance seo which will like to see words in the ur's with title length. SEO used to really emphasize heading content ...it's def not a minor issue! i've rewritten that heading (see above) so it's shorter.  but if you go too short you start to take SEO hits (unless things have massively changed!)

2023-01-10 21:28 UTC, lwasser commented on documentation/website-hosting-optimizing-your-docs.md
> +1. You can host your documentation using [Read the Docs](https://readthedocs.org/).
it is wizardry!! ok i've updated that page - it was pretty slim before. thanks!

2023-01-10 21:31 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for the pyOpenSci package [Pandera](https://github.com/unionai-oss/pandera). *(screen shot taken
I just learned about adding `:alt:` to that type of figure. i was creating figures differenty i think in our other guide. i'll add alt-tags as they are important. 

also i can't reply to the above comment - so i'll do it here

> `Is this the book/document that describes the requirements for pyOpenSci? If so they haven't been coming through all that clearly, it might be worth it to have a separate page for "pyOpenSci requirements" so people can refer to it as a glance like a checklist to make sure they meet all of them. If that's a different document then just ignore me

I'd like your input here. we have a peer review guide with the actual requirements. but i want to make sure that users know how to find those too. but we want to link to them because it would be too hard to continually update the same standards across both guides.

2023-01-10 21:34 UTC, tupui commented on documentation/readme-file-best-practices.md
> +Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for the pyOpenSci package [Pandera](https://github.com/unionai-oss/pandera). *(screen shot taken
Just FYI some alt text resource Quansight has compiled https://github.com/alt-text-task-force?type=source
We did some workshop to add alt text in some projects.

2023-01-10 21:39 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for the pyOpenSci package [Pandera](https://github.com/unionai-oss/pandera). *(screen shot taken
alt is fixed!

2023-01-10 21:44 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +Your README file should have the following information:
ok yes this is confusing isn't it. we should actually link over to the author checks rather than have a requirements list embedded here

this is what we have now - https://www.pyopensci.org/peer-review-guide/software-peer-review-guide/author-guide.html#does-your-package-meet-packaging-requirements but i see how it's going to confuse readers. 

And THIS represents the initial checks:

https://www.pyopensci.org/peer-review-guide/software-peer-review-guide/editor-in-chief-guide.html#editor-checklist-template

I also just found a BROKEN LINK in the authors guide to the EIC checklist. i wonder how we missed that!

@NickleDave pinging you and @arianesasso on this one. we need to better coordinate between the two guides to ensure authors know what the checks are. i think specific checklists belong in the author guide as include files. then we can LINK to more information here to help them implement those checks. but it will require some thought about cross referencing. I also noticed a link is broken to EIC checks in the author guide!

2023-01-10 21:46 UTC, lwasser commented on documentation/contributing-license-coc.md
> +Your Python open source package should include a file called **CONTRIBUTING.md** located in the
Added this:
<img width="812" alt="Screen Shot 2023-01-10 at 2 46 20 PM" src="https://user-images.githubusercontent.com/7649194/211669156-dafc0313-718e-40e3-9b5b-173594ce6adb.png">

2023-01-10 21:48 UTC, lwasser commented on documentation/contributing-license-coc.md
> +## What the development guide for your Python package should contain
oh it is another guide! the community seems to be moving away from contributing and development being conflated. So contributing guides are more about understanding what types of contributions are welcome - issues, pull requests, questions, and how to submit them. Whereas a dev guide describes the dev workflow - fewer contributors will install pre-commit hooks and want to know about build tools. but that should be documented.

this is particularly important if you want to onboard a new contributor OR for pyOpenSci if a maintainer steps down and we need to find someone new - we want the workflow documented. 

this page tho is also split out as we discussed so i hope the entire section is clearer. pyopensci does NOT require a dev guide but i think it will be important when we need to find new maintainers for packages.

2023-01-10 22:25 UTC, NickleDave commented on documentation/python-package-documentation-tools.md
> +While you can chose to use any of the syntaxes listed above, we suggest using
@sneakers-the-rat means that you can't write docstrings in MyST and have them get parsed by autodoc

Here's  a couple related issues discussing:
https://github.com/executablebooks/MyST-Parser/issues/228
https://github.com/sphinx-doc/sphinx/issues/8018

and one proof-of-concept implementation, not available as a package though:
https://github.com/executablebooks/MyST-Parser/issues/228#issuecomment-1003634938

2023-01-10 22:39 UTC, lwasser commented on documentation/python-package-documentation-tools.md
> +While you can chose to use any of the syntaxes listed above, we suggest using
oh do you mean that 

* what napoleon is actually doing  is converting to rst  (my understanding of it) for autodoc to then ingest and render
* what ppl want is a parser/ renderer via myst that converts directly to html across docstring formats? 

* Maybe in theory...  then you could add syntax like `*text*` into the doc string (not sure i'd want that but curious if that is what it would allow)?? 

**** what is the outcome that is desirable here? napoleon is doing a lot on the back end but it works with little user front end issues.

2023-01-19 16:52 UTC, lwasser commented on documentation/readme-file-best-practices.md
> +Your GitHub repository landing page highlights the README.md file. Here you can see the README.md file for the pyOpenSci package [Pandera](https://github.com/unionai-oss/pandera). *(screen shot taken
woah @tupui this quansight sprint idea is magical. we should do that here too! i have html proofer running on our guide books that actually will flag missing alt tags for you in a PR. (doesn't mean it's a good alt tag however just that it exists)

2023-01-19 16:55 UTC, lwasser commented
ok yall. i am going to MERGE this PR. we've i think had well over 400 comments and contributions here from various folks and i appreciate it all. I will merge but please know this is a LIVING document. it is not the final - this is just round 1. ok round 2 for this content. We will merge and then update / fix enhance as we go. Thank you all for being a part of this vision and for supporting this effort! ✨

2023-01-19 16:55 UTC, merged

2023-01-27 21:55 UTC, arianesasso commented on documentation/readme-file-best-practices.md
> +Your README file should have the following information:
Hey, I checked the links, and the link to the EIC checklist is probably not needed at that point. Then, the checklist listed above could be a link to the EIC page (where it makes sense for the checklist to live), as you mentioned @lwasser. I also missed a  link in the author's guide to this page, e. g. here: `Resources for creating files such as the **README** [Link here to readme-file-best-practices] file, code of conduct, contributing guide, and more.`