Add: changelog-file.md to the Docs-for-Contributors-and-Maintainers section.
pyOpenSci/python-package-guide pull request #222
Opened 2024-04-08 18:56 UTC by miguelalizo

Addresses Issue #215  - Describe what a changelog is in the documentation

2024-04-08 19:28 UTC, miguelalizo commented
I think this addition is in a good state to be review. I tried to capture the information from the issue and maybe a bit more. Open to discussion if anything is missing or needs to be changed!

2024-04-09 20:54 UTC, lwasser commented
@miguelalizo this page is great. Thank you for another wonderful PR. 

Note: when we add new content to our pyOpenSci guidebook, we always have a community review period! I've left a bit of feedback. I also opened the pr up for community review. I gave folks a week to provide feedback. I will check back in next week and we will then get this merged!

2024-04-09 21:21 UTC, miguelalizo commented
@lwasser Thanks for leaving some feedback. I'm having trouble finding where you left the feedback. Is it tied to this PR somwhere?

2024-04-09 21:43 UTC, lwasser requested changes
i'm glad that you pinged me! i left a review and didn't actually submit it. all of the comments should be visible now - my mistake!

2024-04-09 21:49 UTC, ucodery reviewed
This is a wonderful guide. Very motivating to the new project author I think!

2024-04-09 21:49 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +The `changelog.md` document serves as a valuable resource for developers and users alike to track the evolution of a project over time. Understanding the structure and purpose of a changelog helps us
I think we will want to name this file `CHANGELOG.md` to match our other meta files (`CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`). Can you please update all referenced here? Also it looks like we got it wrong in package-structure-code/python-package-distribution-files-sdist-wheel.md, can you bring that change into this PR?

2024-04-09 21:49 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +`changelog.md` is a file commonly found in Python packages. Its primary purpose is to provide a chronological record of significant changes made to the project with each new release. This document he
```suggestion
The primary purpose of `CHANGELOG.md` is to provide a record of notable changes made to the project with each new release. This document helps users understand what has been added, fixed, modified, or removed with each version of the software. In addition, it allows the contributors and users to understand the versioning syntax used for the package.
```

This is a great description. Not trying to pick on it, just emphasizing that there is no real time component to a changelog, except that it happens with releases. And that it's not only for major work, but for any change that could be considered relevant or noteworthy for someone.

> In addition, it allows the contributors and users to understand the versioning syntax used for the package.

can you expand upon this? Typically projects follow one versioning scheme that follows some external rules. I don't see how a changelog would inform the reader about version string syntax.

2024-04-09 21:49 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +[Keep a Changelog.md](https://keepachangelog.com/en/1.1.0/) is great, simple resource for understanding what a changelog is, how to create a good changelog, and includes some pointers of things to av
```suggestion
[Keep a Changelog.md](https://keepachangelog.com/en/1.1.0/) is a great, simple resource for understanding what a changelog is and how to create a good changelog. It also includes examples of things to avoid.
```

2024-04-09 21:49 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +```{admonition} Semantic Versioning
Versioning is a big topic, so much so that we have a guide for it! https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-versions.html

We should link there rather than try and define semver twice in this guide IMO. But a good tip could be that the version string of a release often makes "chapters" in a changelog.

2024-04-09 21:49 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +```markdown
This is great, but I think real examples are sometimes easier to follow than ones entirely made up. We must have a project already that has a well-maintained changelog (@lwasser ?) that we can copy as an example? We could clip it for the code block and link to the repo for curious reader to dig deeper.

2024-04-09 22:48 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +```{admonition} Semantic Versioning
Totally missed this page! Thanks for the pointer. Just added a callout in the admonition

2024-04-09 22:51 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +```{admonition} Semantic Versioning
Thanks for the callout @ucodery . @lwasser mentioned the same exact point in the feedback above and I just made sure to add a call-out rather than duplicating the effort.

2024-04-09 22:55 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +`changelog.md` is a file commonly found in Python packages. Its primary purpose is to provide a chronological record of significant changes made to the project with each new release. This document he
Good point. The intent of the last sentence was to emphasize that the changelog can inform the user of what version of the package to install based on its contents. I agree it has nothing to do with the syntax.

2024-04-09 23:38 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +```markdown
I think this is a great idea. Also, it does seem like the projects will benefit from this guide on changelogs since after going through almost all the [projects on PyOpenSci](https://www.pyopensci.org/python-packages.html), there is an clear trend of not having a standard for changelogs. Some projects have them as rst files, some projects have them as .txt file and many don't have a changeling at all!

I just added the changelog of [Devicely](https://github.com/hpi-dhc/devicely/blob/main/CHANGELOG.md) as it is one of the few markdown versions that also follows semver and is based on [keep a changelog](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://keepachangelog.com/en/1.1.0/&ved=2ahUKEwj3jIHjpLaFAxVqHDQIHcbaAxUQFnoECAcQAQ&usg=AOvVaw2VAelWNVwZ18HnfkpI_8pa). The format is not perfect however, since the with the 1.1.0, it seems the project authors stopped using the Added / Changed / Removed subheadings. 

Please advice if we'd like to revert back to the template example as opposed to the real example from Devicely if needed.

2024-04-09 23:39 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +- [PROJECTNAME-TTTT](http://tickets.projectname.com/browse/PROJECTNAME-TTTT)
See [comment](https://github.com/pyOpenSci/python-package-guide/pull/222#discussion_r1558449643)

2024-04-09 23:47 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +## What does it look like?
This is great! I will add a section titled "How do maintainers use it?" right before the "What does it look like?" section. Also, your writeup is already very descriptive and I'm not sure there is more to add to it.

2024-04-09 23:51 UTC, miguelalizo commented
@lwasser @ucodery thanks for the feedback! I made some edits and left some comments in the reviews to try to clarify any doubts I had.

2024-04-10 17:06 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +The unreleased section then always lives at the top of the file. And as new features are added after release 1.x, they get added to that section.
```suggestion
The unreleased section then always lives at the top of the file and new features continue to be added there. At the same time, after releasing a version like 1.0 all of its features remain in that specific section.
```

2024-04-10 17:06 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +This example comes from [Devicely](https://github.com/hpi-dhc/devicely/tree/main), one of the PyOpenSci reviewed and accepted packages.
```suggestion
This example comes from [Devicely](https://github.com/hpi-dhc/devicely/blob/main/CHANGELOG.md), a pyOpenSci accepted package.
```

2024-04-10 23:40 UTC, lwasser commented on documentation/repository-files/changelog-file.md
> +## What does it look like?
ok fantastic!! thank you!

2024-04-10 23:42 UTC, lwasser commented on documentation/repository-files/changelog-file.md
> +```markdown
i agree with you both - great suggestion. let's use the real world example rather than a made up one!! and i love that we are also highlighting one of our packages by doing this!

2024-04-10 23:46 UTC, lwasser commented on documentation/repository-files/changelog-file.md
> +When you are ready to make a new release, you can re-organize the list of unreleased elements into a section that is specific to that new release number.
ahhhh @ucodery this might be partially my fault. 

[this is what i'm used to seeing](https://github.com/pyOpenSci/pyosMeta/blob/main/CHANGELOG.md)

or [this](https://github.com/stravalib/stravalib/blob/main/changelog.md)
 
essentially you have a large flowing unreleased section. Then when you go to make a release, you organize into fixed, added, removed/ deprecated contributors. 

However your suggest is also good and much simpler. i'm curious what you think? we could stick with the simpler version but add a small breakout on how the changelog might be reorganized for a release (as an option). 

Any changelog is better than no changelog so i'm open to thoughts here :)

2024-04-11 03:00 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +Below the unreleased section, there will be a section for each release. In these sections, you can organize new Fixes, Additions and update together.
I agree. I moved explanation out and cleaned up the section.

2024-04-11 03:07 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +When you are ready to make a new release, you can re-organize the list of unreleased elements into a section that is specific to that new release number.
Both valid points! I think it's easier to just see an example of where my thoughts are on this rather than explaining it. I rewrote the section and took somewhat of a hybrid approach. Let me know what you think!

2024-04-11 03:12 UTC, miguelalizo commented on documentation/repository-files/changelog-file.md
> +```markdown
This section was rewritten. I think we should follow the progress in this thread instead https://github.com/pyOpenSci/python-package-guide/pull/222#discussion_r1559801388

2024-04-11 16:26 UTC, ucodery commented on documentation/repository-files/changelog-file.md
> +When you are ready to make a new release, you can re-organize the list of unreleased elements into a section that is specific to that new release number.
Okay, that makes more sense, thanks for the examples @lwasser!

2024-04-11 16:32 UTC, ucodery approved these changes
Awesome work!

2024-04-15 18:26 UTC, lwasser approved these changes
This looks great @miguelalizo many thanks! @ucodery thanks again for all of the review here!! let's merge!

2024-04-15 18:26 UTC, merged

2024-08-09 14:38 UTC, tkoyama010 commented
@all-contributors please add @miguelalizo for doc