Add: Tutorial for migrating from setup.py to pyproject.toml using Hatch
pyOpenSci/python-package-guide pull request #229
Opened 2024-04-08 21:24 UTC by miguelalizo

Addresses #210 by creating the tutorial for migrating from setup.py to pyproject.toml using Hatch.

2024-04-10 01:25 UTC, willingc approved these changes
Looking good. Thanks @miguelalizo

2024-04-10 19:29 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +See [Get to know Hatch](get-to-know-hatch.md).
This section isn't very helpful unless we give at least a minimal definition. "hatch is a python build tool"

2024-04-10 19:29 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +pip install hatch
The rest of this guide settled on a particular idiom
```bash
python -m pip install hatch
```

2024-04-10 19:29 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +4. **Verify**: Verify that the `pyproject.toml` file accurately reflects your project configuration and dependencies. You can manually edit the file if needed, but be cautious and ensure that the syn
ISTM this guide isn't done yet. Migrating to pyproject.toml implies that setup.py will go away. I think there are two more steps:

5. delete setup.py

6. test - build the project with only pyproject.toml, it should not only build but pass any preexisting tests.

2024-04-10 21:34 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +pip install hatch
Actually, for CLI tools like this we go with `pipx install hatch`

2024-04-11 02:11 UTC, miguelalizo commented on tutorials/setup-py-to-pyproject-toml.md
> +pip install hatch
Perfect, thanks for the clarification. Just updated it to use pipe

2024-04-11 02:15 UTC, miguelalizo commented on tutorials/setup-py-to-pyproject-toml.md
> +See [Get to know Hatch](get-to-know-hatch.md).
Good call! I just added a short description of what hatch is and added a admonition for calling out the get to know hatch page.

2024-04-11 02:22 UTC, miguelalizo commented on tutorials/setup-py-to-pyproject-toml.md
> +4. **Verify**: Verify that the `pyproject.toml` file accurately reflects your project configuration and dependencies. You can manually edit the file if needed, but be cautious and ensure that the syn
Great idea. I expanded on this and added 3 more steps: 

- Step 5: Delete setup.py

- Step 6: Test Build

- Step 7: Test Existing Functionality

2024-04-11 16:18 UTC, ucodery requested changes
Looking really good!

2024-04-11 16:18 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +```
IMO we don't need to add bash examples for every step. Especially as some readers won't want to do everything in the terminal.

2024-04-11 16:18 UTC, ucodery commented on tutorials/setup-py-to-pyproject-toml.md
> +### Step 5: Delete setup.py
This guide switches from an ordered list to numbered headers. Let's stick to one style.

2024-04-12 01:08 UTC, miguelalizo commented on tutorials/setup-py-to-pyproject-toml.md
> +### Step 5: Delete setup.py
Good catch! Thanks for pointing it out. Just fixed it to be consistent

2024-04-12 01:08 UTC, miguelalizo commented on tutorials/setup-py-to-pyproject-toml.md
> +```
I agree. I removed some of these and left only a couple of hatch specific ones.

2024-04-12 16:40 UTC, ucodery approved these changes
Thanks for the edit

2024-04-15 18:46 UTC, lwasser approved these changes
Two approvals. we can merge this as well! in the future maybe we can have a demo repo with a setup.py file that people can play with. but for now let's get this merged!! many many thanks everyone for your effort on this!!

2024-04-15 18:46 UTC, merged