Add: package structure & build tools overview to packaging guide
pyOpenSci/python-package-guide pull request #23
Opened 2023-01-04 00:00 UTC by lwasser

I know this likely will need a good bit of work but look forward to feedback from everyone!!

2023-01-04 00:29 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## PDM
Add: https://github.com/py-pkgs/py-pkgs/issues/95#issuecomment-1026434353 

You can use Flit and PDM at the same time, due to PEP 621. So you can have a build-time dependence on Flit only, and use PDM as a developer. :) PDM's backend does support VCS versioning, though.
PDM can disable default version upper capping via a config option. Still want it to be the default. And it still forces lockfile version capping onto your python limit. (strategy.save)
You can also set an option to disable PEP 582. use_venv or PDM_USE_VENV.

2023-01-04 00:30 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +1. Poetry pins dependencies using `^`. This `^` symbol means that there is an "upper bound" to the dependency. Thus poetry will bump a dependency version to a new major version.  Thus if your package
other notes:

https://github.com/py-pkgs/py-pkgs/issues/95#issuecomment-1035584750 

this addresses the inconsistencies with how it update the pyproject.toml file that pradyun told me about so we can be specific .

2023-01-04 20:52 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## Python packaging tools summary
from @astrojuanlu : https://docs.google.com/spreadsheets/d/1Pv5fJbe7tBRURAfx1FKz4iwAmqgqnJ0KyVqGAiReSG4/edit#gid=0 might want a table for build back end vs front end features of tools

2023-01-05 16:51 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
@eriknw this is SO HELPFUL. thank you. 

> I would love to see examples of some packages in the scientific Python ecosystem that use each of the tools. This helps to see how tools are used, and may help package authors choose tooling if they have similar needs as other packages.

Yes! here is the plan!
1. i will ADD examples from our ecosystem of packages - that is just missing and it's a fantastic idea :)
2. [This (which is pretty much nothing right now)](https://github.com/pyOpenSci/examplePy) is going to be an example package. i plan to pick a dev setup and create really good tutorials around each element of the package. i know there are cookie cutters but i REALLY want people to understand the elements of packaging. its profoundly confusing. In the future we could have a few packages using different tools too. this is likely going to take a few months to stand up - i'm chipping away at it while building out this guide and our peer review guide :) open to thoughts on all of this. As we develop clear, beginner-friendly tutorials they will be cross linked in this guide :) 

> Also, in a broad sense, I don't have a good feel for whether this guide suggests what new or young packages should use, what all packages should use, or what many packages are already using. 

Wow- this perspective is so helpful. i hadn't considered this but you are RIGHT. This guide is ideally for people getting strated with packaging. But also for those who may be switching tools. For instance, i just had to overhall a package that a few of us took over maintenance of. it took me FOREVER to figure out what tools to use. And i was still fuzzy on what each tool does. so it's designed for those two use cases BUT with that said

I developed the list by both talking to a bunch of science focused maintainers and researching tools and considering what tools follow standards best (poetry is out because it does NOT follow standards even tho many use it). 

Can you tell me what you would like to see to make the above (none of which is in the guide) more clear! and also what are your thoughts on this?

> For example, versioneer.py for versioning isn't mentioned at all even though many large scientific Python packages use it. Is there or should there be an effort to switch to other tools such as setuptools_scm?

I actually am working on versioning content now locally:) My last pr's got SO HUGE with so many comments i'm trying to keep them smaller now :) but then you lose some context! 

 it's funny that you mention versioneer. I had it in the guide originally because geopandas / pandas use it and i had talked with martin. Then i got some feedback that it's a really heavy tool from some folks - @stefanv had mentioned this and a few others. SO, i decided to steer clear. BUT when i get that versioning page done i'll put it (in a separate PR) so you can see and we can decide what tools should be included. we could include  it as a commonly used tool but a tool that maybe most smaller packages might not need perhaps? 

> how much of this guide is based on what scientific Python packages currently do vs. what is recommended in the broader Python community? What would this guide look like if it were only based on looking at major and mid-major scientific Python packages?

I am trying to strike a balance here of our mission which is 100% focused on scientific python as it could align with broader standards (ie the work PyPA is doing which some science communities are involved in). but we will always support scientific software. 

Let me know what you think and how i could potentially improve this content to make it more clear and useful! and thank you for this feedback. it's tremendously helpful.

2023-01-06 05:34 UTC, eriknw commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
Excellent, thanks for clarifying! All that sounds great.

Heh, and I wasn't arguing _for_ versioneer. It's squarely in the "legacy" category (and there's probably a lot of legacy things around). This just motivated me to remove it; I chose [`setuptools-git-versioning`](https://setuptools-git-versioning.readthedocs.io/en/stable/differences.html) as the replacement: https://github.com/python-graphblas/python-graphblas/pull/362

Really, though, thanks for your thoughtful replies, and thanks even more for taking this work on! I admire the effort, and wouldn't want to take it on myself ;) . I'm happy to take a look (I'm learning a lot) and share my thoughts from time to time. If your target audiences are scientists, they can be pretty critical, so I hope I can help y'all build trust and present info clearly.

2023-01-06 20:56 UTC, rgommers commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
Hatch only supports pure Python packages as of now. `setuptools` is still a very reasonable choice, and okay if all you have is a few C/Cython extensions. But I'd say you should probably recommend `meson-python` and `scikit-build-core` as the two best tools for building packages containing compiled extensions.

2023-01-06 21:11 UTC, rgommers commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
This particular sentence seems a bit harsh. I don't have much of an opinion on Poetry vs. PDM vs. Hatch (they're all quite similar), but Poetry is the most popular by an order of magnitude, so specifically recommending _against_ its design ideas is probably not warranted. The rationale for `^` at https://python-poetry.org/docs/faq/#why-are-unbound-version-constraints-a-bad-idea is not unreasonable; it has more downsides than upsides on average to use `^`, but part of the problem is that Python packaging has no good answers in this area.

As for breaking changes - `setuptools` and `pip` are responsible for more issues by a large factor than Poetry is in my experience, so YMMV.

2023-01-09 11:16 UTC, astrojuanlu commented
Potentially relevant: Potentially relevant: https://pypackaging-native.github.io/

2023-01-09 11:39 UTC, rgommers commented
> Potentially relevant: https://pypackaging-native.github.io/ (by @rgommers)

As a clarification for PR author/reviewers here: the audience of that site is mostly Python packaging experts. It's about documenting problems so we have a full view and can start working on solutions. If the audience of the pyOpenSci packaging guide are mostly beginning package authors and the main focus is pure Python, then best not to scare them with the hairy stuff probably.

2023-01-09 14:06 UTC, NickleDave commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
> I don't have a good feel for whether this guide suggests what new or young packages should use, what all packages should use, or what many packages are already using

:+1: for @eriknw 's suggestion

@lwasser I know you are trying striking a balance but I do think there could be more concrete language about *why* we can't just recommend a one-size-fits-all approach, something like:
"the Python packaging system continues to evolve to meet the broad and sometimes conflicting needs of many different developers and users. We indicate practices that are currently common in the scientific Python ecosystem, that have resulted in part from unique challenges we face with compiled extensions. We also point out newer practices now recommended for the broader Python ecosystem, which you may find more convenient to adapt if you are just starting to develop your package and it is written in pure Python"

Similarly, in addition to all the work you have already done to summarize the different build and dev tools, we can have an *overall* structure that recommends things from the POV of *what* someone is developing, like @eriknw is saying

e.g. (copying from the scientific-python Discord), add a section (on this intro page with links to build/distrib pages, or on its own page?)

## what tools will I need to build and develop my package?
- my package is pure Python
  - build only: setuptools 
  - build and lightweight development: flit; good to learn before you automate everything
  - full-fledged development tools: poetry, hatch, PDM

- my package has a compiled extension, but it's not a GPU thing / doesn't have very complex dependencies
  + setuptools
  + meson-python
  + scikit-build 

- my package has a compiled extension, but it involves GPU or some very hard to acquire dependencies
  + this is where conda might be a better choice

2023-01-13 01:32 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
PDM supports C/Cython extensions too: https://pdm.fming.dev/latest/pyproject/build/#build-platform-specific-wheels

It does this by allowing you to write a python script that gets injected into a setuptools build process :) so that's not necessarily the greatest choice. It's a bit like using setuptools directly. ;)

But the option does exist.

2023-01-16 19:05 UTC, NickleDave requested changes
Hi @lwasser, again this is a giant step forward for us and you have done a huge amount of work integrating everything you've synthesized from everyone you've listened to. I think all the major parts are there and just need polishing up. 

That said, the one thing I do feel is missing is a little bit more of a guided overview, maybe on the intro page? Similar to what @sneakers-the-rat suggested for docs, maybe something like @eriknw describes, that says "if you're this kind of developer, read this and then do this". Like, something with "personas" of who will be reading this part of the guide.

I have some strong feelings about the package structure page. I have done my best to edit myself so that I don't annoy you so much that you stop listening to me completely. But I still felt like I needed to at least explain a slightly different point of view on the review. I hope that's understandable.

2023-01-16 19:20 UTC, rgommers commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
> this is where conda might be a better choice

That's a little confused I think. If you're focusing on _package authors_, there's no such choice to make. You choose a build system that suits you, and you publish to PyPI (sdist & wheels). You will then _also_ want your package packaged in conda-forge.

For _end users_, you do have to make a choice whether you use conda, pip or whatever else you want here. But that's not what this guide seems to focus on.

2023-01-16 19:42 UTC, eli-schwartz commented on package-structure-code/python-package-structure.md
> +where a build is particularly complex, a **setup.py** file may still be required.
It's not about compiled extensions though. The correct distinction is complex builds.

A complex build could mean running a python script that processes some data file and produces a pure python module file.

Probably not common in the scientific community specifically, but I've seen quite a few setup.py files that contain custom build stages which e.g. build gettext locale catalogs.

The main point is that it is more "complex" than simply copying files or directories as-is into the built wheel.

2023-01-16 22:17 UTC, NickleDave commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
> You will then also want your package packaged in conda-forge.

Thank you @rgommers 

To rephrase you, what about language like this:

> my package has a compiled extension, but it involves GPU or some very hard to acquire native dependencies
> 
>     In addition to publishing an sdist and wheel to PyPI, you may need to publish your package so that it can be installed with conda, e.g. on the conda-forge repository, if you want to enable users on all platforms to be able to install it
> 

The current draft doesn't say a whole lot about conda, so maybe this is one place we can address that

2023-01-16 22:19 UTC, NickleDave commented on package-structure-code/python-package-structure.md
> +where a build is particularly complex, a **setup.py** file may still be required.
Thank you @eli-schwartz this is something I have remained blissfully ignorant of.

Do you have a link to such a package? Just so I can better understand.

I don't quite follow why that couldn't be done by a script that runs before build time.

2023-01-17 06:18 UTC, rgommers commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
That still doesn't sound right. Any package author with compiled code (even simple code) will want their package distributed on conda-forge. The attempt to separate out GPUs or hard code seems unwarranted here.

2023-01-19 00:33 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
hi @rgommers thank you for this input! we have a lot of people reviewing here from different parts of the scientific ecosystem and it's my job to parse through all of this feedback and summarize, clarify etc! 

I do think it's important for us to always cross publish on pypi and conda-forge. and it's quite easy to do so (especially with grayskull which i'm excited about trying vs a manual recipe!). i started to work on a separate page related to conda and anaconda cloud which filipe is reviewing. i'd love your input on all of this  again once i work through the comments and have another clean PR to review!! i will reach out when i get there - likely in a few weeks.

2023-01-19 01:31 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
thank you i will reword! the other issue with it is that it adds metadata to the pyproject.toml a bit differently than the other tools do. which i suppose isn't a huge issue but it's just one more difference in the ecosystem. but most people are clearly using poetry after setuptools. so i can back off the strong language here and just state the differences. I have this dream that there is a single tool as described in your blog post that just does things consistently. that doesn't seem to exist.

2023-01-19 01:33 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +# Python Package Structure for Scientific Python Projects
understood. thank you.

2023-01-19 01:34 UTC, lwasser commented on package-structure-code/intro.md
> +There are some differing opinions on what Python package structure should
i have some language from Chris that i'm planning to use here! so i think the second round will be a bit cleaner.

2023-01-19 01:35 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Setuptools** is the "OG" tool that has been used for Python packaging for many years.
og has several meanings BUT it could be gansta?

2023-01-19 01:36 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
TBH this is always wrong, the rationale is very unreasonable and https://iscinumpy.dev/post/bound-version-constraints gives a pretty good summary of why.

This is a separate concern from "does poetry cause more issues than setuptools and pip".

And poetry doesn't force you to use its design ideas, it merely strongly encourages you both in the documentation and in the default behavior of the CLI tool for "editing the project config without a text editor". You *can* use poetry and avoid the bad version constraints behavior, assuming you know it's a problem -- I suppose that for projects which avoid the unwise ***suggestion***, the actual build process itself may be a bit more stable than setuptools.

2023-01-19 01:43 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
hey @eli-schwartz 👋 welcome to pyopensci!

does pdm support VCS based versioning like setuptools_scm / hatch_vcs does? i'm searching for a tool that 

1. is easy to get up and running (flit is simple)
2. supports VCS based versioning like setuptools_scm supports (because many in the community use this workflow)
3. can be expanded if people do have some non python extensions. 
 
it sounds like pdm supports some basic C extensions but (please correct me if i'm wrong) perhaps not the most elegantly? 

PDM is the one tool i haven't experimented with - YET. I had hoped hatch might be that tool but it sounds like it doesn't yet support non pure python projects. if PDM does then it would be between setuptools and PDM. 

Many thanks.

2023-01-19 01:54 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
oh just in case you want a preview - y'all (not open for review yet - [this is why our guide talks about pypi and conda](https://github.com/pyOpenSci/python-package-guide/pull/27/files#diff-c2e079a470ebde87b939d7b58b4035206c52e71e620113c3a2cbc1fa7825bbafR138)! There's so much to parse through here! thank you all again!  this content after round two will be more clear given all of the feedback !

2023-01-19 02:03 UTC, eli-schwartz commented on package-structure-code/python-package-structure.md
> +where a build is particularly complex, a **setup.py** file may still be required.
https://github.com/giuspen/cherrytree/blob/master/pygtk2/setup.py

https://github.com/mypaint/mypaint/blob/master/setup.py#L73 (mypaint might be cheating? It does a lot, including compiled extensions, but it's definitely doing it for generation of pure python and gettext locales and more).

Here's a fun one, it's modifying man pages to reflect the prefix they are installed into: https://github.com/mbj4668/pyang/blob/master/setup.py

This one wants to run glib-compile-schemas as a post-install hook, because glib schema usage requires compiling the schema or it cannot be found and breaks the application: https://git.launchpad.net/gottengeography/tree/setup.py

Meson itself avoids installing polkit or man pages on Windows, if not for that then the data files could be listed in setup.cfg but we need to do an OS check: https://github.com/mesonbuild/meson/blob/master/setup.py


I could rummage up more examples, but this is probably good enough for now...

> I don't quite follow why that couldn't be done by a script that runs before build time.

Yes, there are also projects that ***cannot*** be built with pip, but have to be built by running a Makefile, that first generates some files and then runs pip / setup.py / `python -m build` as part of the Makefile target. I'm not sure that's really ideal though.

2023-01-19 02:24 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
I'm obviously quite biased as a Meson developer -- I think Meson is a great option. :)

It's a simple straightforward build system DSL -- turing completeness is specifically forbidden -- with great support for multiple languages including compiled languages that setuptools does not support, such as fortran, rust, C#, java, objc, vala, D, swift...

It's not as simple as other build backends might be, but I think it strikes a good balance for approachability.

> is easy to get up and running (flit is simple)

Flit does this specifically by having no configuration -- and only supporting the cases where "no configuration" is viable. It does a beautiful job at that, but for that very reason it cannot ever be extended to support C extensions, among other things.

> supports VCS based versioning like setuptools_scm supports (because many in the community use this workflow)

Flit doesn't even support that, because it's too much configuration and isn't simple enough. :rofl:

The author of Hatch and hatchling provides hatch-vcs as a plugin. It depends on setuptools-scm.

PDM basically copied setuptools-scm into itself, and supports it without extras.

Meson allows you to use `version: run_command('python3', '-m', 'setuptools_scm', check: true).stdout().strip()`, this will run setuptools_scm's command-line to print a setuptools_scm based version and use it as the project version. You can also write any arbitrary python script with more custom logic, and run that instead. I have plans to support this natively using gitattributes export-subst...

> it sounds like pdm supports some basic C extensions but (please correct me if i'm wrong) perhaps not the most elegantly?

It would be more accurate to say that PDM supports using PDM and setuptools at the same time, so you run setuptools to produce the C extensions and then PDM receives the compiled extension files (.so, .pyd) and packages it up alongside the pure python files.

2023-01-19 02:37 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
> I had hoped hatch might be that tool but it sounds like it doesn't yet support non pure python projects.

The author of Hatch seems to believe that Hatch should become the official, *only* supported way of doing python packaging, and that non-pure python projects are best used by:
- using hatch
- [writing your own hatch plugin](https://hatch.pypa.io/latest/config/build/#build-hooks)
- having that plugin run `meson` or `cmake` or `./configure && make`
- obviously, write your own build system files for whichever general "systems programming" build system you use
- do not use that build system's native support for installing files or producing wheels
- have your personal hatch plugin tie this all together

I don't know why this is supposed to be a good idea, but it's the exact opposite of simple. It's write-your-own-buildsystem. I would advise you to not have any expectation that you just need to wait for support to be added. The best-case scenario is that someone publishes a hatch plugin that allows you to depend on hatchling, the plugin, *and* the build system, and then you still need to define your compiled extensions in one ecosystem (meson/cmake/autotools) and install them in a second ecosystem (hatch). And at least you don't have to write your own plugin.

2023-01-19 11:01 UTC, rgommers commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
There are no silver bullets here yet, no workflow tool is complete. Both Hatch and PDM are single-author tools, which is another concern. @eli-schwartz's assessment is unfortunately correct here I believe (at a high level at least, not sure about details). Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build backend hooks in `pyproject.toml`, it's pretty much a dead end.

2023-01-19 20:13 UTC, cmarmo commented on package-structure-code/python-package-build-tools.md
> +* Dependency "pinning": No (but this feature may come in the future)
Nit: pinning is not quoted some places else, also is uppercased and undercased... I suggest to pick one and stay consistent.

2023-01-19 22:47 UTC, lwasser commented
Hi everyone. the review for this section of the guide is now CLOSED while i work on updating things locally. Please refrain from adding new comments UNLESS i ping you (as i might for clarification as i work on each set of comments). Similar to our last round of reviews for documentation, once a new version of this PR is available i'll reopen it to another round of reviews. I suspect this might take more than 2 rounds given the complexity - but we shall see! many thanks for all of the comments above.

2023-01-19 23:05 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
hey @eriknw i wanted to followup here. the other thread is long now with varying topics :)

i checked out your pr here:
https://github.com/python-graphblas/python-graphblas/pull/362

how does setuptools-git differ from setuptools_scm? i'm just curious why you chose that? (collecting data points).

And please know i am going to work on adding specific examples for setup using each tool . And actually stefan and i discussed just creating examples for each in a very minimal setup as a way to look at the various options. so i will probably do that too.

2023-01-19 23:25 UTC, lwasser commented on package-structure-code/intro.md
> +In this guide, we have made decisions around suggested standards and required
This section is now gone! i've woven it into some of the main text and simplified the page.

2023-01-19 23:27 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
@NickleDave it would be super helpful if you have a comment to either +1 someones comment that you agree and if you have more to add, please add it in a separate line of the PR as a separate comment. This thread is super long covering multiple topics and that makes it harder for me to respond to each item and each person ! many thanks!!

2023-01-19 23:34 UTC, lwasser commented on package-structure-code/intro.md
> +standards, based upon the commonly used approaches in the scientific Python
@eriknw i'm pulling our your comment below so i can respond and we can potentiall chat about it a bit as i work locally to update

> More directly: how much of this guide is based on what scientific Python packages currently do vs. what is recommended in the broader Python community? What would this guide look like if it were only based on looking at major and mid-major scientific Python packages?

I have been thinking about this a lot and chatting with folks across communities. I think i'm hoping to :

1. find a single workflow for those who are newer / getting started. BUT one using a tool that is extensible enough to support other backends like meson for instance, as such that someone who did need more complex build steps COULD still use the basic workflow. i say this KNOWING some will strongly disagree with parts of this but... we can't win fully here. the vision being some local to the scientific community consistency in the future!! 
2. Present the broader landscape of tools (maybe not including versioneer 😆 ) so people understand what each tool and option provides generally. But still directing folks to a particular workflow and approach. 

And there is my dream. ✨ can.it.happen? please! :) i will need everyones help getting there!
if the above could happen, then there is no need for two guides EXCEPT for ralf's guide which is needed but also super technical . maybe that is the guide for the larger and more complex packages ?

open to your thoughts...

2023-01-19 23:34 UTC, eriknw commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
I chose `setuptools-git-versioning` b/c it's what `bokeh` chose, and I trust their devs. I suspect I could trivially switch to `setuptools_scm` and wouldn't notice a difference. It was super-simple to set up and it's been pretty nice to use so far (once I figured out how to install our package on `readthedocs` to get a version). As for differences, see here: https://setuptools-git-versioning.readthedocs.io/en/stable/differences.html

I just [configured `setuptools-git-versioning`](https://github.com/python-graphblas/python-graphblas/pull/366/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R111-R114) a little more. I hope and suspect I won't need to worry about version handling for years now.

2023-01-19 23:37 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
based upon the feedback above i have rewritten this section

2023-01-19 23:39 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +package's **SDist** and *Wheel* distributions.
😆 @cmarmo thank you :) i don't know why i did that . probably forgot to hit * twice in vscode :) fixed!

2023-01-19 23:53 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
ok y'all this is a bit of a crossroads. 
Clearly poetry is THE most commonly used tool for packaging (after setuptools). I believe this is because it is SO EASY to start using it. I was able to get started with it quickly and with 0 issues because of the clear docs. i'm happy to back off being so critical of it :) 

I also also want to steer folks towards some tool that is flexible (could support another back end, (Ralf as you mentioned!), follows standards and is maintained!

i don't think we can expect beginners to understand that `^` might be problematic and also why it might be problematic. 

I also don't think we can expect developers, as humans, with varying backgrounds to be religious about semver (or even know about it if they are new). 

so we should assume they new comers will follow poetry's default suggestions :) 

Do you think I should present poetry as a good option, but also  mention the two (potentially) problematic things to be aware of: 

1. upper bounds limits (`^`) <i could mention here that they can simply remove the carrot in their toml file>
2. The way it adds metadata to your pyproject.toml file slightly differently that standards ask us to? (maybe that is not a big deal?)

NOTE: I also have not tested whether a front end like poetry could support a flexible for non pure python builds back end like meson

many thanks for your thoughts here. in the meantime i'll rewrite with less harsh language!

2023-01-19 23:59 UTC, rgommers commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
That all sounds great, thanks Leah. (1) seems important to mention, (2) not so much.

2023-01-20 00:07 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
> I also don't think we can expect developers, as humans, with varying backgrounds to be religious about semver (or even know about it if they are new).
> 
> so we should assume they new comers will follow poetry's default suggestions :)

Well the thing is that this is the problem. Poetry tries to enforce strict semver, that's the entire concept behind its use of `^` pinning.

@henryiii's blog article goes into some detail about that, but particularly note the discussion around CalVer dependencies -- which ***cannot*** be depended on via "strict semver" `^` bounds, but poetry doesn't care and tries to add "strict semver" dependencies anyway.

2023-01-20 00:21 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
ok got it. i'm back to PDM & poetry now based on this (Front ends Eli but perhaps i don't understand meson enough yet)
* DANGER: single developer
* Benefits - 
* i think it could use meson as a back end based on feedback i've given? 
* it has a scm option (i love vcs based versioning and i think a lot of people use it). it is not hard to setup and document and use on a maintainer team. i'm using it with a (small) team i'm on. 

@eli-schwartz my understanding is that meson is not quite ready to be used by beginners? you can correct me. i haven't used it yet. 

or poetry:

Dangers: 
* ^ as a default (we could teach around that
* adds deps and metadata to the toml file a bit unconventionally 😢 
* not sure about a VCS option with poetry??
BENEFITS
* can be used with a meson back end for extensions
* amazing documentation
* many already use it 
* seems to have a small dev team or atleast an active community contributing? 

Thoughts? and thank you for the feedback here. rewriting this page now. 🙏

2023-01-20 01:44 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
Here is a basic Meson-based build, for a project that:
- is called my-awesome-project
- has pure python code in `myproject/` which should be installed as a python module `import myproject`
- has a script that prints the version called `get_version.py`

Note: you also need a pyproject.toml with PEP 621 metadata.

...

Use the equivalent of setuptools find_packages:
```meson
project(
    'my-awesome-project',
    version: run_command('get_version.py', check: true).stdout().strip(),
)

py = import('python').find_installation()

install_subdir('myproject', install_dir: py.get_install_dir())
```


Specify the list of installed files:
```meson
project(
    'my-awesome-project',
    version: run_command('get_version.py', check: true).stdout().strip(),
)

py = import('python').find_installation()

py.install_sources(
    'myproject/__init__.py',
    'myproject/foo.py',
    'myproject/bar.py',
    'myproject/submod/__init__.py',
    'myproject/submod/baz.py',
    'myproject/submod/frob.py',
    preserve_path: true,
)
```

It can definitely be used by beginners. :) However, the power available within Meson is not fully realized with such simple examples -- once this scales to more complex things like 
```meson
py.extension_module(
    'c_mod',
    'myproject/c_mod.c',
    install: true,
    subdir: 'myproject',
)
```

then Meson really starts paying off.

2023-01-20 07:20 UTC, stefanv commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
I like meson very much. That said, I think it has two rough spots:

1. You need to know the magic incantations to configure and build, which happens in stages.
2. If you don't want to use those incantations, you can use pip, but then you loses out on incremental rebuilds.
3. In-place builds are still experimental (waiting for symlinks so that dev installs function like we're used to).

In this regard, I think setuptools, while not the design I prefer, is easier for programmers who "just know Python". I looked at the scikit-learn setup.py earlier today; it's a big build setup with various technical tweaks, but every part can ultimately be dissected by someone who knows Python.

I still think meson is quite possibly where we will land long-term, I'm just not sure it's what should be recommended (especially to beginners) *right now*.

2023-01-24 17:28 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +layout such as tests being included with the package when they are installed) to
> Also reminder from discussion in Slack that some people exclude tests to reduce the size of the source distribution, especially if the tests require some giant wad of test data, as if often the case for scientific packages

@NickleDave  i need you to understand that your opinion on packaging is not the only opinion here. And this specific topic is a bike-shedding topic to many so i have to collect opinions both in the open and via private conversations. many just don't want to engage in this type of argument.  i also don't need a reminder about conversations that happened in slack. I have pages of notes from conversations that have happened in slack, discord, email , private dm's etc. it is not efficient to keep rehashing these circular arguments. 

As an organization we will make decisions. At the end of the day I am going to make some decisions that some people might not like (this is inevitable). I will make those decisions with the bigger goal of streamlined approach to packaging projects that aligns with the broader scientific python efforts. I will do what is healthiest for the broader community even if it is not perfectly inline with my personal opinions about packaging, data science etc!

2023-01-24 17:33 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +# Python Package Structure for Scientific Python Projects
> I know you know this stuff already but since this review is a place where we talk about this stuff in the open, I am going to plainly state the details here. 

This is really unhealthy language for a review. If you know what i know why are you rehashing it over and over throughout this review? there are many opinions around this topic and in the end we shall pick a pack forward. please don't bring up what i know and don't know as it doesn't help me get to the goal which is a shared vision for what packaging looks like. this feels extremely counter productive to our mission.

2023-01-24 17:35 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +When you make a release on GitHub, it creates a SDist file (`.tar.gz`) that
see what happens when you make an sDIST locally with setuptools without a manifest file and without a setup.py file. it depends on the tool how things are packaged.

2023-01-24 17:39 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +# What is a SDist and Wheel? About Python Package Distribution Files
> I haven't seen someone refer to an sdist or a wheel as a "file" before -- aren't they technically an archive with a bunch of files in them? 

when you have a file.zip do you say file distribution of zip file?  trying to help users understand what a whl is just a zip file and a sdist is just a tar ball which also is just a fancy zip file on some levels. many know what zip files are and in a directory they look like individual files.

2023-01-24 18:05 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +   * Tools like build won't automatically find the package directory if it's
would love to have comments only in one place if they are the same topic / idea. 

how do you build with setuptools? build is the way i do it and a lot of folks i think build that way to create sdist and wheel  (look at fatiando)? 

setuptools is the most common packaging tool so your question about how many people use it is a bit confusing. can you explain your question?

2023-01-24 18:06 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +for the `src/` directory when installing the package
it's just a small but extra set of steps between find_packages and other setup items.

2023-01-24 18:09 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that needs to be compiled is stored in `src/`.
this isn't for experienced devs. i can remove con if that is what you are strongly responding to given your strong opinions about src/ . but the bottom line is adding src/ is another step to think about in a build. it could have some value but i'm might not be worth the community overhead that it would cost to suggest it. people can do what they want but we have to make some decisions for beginners. 

grok is such a funny jargon word.

2023-01-24 18:10 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +
i think this is a question but also a statement. Are you saying that you think it would be nice to have a short introduction to the PEPs that drove the pyproject.toml file ?

2023-01-24 18:16 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +1. Because setup.py has a mixture of code and metadata, it opens the user to a potential bad code injection on their computer when the package is installed.
that list was not intended to be 1 as in the most important. it's just a list of reasons why it might make sense from moving away from setup.py.

 i will talk more to my security friend who specializes in this space. my talks with them and what i've read suggest that security is 1 or a few reasons to try to avoid setup.py. i see that you are questioning me on this here but also that you potentially aren't an expert in this area so i will followup with experts to resolve this.

2023-01-24 19:05 UTC, eli-schwartz commented on package-structure-code/python-package-structure.md
> +1. Because setup.py has a mixture of code and metadata, it opens the user to a potential bad code injection on their computer when the package is installed.
I have some expertise in this matter, although don't take my word for it.


But. Consider what the goal is of avoiding a security flaw. You want to offer protections against running code which you don't trust, which *might* be malicious (it might also be perfectly safe).

To solve this, you need some mixture of a few guarantees:
- the end user can prove or configure via policy that external code is not run, at all
- external code is run, but it's only run inside a security sandbox -- this may be a language runtime which is deliberately "crippled" to not provide access to filesystem I/O, network, the ability to spawn subprocesses, or some combination thereof. It might be running inside a container such as docker, or a full-blown Virtual Machine. The code may turn out to be malicious, but the worst thing that can happen is it damages the sandbox, which is destroyed after use anyway.
- external code is printed, and possibly linted, before the user reads it and confirms that it's safe to run (this is hard to get right, and mostly serves to separate "definitely safe" from "this is running a lot of recursive code which is difficult to read"
- external code is cryptographically signed by key in the trusted set, and the user doesn't know what the code is but can cryptographically verify that it comes from someone that is trusted, so, by extension, it must be trusted code


Untrusted code can come from a few different places. In the context of python packaging, untrusted code can be either:
- the build backend listed in `build-system.requires`, although a few common ones are considered commonly trusted ;) this includes setuptools, poetry_core, flit_core, meson-python, maturin, scikit-build, pdm, hatchling...
- a file which the build backend is instructed to evaluate. For:
  - setuptools, this is setup.py *and* setup.cfg, the former unconditionally and the latter if and only if setup.cfg has config keys that specify a value to be loaded as `attr: ...`
  - poetry, this is build.py or some other file listed in pyproject.toml
  - pdm, this is build.py or some other file listed in pyproject.toml
  - hatchling, this is additional build-system.requires listed in pyproject.toml as hooks
  - meson-python, this is `meson.build`
  - scikit-build, this is `CMakeLists.txt`
  - maturin, this is `build.rs`
  - flit, this is `project_name/__init__.py` if and only if "description" or "version" are specified as dynamic metadata

Note in particular that it's a common mistake to think that flit doesn't evaluate any untrusted code -- it does, it will import the python package itself to retrieve the version number (and description) and it will automatically do this as a fallback if you don't set one. Setuptools can do the same thing with a formalized approach -- a setup.cfg "magic value" that says "get the real value by running the python package and importing the value from it as python code".

...

Above all else, you must consider the following ironclad rules:
- if a malicious attacker can tell you to disable your security measures, then you don't have security measures
- if a malicious attacker can trick you into safely installing malicious code, even though you didn't *run* that code while installing, you are only safe up until the moment you try to run the software you just installed


In particular, since the build backend can tell you whether to use setup.cfg or setup.py, an attacker is not forced to use setup.cfg. This is a solvable problem if setuptools offers a "secure mode" that forbids using setup.py or dynamically imported attributes. You could ask for such a feature from the setuptools developers -- if they implement such a thing you could then use it like e.g. `python -m build -Cwith-safe-load` or something, and projects using unsafe setup.py will fail to build with an error message saying it was unsafe.

2023-01-24 20:20 UTC, henryiii commented on package-structure-code/python-package-structure.md
> +that needs to be compiled is stored in `src/`.
src has the same benefits in Scientific Python code. The problem is Scientific Python codebases are large and moving all your source code is painful on a large, shared projects. One of the key benefits, actually, is for compiled code. The old workaround, `python setup.py build_ext --inplace` is deprecated and dying, so I'd expect to see more projects finally bite the bullet and make the move.

Boost-histogram is an example of a project with `/src/boost_histogram` and `/src/*.cpp` files.

2023-01-24 20:20 UTC, henryiii commented on package-structure-code/python-package-structure.md
> +* CONTRIBUTING.md
FYI (doesn't need to change here unless you really want to), I prefer `.github/CONTRIBUTING.md`, keeps the src cleaner, reduces scrolling to get to the README, and still pops up as a suggestion when making a PR.

2023-01-24 20:20 UTC, henryiii commented on package-structure-code/python-package-structure.md
> +
We have been discouraging linking to or even mentioning PEPs. Those are intended for implementations, but not as long-standing documents. The canonical location is packaging.python.org's specs.

2023-01-24 20:20 UTC, henryiii commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +When you make a release on GitHub, it creates a SDist file (`.tar.gz`) that
I would absolutely not call a GitHub release an SDist. An SDist is a Python Source Distribution. It contains a generated metadata directory. A GitHub tarball is a `git archive` output of the source repo, and will not contain that generated directory. It is not a valid SDist.

2023-01-24 20:23 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
FYI, Poetry will move to PEP 621 configuration in version 2. There will be automated tooling to convert a V1 pyproject.toml into a V2 pyproject.toml, but for new users, I'd just say use PDM (probably with hatchling as a backend :)), then if you want to switch to poetry after V2, just change a few lines (maybe as little as two) and you'll be using Poetry even easier than the original users running the conversion scripts. ;)

2023-01-24 20:24 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +## PDM
Actually, it's an option to enable PEP 582 these days. The author was afraid people were avoiding PDM because of the not-yet-accepted use of the PEP, so it's off by default in version 2. PEP 582's just been submitted to the steering council.

2023-01-24 20:33 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +| Build backend                                                          | setuptools.build_meta | flit_core | hatchling |  pdm-pep517   |
@henryiii this is what i've been trying to get at - what tools would support a move to something like meson that could then support more complex builds. so if we teach PDM people could add on to it for more complex builds IF they so desired. 

and making not of the GPP™️

2023-01-24 20:45 UTC, lwasser commented
@henryiii thank yo ufor this input. i'm happy to adjust language throughout! 
one point of clarification here:

> I would absolutely not call a GitHub release an SDist. An SDist is a Python Source Distribution. It contains a generated metadata directory. A GitHub tarball is a git archive output of the source repo, and will not contain that generated directory. It is not a valid SDist.

I think i understand what you are saying. 

Below are two screen shots. you can see that the Sdist that setuptools build creates is not too different from the tarball from github except for the fact that the .egg dir has some metadata files and setuptools adds a manifest and PKG-INFO files (metadata type files). but the source code is the same. 

So how would you describe to beginners that just look at the files how the github tarball is different from the created Sdist? would it be correct to focus on that generated metadata directory that you mention above? and as such that metadata is what makes it a source distribution (even tho you technically could install from the github tarball too if it was pure python)? many thanks! 

<img width="455" alt="Screen Shot 2023-01-24 at 1 40 16 PM" src="https://user-images.githubusercontent.com/7649194/214405685-c4d87577-c505-41f0-b19f-fd5a4acb4660.png">
<img width="271" alt="Screen Shot 2023-01-24 at 1 39 34 PM" src="https://user-images.githubusercontent.com/7649194/214405694-00bce31c-c56a-4b16-89ce-2f47aa6172d9.png">

2023-01-24 20:47 UTC, eli-schwartz commented on package-structure-code/python-package-structure.md
> +a **proproject.toml** file sometimes combined with a **setup.cfg** file.
(I pedantically insist on using `.flake8`, `.pylintrc` or `.mypy.ini`, I don't want my flake8 configuration to overlap my build metadata whether that is `setup.cfg` or `pyproject.toml` :stuck_out_tongue_winking_eye:. Fortunately, ruff supports `ruff.toml`, so that's not a concrete reason for me to avoid ruff. All this being said, using setup.cfg for flake8/pylint/mypy/whatever does seem like the worst of all possible worlds.)


The important thing to note about setup.cfg in this context is that if the goal is to write a guide explaining how to "setup a package installation" then, indeed, setup.cfg is experimentally deprecated by pyproject.toml for setting up the package installation with setuptools. https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

Note also: `[tool.setuptools]` is considered beta-quality, which may be an argument in favor of setup.cfg, although many packages especially simple ones probably don't actually need that anyway.

2023-01-24 20:49 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
@henryiii i appreciate this. i keep getting conflicting information about what hatchling and poetry can and can't support. i'm not sure how to get this right given that. is it maybe that hatch doesn't support implementing custom steps but would with a plugin because hatchling can? @rgommers i wonder if you can perhaps chime in here? it was my understanding that hatch or hatchling has some limitations. this is where i haven't tested non pure python builds yet to know.

2023-01-24 20:54 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
@henryiii that is great. do you know if poetry might be open to an option to remove the `^` for deps in the future? And if not, do you know if it's easy enough for a user to just manually remove that before build? it sounds like PDM might be the way to go - id love to add to the docs however for a beginner workflow.

2023-01-24 20:57 UTC, henryiii commented
They are very similar files, but they don't have to be. If you are using setuptools-scm or another VSC versioning tool, they will add a version file to the SDist. (Nowadays, you can get a version burned into the git archive too with `.gitattributes` file & a template file, but it won't be the same location and file as the SDist). You can also control what goes in the SDist - people often remove CI files and things like that from the SDist. Docs too if they are large.

The PKG-INFO file is required, as per https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-format. So the git archive is never an SDist.

They are ultimately simply similar but not the same file.

2023-01-24 21:03 UTC, eli-schwartz commented
On the sdist vs. github autogenerated archives topic, maybe it helps to provide some wider context?

The python concept of an sdist isn't unique to python -- the C/C++ communities, the autotools community in general, and to some extent the "multi-language projects" communities face the same challenges.

By autotools convention -- and usually copied elsewhere -- there is the concept of a "dist tarball" which is not the same as a snapshot of the git revision control contents. A dist tarball is distributable source code, user-oriented rather than developer-oriented, and:
- can contain files that are not in git
- can exclude files that *are* in git

You make this with `make dist` or in Meson's case, `meson dist`. CMake can be coded to use cpack.

Dist tarballs for autotools will include configure and Makefile.in which are generated from templates (configure.ac, Makefile.am). Dist tarballs for *any* build system or project may contain git submodules, or possibly even sources which are `wget`'ed by the build system (it is a bad idea to wget your sources, at least without checksums but people definitely do it). 

Dist tarballs can exclude stuff that isn't needed for distribution. This might include CI scripts, the `.github/` directory, etc. -- none of this is necessary unless you're hacking on the CI. Other excluded content might be intended exclusively for use by people who have the full git repository of the project to work with, for bisecting, githooks, etc.

For python, specifically, the generated metadata directory is python's equivalent of the autotools configure script. It's really useful in many cases, and absolutely critical in some -- such as setuptools_scm's version finder, which requires to either be run from a full git repo, or be run from an sdist that contains the generated metadata (which was generated in a full git repo).

Github autogenerated tarballs contain effectively none of this functionality. And that actually results in build errors for projects that use setuptools_scm, if people attempt to use github autogenerated tarballs for building.

2023-01-24 21:08 UTC, henryiii commented on package-structure-code/python-package-structure.md
> +a **proproject.toml** file sometimes combined with a **setup.cfg** file.
I'm not against mentioning setup.cfg, just against mentioning combining pyproject.toml and setup.cfg. :)

2023-01-24 21:10 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
- poetry: supports it, but is undocumented and uses setuptools under the hood, they plan to change how this works and *then* document it
- pdm-backend: supports it, and documents it -- and also uses setuptools under the hood
- hatchling: permits you to define hooks for you to write your own custom build steps, including to build C++ extensions

This was discussed a bit at https://github.com/pyOpenSci/python-package-guide/pull/23#discussion_r1063793389

2023-01-24 21:18 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
No, though I don't know how it will behave in version 2 - there's a chance they might avoid `x,<x+1`. But I'd doubt it. The reason is really the locking solver and the Python version - if you depend on a single package that has `python<4` (which there are now quite a few due to Poetry's defaults), then you _can't_ solve with an open Python version - the lock file limit then must be <4 and that's the same as the Python limit - so the problem they've been shoving onto library authors would suddenly affect default users - so I'd predict they are sticking to their limits. Maybe, just maybe, they will do what I want and allow the metadata option and the lock file limit to be specified separately, which would solve the issue, but we'll see.

2023-01-24 21:28 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
Hatch is the frontend, hatchling is the backend. The plugins are for hatching, technically, though they use the naming convention `hatch-<plugin>`. The only existing plugins I know of also use setuptools under the hood, such as the mypyc one, but wants to move away from it (could easily be wrong here, CC @ofek). I'm planning on helping with integration with at least scikit-build-core, and hopefully standardizing a way to build plugins for extensions.

Hatch is the unified user-facing CLI tool and environment manager (basically like flit + tox). I personally mostly use standard tools (venv/virtualenv, nox, build, pip, twine, often via pipx), and when I do use a frontend, it's for the locking, so I use PDM. I know some people who really like Hatch, though, for its handling of environments.

There is an example of poetry using meson via a script, but you can't really do it properly without connecting to the build hook. For example, you can't specify "ninja only if it's not installed" unless you have privileged communication with the build backend. Which means you can't support systems without binary wheels (which is one of the main places you need a good build backend).

2023-01-24 21:32 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +| Build backend                                                          | setuptools.build_meta | flit_core | hatchling |  pdm-pep517   |
PDM should support scikit-build-core and meson-python out of the box. (Unless you don't use the PEP 621 configuration for meson-python, which I don't recommend doing). AFAIK, it's the only one to handle this correctly - all the other front ends are tied to their own backend. I'd love to see Hatch change, and I hope Poetry does it right in Version 2. Flit probably won't - the author was even asking if people still wanted the front end (I don't - flit-core is great for minimal dependency bootstrapping, but flit the CLI app doesn't solve enough and causes issues by changing flit-core's file discovery).

2023-01-24 21:44 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +| Build backend                                                          | setuptools.build_meta | flit_core | hatchling |  pdm-pep517   |
Flit as a CLI application is very different from hatch, pdm, poetry etc as they all provide far more than just a build frontend. As far as a flit CLI goes, I'm a staunch believer that setuptools was wrong to deprecate setup.py, solely on the basis that I believe all build backends must provide a CLI command to bus the wheel minimally. I'm sad to see "just use python -m build", but it is what it is... Setuptools had a *bad* CLI, so everyone decided that CLIs are inherently bad. :(

`flit build` was more interesting to me before flit_core gained a `python -m` option to build wheels. I'm otherwise unsure what you'd use the CLI for.

2023-01-24 21:46 UTC, henryiii commented on package-structure-code/intro.md
> +standards, based upon the commonly used approaches in the scientific Python
I'd say there are two options: show the standard tools that do one job, but do it well. IMO, there's not much difference between:

```
flit build
poetry build
pdm build
```

And

```
pipx run build
```

Except the later always works, even in CI, even in reusable workflows, you can put a version of it in nox/tox files, everywhere, even if you switch backends daily.

Same thing for all the alternatives and `pipx run twine upload dist/*`. Again, it doesn't matter what unified tool someone comes up with, this can be put into a GitHub Action and reused on all your projects.

To show just one frontend tool, then PDM seems to be the best option at the moment. You can use any backend, so it should work with scikit-build-core and meson-python. It has built in commands for the various things you'd probably want to do. It's got lock files, too.

Hatch is another option, but not supporting arbitrary backends is a huge downside; no lock files yet is one too. The up-side is it basically can replace nox/tox, being a true "all-in-one" tool. While ideally you should still having a nox/tox file.

2023-01-24 21:49 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
> The only existing plugins I know of also use setuptools under the hood, such as the mypyc one

That is the only plugin that uses setuptools

2023-01-24 21:51 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +| Build backend                                                          | setuptools.build_meta | flit_core | hatchling |  pdm-pep517   |
Hatch will be able to build projects that don't use Hatchling in 2 minor releases from now

2023-01-24 21:59 UTC, ofek commented on package-structure-code/intro.md
> +standards, based upon the commonly used approaches in the scientific Python
> Hatch is another option, but not supporting arbitrary backends is a huge downside

Hatch will be able to build projects that don't use Hatchling soon

> PDM [...] got lock files

That's kind of a nebulous term though, does it support source distributions, does the lock file work on all platforms, etc. Just saying it has something doesn't mean much in this case without more details (the same goes for Poetry)

> PDM seems to be the best option at the moment [...] It has built in commands for the various things you'd probably want to do

How does that differ from what Hatch provides?

2023-01-25 01:00 UTC, lwasser commented
ok everyone. thank you so much. And my apologies if i sound a bit "testy" today. i didn't get a lot of sleep last night and am having one of those "off" days. 

I think i need to now take all of the above comments and digest, and try to come up with better language that does justice to all of these tools. I will ping y'all once i have a better / more accurate / less opinionated rewrite and will likely have more questions. Many thanks everyone for this amazing feedback! i know the end product will be worth all of the discussion here.

2023-01-25 04:32 UTC, henryiii commented on package-structure-code/intro.md
> +standards, based upon the commonly used approaches in the scientific Python
Poetry's work well, though they make a mistake in metadata - they assume metadata can't change between wheels of the same version, which is incorrect, but very commonly good enough. PDM's file work great for the reason I use lock files - they allow me to control updates. I'm not sure how they work for security (which I think is the main issue people are worried about for SDists in a general lock file description). But being able to have a locked set of versions for an application you deploy (like a website) is crucial.

> How does that differ from what Hatch provides?

It doesn't, my point is it provides a very useful core feature (the ability to control updates, similar to Gemfile.lock, package-lock.json, etc - and really the only reason I use a frontend) but all the other commands Hatch has as well (which, by the way, I never use - I always use `pipx run <build/twine>`).

2023-01-25 23:17 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
ok thanks y'all. I think what i'm reading above is that part of this also has to do with HOW the front-end tool is able to "communicate" with the back end tool. 
Summary:
*  pdm, hatch and poetry all have "ways" of supporting c extensions via pdm-build, hatchling and poetry's build back end. 
* poetry's support for C extensions is not fully developed and documented (yet). Poetry doesn't offer a way to facilitate "communication" between poetry front end and another back end like meson to build via a build hook. 
* PDM and hatch both offer a plugin type approach to support custom build steps 
* PDM (right now) is the only tool that supports other back ends (hatch is working on this - 2 minor releases away)
* At some point a build becomes so complex that you need to use a tool like scikit or meson to support that complexity.

2023-01-25 23:57 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
> PDM and hatch both offer a plugin type approach to support custom build steps

- pdm doesn't use plugins. Hatch does.
- pdm and poetry both rely on setuptools for C extensions. pdm's support claims to be fully developed and documented. poetry claims nothing, and doesn't document it.

Other than that, I think your summary is accurate.

2023-01-26 00:03 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
got it. ok thank you all. the discussion here was one i thought was in my emails... so i think i have a better understanding and will work on cleaning up this entire section. 

If we did end up suggesting PDM... what is the benefit of using hatchling as the backend vs pdm's back end(s) (they actually had two options for a PDM back-end when i tried it (pdm517 and pdm-backend). 

(Options PDM provides in their init workflow below)
```bash
0. pdm-pep517
1. setuptools
2. flit
3. hatchling
4. pdm-backend
```

2023-01-26 00:34 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
I would say:

1. File inclusion is more configurable and easier by default
2. There is already a rich ecosystem of plugins and a well-thought-out interface
3. Consistency since the official Python packaging tutorial uses Hatchling by default

Also out of curiosity, is there a deadline for the frontend recommendation? If so I'm wondering what Hatch needs to implement in order to meet your criteria by then

2023-01-26 00:53 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
> File inclusion is more configurable and easier by default

You will not get easier than flit. :P

> There is already a rich ecosystem of plugins and a well-thought-out interface

I would disagree about well thought out interface, but clearly that's highly subjective.

> Consistency since the official Python packaging tutorial uses Hatchling by default

I seem to recall that the packaging tutorial specifically wanted to ignore the bad vibes of being opinionated here, and hatchling narrowly won the position of "first on a list of equals" with the understanding that it wouldn't be pushed as "PyPA is telling you you should probably use this and ignore all others".

Tremendously disappointing to see the author of hatchling evangelizing that hatchling should be recommended as the preferred ideal backend because "it's what the official packaging tutorial for all of python recommends as the default". That's some nice weight to bring to bear. ;) Also pretty circular.

Seems like it was a bad idea after all, to allow hatchling to declare itself "basically the default way to package python software, as declared by PyPA"?

2023-01-26 01:07 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
I think you're reading far too much into what I'm saying unfortunately, and frankly I'm confused why you have such an adversarial tone here. I was responding to the question that was asking the benefits of Hatchling over PDM's backend.

2023-01-26 01:14 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
To be fair, you did randomly bring up Flit so perhaps you just didn't realize I was answering a direct question.

2023-01-26 01:41 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +* PDM
thank you @henryiii @astrojuanlu also had commented on this with my table mixing back ends and front ends. TBH i'd used setuptools for years but didn't understand it just isn't / doesn't have a front end. i'm still actually a bit confused because build is what you use to build your package. but setuptools is the back end.

But what i plan to do is mention just mention that setuptools is a very mature packaging tool that supports backwards compatibility in packaging and is the most commonly used tool. Then in that table i will remove setuptools and add poetry. 

i'm going to suggest that users don't use setuptools and pick a modern front end that supports other back ends like meson.

Does that sound reasonable?

2023-01-26 01:42 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
"The benefit of hatchling over PDM's backend is that it's more consistent with the python packaging tutorial, which uses hatchling by default."

What is the "benefit" here? Sounds like you're trying to suggest using the weight of the python packaging tutorial, that people should use something based on the merit that the python packaging tutorial implies you should? The benefit, in other words, is "you want to agree with the python packaging tutorial, don't you"?

Note also that the goal of this tuturial isn't necessarily to transclude the python packaging tutorial to begin with -- for example, the "guide to scientific python package recommendations" per definition has different priorities compared to the "guide to generic python packaging" which is what PyPA's guide is (the vast majority of python packages have no real build steps, but the scientific community doesn't have that bias and may in fact have the reverse bias).

So the "appeal to authority" of the ***Official*** python packaging tutorial is not, in and of itself, a signpost to the best thing for scientific python.

> frankly I'm confused why you have such an adversarial tone here

It makes me *exceedingly* uneasy to see a tool being suggested as beneficial to be the recommendation, by the developer of that tool, using the logic that effectively boils down to "PyPA said you should".

You want to argue in favor of hatchling's excellent UX or how you think that it solves the problems faced by scientific python? Go right ahead, that's eminently fair and I have absolutely zero issues with that. The best person to answer how a tool can solve a need is, naturally, the person who wrote and documented the tool.

You want to argue in favor of hatchling's superiority with subtle attempts at "because PyPA says so" and I start getting very suspicious, and TBH that colors my entire view of this conversation.

2023-01-26 02:01 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +* PDM
How are we defining frontends? Do we mean "a CLI command that builds the project"? Do we mean "a project management tool providing various lifecycle helpers including, but not limited to: building, testing, installing, publishing to PyPI, environment management, editing project configuration, and more"?

Setuptools has a CLI command that builds the project -- it's just deprecated. You don't have to use `python -m build`, you can use `python setup.py bdist_wheel` if you don't mind getting a warning that someday they will remove this.

flit-core has `python -m flit_core.wheel` which builds the project. Is this a frontend?

...

If the section intends to focus on the CLI user experience, then honestly I'd say, just suggest the use of `python -m build` "or you can use a full project management tool such as PDM or, in two minor releases, hatch". A guide to choosing options for getting started, doesn't need to focus on the specifics of what tools have wired up their own private CLI. People who care about that will learn about it *after* they have chosen a tool and gotten comfortable with it.

If the section intends to focus on the configuration and support for build steps and other aspects of getting the software into a package, then avoid mentioning hatch or pdm -- mention hatchling and pdm-backend.

2023-01-26 02:13 UTC, stefanv commented on package-structure-code/python-package-build-tools.md
> +* PDM
Perhaps this has been covered, but typical front-end uses would be ... ? I'd list:

1. build package
2. install package
3. install package as editable
4. bundle package into binary wheel
5. bundle source into sdist

That's what we typically need during development workflow. Uploading I can always do with twine.

`python -m build` covers (4) and (5), with (1) implied?

There are some alternative workflows for 2 and 3, such as launching a Python interpreter with PYTHONPATH correctly set (like we do in `devpy`), but I think installs (+ editable installs) are preferable.

2023-01-26 03:05 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
The fact that it's the default in that other major tutorial was not in my main points, it was the last one I added. The main two points you very quickly discarded and began focusing on this one.

If two tools provide the same functionality, would you not say it's beneficial to have consistency with things that currently mention one of those?

As far as your comment about the build hook interface, do you have any suggestions? I'm not sure if you know this but the backend of PDM is moving to a system similar to Hatchling (the current way is executing a Python file).

2023-01-26 04:24 UTC, henryiii commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
The scikit-hep cookie provides 11 backends including flit-core and hatchling, and I've moved packaging to flit-core, and lots of other things to hatchling, and I can say that hatching's defaults are much nicer than flit-core's. Hatching uses `.gitignore` to decide what to put in the SDist. Flit-core basically tries to keep its hands off of adding defaults, so you have to configure everything manually. To make it even more confusing, if you use `flit` instead of a standard tool like `build`, it will switch to using VCS and those ignored files won't be added - meaning it is really easy to have a project that doesn't support build, including various GitHub Actions. Hatchling wins this by a ton.

TL;DR:

```
[tool.flit.sdist]
include = ["LICENSE*", "tests/", "docs/"]
exclude = ["docs/_build", "tests/manylinux/build-hello-world.sh", "tests/musllinux/build.sh", "tests/hello-world.c", "tests/__pycache__", "build/__pycache__"]
```

Vs.

Nothing. The default just works.

2023-01-26 19:51 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +| Feature                                                                | Setuptools            | Flit      | Hatch     | PDM |
Right now this needs to be updated but the rest of this page has been rewritten. I've refocused this page to be pure python. i'll add some discussion on another page that is about more complex builds and will link to ralf's guide there. the idea is that a beginner won't be worrying about C extensions (i think) so i want this page to be a bit more user friendly (but also accurate).

2023-01-30 19:23 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
> Hatching uses .gitignore to decide what to put in the SDist.

Oh hmm, I mentioned this at https://github.com/lululxvi/deepxde/pull/1117#issuecomment-1409048764 but basically, this sounds outright terrible. You do not want this, ***ever***.

- it is inconsistent with git, because git ignores your gitignore if you mark the file as tracked, this will surprise users who know how git works and make them go "what in G-d's name is hatchling doing" if they have a generic ignore pattern overridden by an important file checked into git
- it's badly implemented, git has `git check-ignore`, do not use external libraries for this, using the git tool will respect the files manually tracked by git
  -  but you have to use those external libraries either way, since the VCS scraper format is arbitrarily tied to the config settings format and you need it for the latter
- you should be doing what Meson does, and using export-ignore which is *intended* for applying to files tracked by git, and build artifacts that should also be shipped in an sdist should be known by the build mechanism itself and appended to sdist sources by said build mechanism, without any need for inclusion patterns.

For the vast majority of cases, what you actually want is "ship everything tracked by git, and maybe skip some handpicked things". Gitignore is fundamentally wrong *and* confusing, because using it fundamentally implies that you don't want those files tracked by git either, so git will stop you from tracking them in git.

The common, standard use case of .gitignore in a project with compiled extensions, for example, is to ignore `*.so` / `*.pyd` because... you don't want to accidentally check them into git, you just want to build them and distribute them in wheels. :facepalm: 

> To make it even more confusing, if you use `flit` instead of a standard tool like `build`, it will switch to using VCS and those ignored files won't be added - meaning it is really easy to have a project that doesn't support build, including various GitHub Actions.

This is a maintainer stubbornness bug, not a bug in the idea of using the VCS. Look at setuptools_scm for the correct way to do this, zero-config and all.

I wish flit would fix this, but I'm also fine with using flit to build wheels instead of `build`. I don't really see the point in setting up isolated build envs here. :shrug: Flit doesn't support plugins or build steps, so every single advantage of build isolation (including the one you're inevitably going to respond to this comment with) doesn't matter.

> As far as your comment about the build hook interface, do you have any suggestions? I'm not sure if you know this but the backend of PDM is moving to a system similar to Hatchling (the current way is executing a Python file).

The current way is not "executing a python file", the current way is "making use of setuptools". :)

I cannot find any discussion about changing this, but probably I'm looking in the wrong places.

...

IMHO there should be one clear way to do it, and that way should be plumbed in. For example, setuptools has Extension objects which are part of the setuptools configuration, and setuptools then figures out both how to build it and where to install it. Meson has an install routine attached to each artifact's base definition, letting you specify where inside site-packages it should get installed to -- and it exports a set of IDE introspection files which is also used by the build backend to map files to their install location, pyproject.toml doesn't know *anything* about what files are installed, not even via a tool section. Maturin has a directory of python sources and a single name for the (single) rust compiled extension, and then uses that name in combination with Cargo.toml to figure out how to build it and where to install it.

If there's some way to configure an extension purely via pyproject.toml, that's not necessarily a bad thing -- that's been floated as an idea for setuptools as well -- but you should not need to configure things in two or more places, so that should *only* be present in pyproject.toml.

As far as I can tell from the unreadable hatchling documentation carefully hidden away in the hatch documentation (yet again, hatchling cannot absolve itself of the need for good documentation by saying "it's a subpage of this tangential documentation site", also, this has got to be my 20th time reading it the last couple of months and I still cannot figure out how custom hooks are defined and used) there is an "artifacts" setting that has no purpose other than to break down that connection.

Does PDM intend to have any sort of unified conceptual framework tying together how everything works?

2023-01-30 20:29 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
>> Hatching uses .gitignore to decide what to put in the SDist.

> Oh hmm, I mentioned this at https://github.com/lululxvi/deepxde/pull/1117#issuecomment-1409048764 but basically, this sounds outright terrible. You do not want this, ever.

As I mentioned there it doesn't appear like you're appreciating the full landscape of build situations that led to that default. I'll re-post:

> using the ignore file actually leads to more consistent behavior because building from an actual Git checkout is in fact the least common scenario. If one is building from the source distribution for example by using pip or distribution configuration for a project as is common with Conda, Nix, etc. there is often no Git functionality, only the included ignore file.

You brought up `setuptools_scm` a few times, so I'm curious what @RonnyPfannschmidt thinks

> As far as I can tell from the unreadable hatchling documentation

I must say your lack of positivity is quite discouraging 😅

2023-01-30 20:47 UTC, RonnyPfannschmidt commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
Based on the horrors in the code base of setuptools_scm for differences between git versions im very thankful of the defaults hatch brings in

My personal experience is that neither git being remotely recent nor existent can be relied upon

For me hatch/hatchling and its defaults removed massive amounts of friction

2023-01-30 21:10 UTC, pradyunsg commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
May I suggest that that folks step away from this line of discussion for a bit?

As someone _just_ stepping in, I'll say that the discussion here is feeling quite polarised and combative; in the direction of arguing "my opinion is better than your opinion".

2023-01-30 21:11 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
Hi Colleagues 👋 

i am so so appreciative of all of the thoughts, direction and insight that i'm getting in this PR on python packaging tools. And i appreciate the passion and enthusiasm surrounding tools. 

With that said, I must interject here as I am worried that this conversation is becoming adversarial. As such it is redirecting us from our focus here of providing a truly useful resource that will help demystify the python packaging ecosystem! (particularly for beginners!).

such adversarial tone can really distract us from our important larger goal! but also i worry that others won't want to participate in these types of debates. and i NEED everyones review here!! 

I think that constructive feedback will be most valuable. If we can keep the discussions positive, it would help me greatly! so thank you in advance!! 👐 

I also think that we all have similar goals in that we want to see the python packaging environment become a more positive and easier to navigate place.
At the same time i want to ensure we are presenting the facts about each tool and that is where i need everyone's help! (thank you in advance AND for what you've already provided!)

i can happily look into the .gitignore issues and hatchling / pdm defaults as i'm testing various front and back ends!! but @henryiii i do hear your points about preferred tools. @ofek i do appreciate all of the work that you do on hatch and hatchling and in this community! 🙏  You are awesome!! @RonnyPfannschmidt hi! 👋 welcome to pyOpenSci. nice to "meet" you virtually.

 @eli-schwartz i'm can only imagine that working on meson is a huge effort! i'm enjoying using meson-python so far in my testing. And also appreciate the help with PDM addressing bugs! so thank you as well. 

we will find a path forward. I suspect we can do this via user-focused testing out all of the great packaging tools that everyone here is contributing to and developing (often in our spare free time!!) ! i think we all just share a goal of a streamlined user experience for packaging workflows. i'm confident we will get there, working together,  with time and patience!!

Let's pause on this conversation at this point as I focus on lots of updates to this section of the guide. i'll reach out and ping y'all with comments and questions as i have them. THANK YOU ALL for being here in the community! 

also dont hesitate to email (leah at pyopensci.org) me at any time with concerns!! i want this to be a great resource! i want us to help the community !!  ✨

2023-01-30 21:11 UTC, eli-schwartz commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
> If one is building from the source distribution for example by using pip or distribution configuration for a project as is common with Conda, Nix, etc. there is often no Git functionality, only the included ignore file.

If you pip install a source distribution or use conda, nix, etc. then you are building a *wheel* from an sdist, you *have* an sdist.

You therefore do not need the included ignore file, unless you use gitignore to define what goes into the wheel, not just what goes into the sdist? If so, how does that work? Any files that you want to gitignore and not distribute in the wheel, are already not-shipped in the sdist. So where did they come from? The build process that most projects don't need? Shouldn't those just avoid emitting non-distributed side effects into the same location as the distributed artifacts?

e.g.
- Meson: compiles all code into a private build directory, but then only the distributed artifacts are marked as installable, so only those are copied/json-tagged for export
- setuptools: has a `build/lib.linux-x86_64-cpython-310` and `build/temp.linux-x86_64-cpython-310` and sticks all non-distributable side effects into the latter, which do not get bundled into the wheel, but emits the final compiled `*.so` into the former

> I must say your lack of positivity is quite discouraging :sweat_smile:

Well, this isn't the first time hatchling has been criticized for the fact that the documentation it *does* have is difficult to discover, so I had been hoping this morning that it would finally be fixed, but no -- hatchling still points at hatch.pypa.io, and then I had to spend a while clicking around to find it, including a detour to the changelog file which is the only place that hatchling is mentioned, and another detour to a disclaimer that "Hatch" (no mention of hatchling) is "modern" specification-compliant and tools like tox and cibuildwheel work fine with it.

2023-01-30 21:14 UTC, pradyunsg commented on package-structure-code/python-package-build-tools.md
> +**Hatch** is the newer, more modern tool that supports customization of any part of your packaging steps.
May I suggest that that folks step away from this line of discussion for a bit?

As someone _just_ stepping in, I'll say that the discussion here is feeling quite polarised and combative; in the direction of arguing "my opinion is better than your opinion".

---

Statements about of how you feel negatively about some other tools' design choices/someone else's work tend to polarise discussions, which is counter-productive for what we should be trying to do here. It pushes away people from engaging by being emotionally taxing and aren't particularly valuable on their own either.

2023-01-30 21:48 UTC, lwasser commented
Hi colleagues. I truly value respectful, open conversation surrounding open source topics. Please know that I appreciate y'all.

However, it is also important that the discussions in our organization remain positive and supportive of each other's efforts. We can disagree, but there's no need to direct negative comments towards the work of others.  [Our code of conduct](https://www.pyopensci.org/governance/CODE_OF_CONDUCT.html#repeated-subtle-and-unintentional-micro-aggressions) highlights this. Particularly we talk about the importance of micro-agressions and avoiding using words that are combative / place others in a position that they feel uncomfortable.

Notably, @eli-schwartz, please consider this post a direct warning to not engage in such behavior going forward. I value your work and your thoughts and want your input. But its counter productive to our organization's shared goals to be adversarial. 

Thank y'all for understanding.

2023-02-16 20:14 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
It might take a while (so maybe not relevant for now), but I suppose poetry will evolve away from aggressively promoting strict semver. See python-poetry/poetry#7517 (still has to go through the review, so not yet certain)

2023-02-16 20:43 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +Dependency management, ✖,✖,✅, ✖
```suggestion
Dependency management, ✖,✖,✅,✅
```
I know of many users who use poetry only for dependency management (and not for building), i.e. as an alternative to pipenv or pip-tools.

2023-02-16 20:45 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +Version Control based versioning,✖,✅,✅,✖
Not sure if that counts, but there is a plugin for that purpose: https://github.com/mtkennerly/poetry-dynamic-versioning

2023-02-16 21:23 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency management, ✖,✖,✅, ✖
thank you. this was a mistake on my end - a typo! i do know that you have an excellent dependency management system in poetry! i've used it!

2023-02-16 21:24 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Version Control based versioning,✖,✅,✅,✖
it absolutely counts. I will add that to the notes. hatch_vcs is also a plugin. many thanks for calling this out @radoering

2023-02-16 21:24 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Version Control based versioning,✖,✅,✅,✖
@all-contributors please add @radoering for code, review

2023-02-16 21:26 UTC, lwasser commented
@all-contributors please add @radoering for code, review

2023-02-16 21:33 UTC, radoering commented
Just to avoid more off-topic in python-poetry/poetry#2740 I'm answering your questions here.

> Would you (or someone on the maintainer team here) be open to reviewing again and also answering a few questions that i have about poetry? I've played with all of these tools but it's hard to really understand all of the features and future plans without talking to maintainers. i'm happy to post questions wherever you'd prefer them to go as well - in an issue in our repo or here. many thanks!

I'm open to review. You can ping me here or as mentioned by Secrus ask your questions on our Discord server or in a new [discussion](https://github.com/python-poetry/poetry/discussions)

2023-02-16 21:47 UTC, lwasser commented
@radoering ok great - i'll ask questions in the discussion thread over in the poetry repo and will ping you once i have a cleaned up version that you can look at! many many thanks for the input and for being willing to answer questions! This is a work in progress and i'm trying to get as much input as possible to ensure it represents everyone's hard work on tooling in the community!

2023-02-16 22:51 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## PDM
ok perfect - i've updated this in the table! thank you

2023-02-16 23:22 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +1. Poetry pins dependencies using `^`. This `^` symbol means that there is an "upper bound" to the dependency. Thus poetry will bump a dependency version to a new major version.  Thus if your package
working with the maintainers [here](https://github.com/python-poetry/poetry/discussions/7525)  to clarify. it sounds like there is a bit more flexibility with poetry upper bounds pinning than i had thought! and that they are working towards pep 621 support.

2023-02-16 23:23 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## Python packaging tools summary
this has been implemented / updated!

2023-02-16 23:35 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +It's dependency management decisions have caused breaking changes in several large
@radoering thank you for this and i really appreciate the discussion we are having over in the poetry discussion thread. i think this strict semver is the real sticking point with poetry right now. Poetry is widely used in the community AFAIK and also your documentation is i think one of the best examples i've seen so far (especially for beginners!).  

just so you know i have relaxed my language around poetry!

2023-02-16 23:36 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +There are a suite of build tools that you can use to create your Python
fixed!! so sorry i got testy on some of your comments the other week, @NickleDave i needed to take a breather from this PR i think but am working through everything now with a level head (and some hot tea!)!! 🫖

2023-02-16 23:39 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +This pages will help you understand the two core packaging files
fixed!

2023-02-16 23:41 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +# What is a SDist and Wheel? About Python Package Distribution Files
what about 

# The Python Package Source and Wheel Distributions

??

2023-02-16 23:43 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +To begin, it's important to understand the two "types" of
what about (a lot of this has been rewritten via comments so i can't commit here but can work locally to adapt:

It's important to understand the two "types" of distribution files. You can 
think about files as either source or binary:

2023-02-16 23:46 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +SDist, short for **S**ource **D**istribution file is a packaged file in `.tar.gz`
how about:

### What is a source distribution (SDist)?

**S**ource **D**istributions (referred to as SDist) is a set of files saves as 
a `.tar.gz` archive (often called a "tarball"). The SDist has all of the files 
needed to build your
package. As the name implies, a SDIST contains the source code; it has not been 
built or compiled in any way. Thus, when a user installs your source 
distribution using pip, pip needs to run a build step first.

2023-02-16 23:47 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +format. Thus, anyone using this file, will have to build the files first before
does the rewording proposed above sound better / more clear?

2023-02-16 23:49 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +When you make a release on GitHub, it creates a SDist file (`.tar.gz`) that
ok here's where i am with this - better?
*********
When you make a release on GitHub, it creates a git archive that contains all 
of the files in your GitHub repository. While these files are similar to an 
SDist, these two archives are not the same. The SDist contains a few other 
items including a metadata directory and if you use `setuptools_scm` or `hatch_vcs` 
the SDist will also contain a `_version.py` file.

2023-02-16 23:50 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +is a pre-build, ready-to-install format.
fixed!

2023-02-16 23:52 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +A wheel or `.whl` file, is a zipped file that has
fixed!

2023-02-16 23:54 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +the extension `.whl`. The wheel does not contain any of your packages
yes - so that was what i was getting at. if you look at the wheel rather than a .toml file and setup files you have the metadata, etc... this is better language - fixed!

2023-02-16 23:55 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +needs a **setup.py** file to support a more complex built.
fixed! i need to find a better way to merge these small commits before the pr gets too complex. having to to it manually  - making a note to myself to implement that FIRST on our next round

2023-02-16 23:58 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +work about malicious code injections when it is installed.
great point - ok so the thing i shared in slack i think isn't the right one. And i'm also a bit confused about this now after talking to a. bunch of folks. Maybe we can revisit when i create a new fresh PR on top of this branch? i've left a TODO note in this page to do this so we don't collectively forget to revisit!  so i'm going to resolve this with the intent of revisiting once we have a cleaner version of this content!

2023-02-16 23:58 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +**Setuptools** is the "OG" tool that has been used for Python packaging for many years.
ive called this "mature" in the latest very much rewritten version !! but everyone does love an OG, right? 🙃

2023-02-17 00:02 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +package's **SDist** and *Wheel* distributions.
fixed!

2023-02-17 00:04 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +* Dependency "pinning": No (but this feature may come in the future)
ok i think i've fixed throughout on this page with a find and replace. i don't see it uppercased on this page but perhaps i fixed it previously after seeing this comment ? many thanks!

2023-02-17 00:05 UTC, lwasser commented on package-structure-code/intro.md
> +community.  Our goal is to help standardize packaging across this ecosystem.
many thanks!! very helpful. it's funny how so many of us just look at other packages that we respect and follow their lead. for me that was geopandas!

2023-02-17 00:10 UTC, lwasser commented on package-structure-code/intro.md
> +standards, based upon the commonly used approaches in the scientific Python
@henryiii , @ofek thank you for this... i wondered if you can clarify this as i'm working on the poetry part of this guide today (and am getting some great feedback from the maintainers as well.

> they (Poetry) assume metadata can't change between wheels of the same version, which is incorrect

do you mean that a wheel for the same version of a package but that would be custom built for different say operating systems or hardware in an HPC environment may have different metadata needs?

2023-02-17 00:16 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +extensions), we suggest you consider using **meson.build** or **scikit-build**.
ok got it -- i'm going to resolve this and hopefully the next round of edits is more clear / accurate!

2023-02-17 00:17 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Of the tools listed on this page, two of them support
fixed!! we now have a nice table of features. many thanks.

2023-02-17 00:19 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +| Build backend                                                          | setuptools.build_meta | flit_core | hatchling |  pdm-pep517   |
perfect - 
Notes: PDM did not work with meson-python out of the box BUT it seems to now after a few minor bug fixes!! 🎉 i have not tried scikit-build yet. 

@ofek i'm happy to update our guide as features are added to hatch! i see this as a living document that will evolve with the ecosystem!

2023-02-17 00:25 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +| Has built in dependency management                                     | no                    | no        | no (future feature)       | yes |
fixed!

2023-02-17 00:26 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +| Supports custom build steps (before creating wheel)                    | yes                   | no        | yes       | no  |
i think you are right after looking at other comments here! it think i've fixed this now via a big reorg!!.

2023-02-17 00:29 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +There are no downsides to using Flit. If you have a simple build, it might be
@henryiii so i think (correct me if i'm wrongly assuming) that you are referring to flit not using .gitignore to ignore certain files when creating SDist? (is that correct?). would this be akin to using a MANIFEST.in file with setuptools? or can you clarify so i can capture this in our guide?

2023-02-17 00:30 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. This makes the package size slightly smaller.
ok got it. i'm going to rewrite this entire page next... so i'll keep this open and will try to capture this in my next attempt!

2023-02-17 00:30 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +There are some benefits to the scientific community in using the flat layout.
got it - am going to capture in a rewrite. i understand now the benefits of src/ after a bunch of experimentation!

2023-02-17 00:32 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* CONTRIBUTING.md
i've been adding CONTRIBUTING to docs as well as an include. i wonder if a "hidden" dir will impact include files?

2023-02-21 20:41 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +layout such as tests being included with the package when they are installed) to
Ok after a LOT of thought about this i'm adding src first.. and suggesting it for newbies (not being clear that we do not require it for our reviews!! i'll create a new PR with the new page. and i may pull out the pyproject.toml as a separate file?

i think the tests being included or not is really not related to the structure because i mean if you default to using setuptools is includes EVERYTHING and i mean everything regardless of where it is (without a MANIFEST file). so that is a separate topic related to how tools are configured and how devs configure things too as you point out. 

i do think this topic is still a bit bike shedding like BUT i also see the benefits to beginners and i do NOT want to confuse people with a debate or a choice up front.  i hope this new version will provide a nice middle group that considers all points of view but advocates for an approach that i do think is more beginer friendly. (our target audience!) i have sourmash on the list of packages that use src/ please send others my way to add to the guide. i just posted on social about it too (2pm post)

2023-02-21 20:42 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +for these tools is not worth the maintenance investment. To avoid dividing the
i think there is a divide already TBH. i wish there wasn't. but in the end i think that most people will use the approach that we suggest. just like they WANT to. look to pypa. i think that you will like the new version of this document but definitely would love to not continue to debate this topic too!! :) 

i think users are put off by such debates. but i also think we have a nice middle ground with the new version of this file!! will see what you think when i push a new pr.

2023-02-21 22:35 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* Often the `tests/` directory also lives within that same `package-name` directory.
i've since realized that really the tests location is not related to the layout style! maybe we have a section devoted on where to place tests and things to consider? what do you think? 

because the things to consider would be data and where data live and package size. we could then link to the tests page (which doesn't exist yet).

2023-02-21 22:42 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +your package will be "found" by build back-ends automagically.
yes i did have issues with configuring src/ with setuptools + build. but i think in the end if we are recommending src/ to newcomer and they use a modern tool this really wont' be an issue. setuptools has a lot of really bad defaults is what i learned the hard way. i just removed this from the page. i'm going to resolve these issues as i go @NickleDave but you will have another chance to review a shiny new PR with this content just like we did with the docs section!

2023-02-21 22:43 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* You can directly install the package directly from the root directory.
yes i think the import directly is engrained in many's workflows. but as i mentioned above i think that this - if designed for beginners we can just teach new workflows. and it's ok. we aren't forcing anyone to move to src/ if they don't want to. but what i do like is we are aligning with PyPA and the work pradyun is doing (not pinging them here so avoid 8000 more notififcations in their email!)

2023-02-21 22:44 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* This structure is simpler to setup to support packaging compared to the `src/`
fixed!

2023-02-21 22:46 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +be implemented using a `src/` layout too!)
i've removed most of the pro cons. i have realized it's not worth comparing them in this way. somethings that are harder with setuptools are a bit harder. lots of people (most in fact based on numbers) used setuptools BUT each tool is unique in what it does and doesn't do by default. and tests really are a separate topic so i think the new version of this is better.

2023-02-21 22:47 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +`src/package-name` directory, `tests/` are in the root and with docs/
thanks! fixed!

2023-02-21 22:49 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +   * Tools like build won't automatically find the package directory if it's
understood. i really didn't understand setuptools / build and how they worked together and with pip. so it was NOT clear to me that setuptools is the backend and build is the front end? But i DID have to configure things when i used setuptools/build to build my package! regardless i have removed this as i've removed cons altogether now - because some of this was my lack of understanding of various tools and issues represented in text! i think the current version is better / more clear but look forward to more feedback!

2023-02-21 22:50 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +for the `src/` directory when installing the package
yea - i think it took me actually running into this with my package to understand. i do now and THINK i've clarified in the document. but we shall see when i open this up for another review. many thanks!
it has been a lot of work to really understand the entire ecosystem and peps beyond just using stuff to build a package which is what i've been doing for many years without understanding the ecosystem properly! i think i have a much better understanding now which is reflected in the current draft!

2023-02-21 22:52 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that needs to be compiled is stored in `src/`.
yea... ok i agree. So what i've done in the rewrite is simple state - look it's too hard to ask everyone to move to source. it would be a resource deficit if we did that! BUT we can ask newcomers to consider using src/ for various reasons.

That way i'm avoiding any discussion of pros and cons and focusing on why src might be better for newcomers but also acknowledging that many in the community don't use src for very pragmatic reasons .

2023-02-21 22:57 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +1. Because setup.py has a mixture of code and metadata, it opens the user to a potential bad code injection on their computer when the package is installed.
ok so .. this is the one issue i'm still a bit unclear on.. but eli has a really  detailed response above.... 

Is the takeaway here that setup.py is really problematic because it requires a second run during build because first you need to extract metadata to know what the package requires and then a second to build hte package? is that the real issue?

Because most people are likely installing wheels which if i read everything above correctly, this means that in most cases code is NOT being run upon install ever. 

is that a clear way to simply describe why moving away from setup.py is a good thing? i get the SDist will always be arbitrary code as it's just a bunch of files.  many thanks

2023-02-21 22:59 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +The [TOML (Tom's Obvious, Minimal Language) format](https://toml.io/en/), is an easy-to-read structure that is founded on key: value pairs.
fixed!

2023-02-21 23:03 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +
@henryiii can you please clarify this? i do agree that pep numbers are confusing! i always mix up the pep numbers 

at the same time - [this page for example refers and links to PEP 518](https://packaging.python.org/en/latest/specifications/declaring-build-dependencies/) so i'm just confused about what to link to / refer to where

2023-02-21 23:05 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +[PEP518 describes the move away from setup.py to the pyproject.toml file.](https://peps.python.org/pep-0518/)
i agree that we need a better intro... but now i'm confused about linking to peps and such based on henry's comment above. does this make sense to you by chance @NickleDave ? and would you like to help with the intro here i can push a new PR with cleaned up everything i think soonish maybe this week even?

2023-02-21 23:09 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +a **proproject.toml** file sometimes combined with a **setup.cfg** file.
ok... this makes sense. i mentioned the two together because i actually found a handful of packages using this combo -- see

https://github.com/fatiando/pooch for a while i was really looking at fatiando for best practices. essentially it's really hard to find the "right" best practices out there (or to know who is using an approach that is considered best practice vs not) .

so maybe i'll say something like... setup.cfg can be found in the ecosystem due to <some text here about how it's being deprecated but not everyone knows that or something ike that??> but the ecosystem is moving away from it in favor of using pyproject.toml...?

2023-02-21 23:13 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +where a build is particularly complex, a **setup.py** file may still be required.
this is helpful. i think to clarify here @NickleDave i'll add a little breakout about what we mean by complex builds. hopefully that will help our readers better understand. i thijnk most of our readers wont be in that complex build space and we can then link to Ralf's guidebook for them. i'm creating a page for that. it will just introduce complex builds and say - go to ralf's guide for more on this!

2023-02-21 23:51 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +## Core scientific Python packages that use the flat layout
i've added a table of src/ layouts. included sourmash and another climate data. do you have others you can share maybe via slack as there are too many comments here for me to find at this point.. github is literally hiding them in the file views from me. 😆

2023-02-22 00:59 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +* PDM
so i've included a few other things @stefanv 

```
* [Build your packages (create the SDist and Wheel distributions](python-package-distribution-files-sdist-wheel)
* Installing your package in a development mode (so it updates when you update your code)
* Publishing to PyPI
* Running tests
* Building documentation
* Managing an environment or multiple environments in which you need to run tests and develop your package
```

These front end tools have other bells and whistles. i think that the major benefit here is there is less cognitive load if you have similar commands. sure you can use twine to publish but flit build, flit publish is going to be easier to remember especially for a beginner. 

Also i'm learning that tools like hatch have other bells such as a nox like tool so you could skip the whole nox / makefile part for pure python builds. PDM and hatch offer levels of environment management with matrix testing offered by hatch (i hope i'm getting these all right). So i think it's worth users understanding what tools provide. 

Also version bumping is slightly different across tools! anyway i'll push a new version of this all with a fancy table for all to look at and see if i've gotten closer to getting this all right!

2023-02-22 01:01 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +* PDM
Here's a lil preview just in case you wanna see where this is goin too! i've re-added poetry as it does sound like they may be moving towards allowing users to forgot the ^ pinning too! and will be closer to pyproject.toml dep declaration standards in the next release 🎉 

<img width="704" alt="Screen Shot 2023-02-21 at 6 00 11 PM" src="https://user-images.githubusercontent.com/7649194/220493600-dc60c298-4686-4e5a-845f-7229210013cc.png">
<img width="708" alt="Screen Shot 2023-02-21 at 6 00 04 PM" src="https://user-images.githubusercontent.com/7649194/220493601-63da4230-0320-4168-87ff-598f45393d43.png">

2023-02-22 01:31 UTC, lwasser commented
@all-contributors please add @astrojuanlu for code, design, review

2023-02-22 01:55 UTC, lwasser commented
@all-contributors please add @eli-schwartz  for code, design, review

2023-02-22 01:55 UTC, lwasser commented
@all-contributors please add @rgommers for code, design, review

2023-02-22 01:57 UTC, lwasser commented
@all-contributors please add @ofek for code, design, review

2023-02-22 16:33 UTC, lwasser commented
hey y'all - i am going to hide comments that i've addressed in the docs because there are so many i keep losing track of what i've addressed. please do not take offense to your comment being hidden - this just means i've addressed it in the text.  it's just a lot of information and I want to make sure that i have addressed EVERYONE's feedback. many thanks

2023-03-22 18:36 UTC, lwasser commented
y'all - closing this PR - the most recent one with ALL of the changes from this PR was just merged!! #55 
Note - it's inevitable i made more mistakes given the volume of feedback and comments. as such anyone is welcome to open an issue here at any time with suggestions... it should be live in 5-10 minutes. so many thanks for ALL of the feedback and input here y'all!! both pr's have over 400 comments  made by dozens of community members! pyOpenSci is and I am so appreciative!

2023-03-22 18:36 UTC, closed without merging

2023-03-23 17:27 UTC, lwasser commented
All - last ping from me here on this CLOSED pr. I've had this zenodo file open for a while and just did a bit update with everyone's names who has participated in the reviews and contributed to our work across both this PR and the other that was just merged yesterday! 

Please review and add / edit  the zenodo file in this pr if you'd like your information displayed in the guidebook citation differently: 

https://github.com/pyOpenSci/python-package-guide/pull/20

If i missed you (i'm very sorry if that happened but i hope it doesn't!) please either comment on the pr with your info or add yourself via an inline comment. i don't want to miss anyone. 

I will push a new release of this guide with the updated zenodo file next Tuesday April 28th. you can still add your name or edit your details after that time but only as a pull request given the open one will be merged!! Many thanks!!

2023-03-27 22:04 UTC, lwasser commented
hi y'all - one last reminder - i will merge [this pr ](https://github.com/pyOpenSci/python-package-guide/pull/20) with the zenodo doi information tomorrow (tuesday mar 28) and create a release of this repo at that time. feel free to update / comment on the pr that is open if any of your information if missing. many thanks y'all for the comments already there (i just committed them!)