docs: translate to Spanish intro.md of package-structure-code
pyOpenSci/python-package-guide pull request #335
Opened 2024-07-14 18:03 UTC by RobPasMue

Related to #313

2024-09-14 18:59 UTC, flpm requested changes
One more down! Thanks @RobPasMue for helping with this.

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"¿Distribución del código fuente, distribución plana y dónde deben vivir las carpetas de tests? "
```suggestion
"¿Distribución con estructura 'src', distribución plana y dónde deben vivir las carpetas de tests? "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"la filtración en PyPI como los metadatos que un instalador de paquetes necesita para "
```suggestion
"los filtros en PyPI como los metadatos que un instalador de paquetes necesita para "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Si tiene un paquete de Python puro, es un proceso sencillo publicar en PyPI y luego en "
```suggestion
"Si tiene un paquete de Python puro, publicar en PyPI y luego en "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"un canal de Conda como conda-forge. Aprenda más aquí."
```suggestion
"un canal de Conda como conda-forge es un proceso sencillo. Aprenda más aquí."
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"mínimos del editor](https://www.pyopensci.org/software-"
```suggestion
"mínimas del editor](https://www.pyopensci.org/software-"
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Proporcionamos una descripción general de las opciones disponibles para empaquetar su herramienta."
```suggestion
"Proporcionamos una descripción general de las opciones disponibles para empaquetar su código."
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"como una herramienta de Python puro y evolucionar hacia una herramienta que requiere capas adicionales "
```suggestion
"como código en Python puro y evolucionar hacia un código con capas adicionales "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Para apoyar los muchos usos diferentes de Python, hay muchas formas de crear un paquete de Python. "
```suggestion
"Para satisfacer todos los usos posibles del lenguaje, hay muchas formas de crear un paquete de Python. "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Un objetivo compartido de estandarizar los enfoques de empaquetado en todo este ecosistema de Python (científico)."
```suggestion
"Un objetivo compartido de estandarizar los enfoques de empaquetado en todo el ecosistema de Python científico."
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"y aceptados [comunidad de Python](https://packaging.python.org/en/latest/) y "
```suggestion
"y aceptadas [comunidad de Python](https://packaging.python.org/en/latest/) y "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Aquí, también intentamos alinear nuestras sugerencias con los más actuales "
```suggestion
"Aquí, también intentamos alinear nuestras sugerencias con las prácticas más actuales "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"Las sugerencias para la distribución de paquetes en esta sección se hacen con la intención de ser útiles; "
```suggestion
"Las sugerencias para la distribución de paquetes en esta sección se hacen con la intención de ayudarle; "
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"de Python de pyOpenSci!"
```suggestion
"que aplica pyOpenSci!"
```

2024-09-14 18:59 UTC, flpm commented on locales/es/LC_MESSAGES/package-structure-code.po
> +"¡Consulte nuestra [página de alcance de paquete](https://www.pyopensci.org"
```suggestion
"¡Consulte nuestra [página con el scope que cubre PyOpenSci](https://www.pyopensci.org"
```

2024-09-16 07:47 UTC, RobPasMue commented
Thank you once again for reviewing @flpm!

2024-09-17 17:36 UTC, flpm approved these changes
LGTM

2024-09-17 17:37 UTC, merged