(Review 2) Packaging section - part 2 (Reviews Welcome)
pyOpenSci/python-package-guide pull request #55
Opened 2023-02-22 20:49 UTC by lwasser

This PR builds on top of ALL of the feedback here: 
https://github.com/pyOpenSci/python-package-guide/pull/23 

Im hoping that we have made some good progress. 
a few. highlights:

✅ we are suggesting (but NOT requiring) src/ layout for beginners as it will remove some of the pain points associated with testing but we also review flat layouts as the most common layout in the ecosystem. i hope this is a win win. 
✅ i've added poetry and updated the table of front end tools! 
✅ i've tried to avoid being bogged down in details of each tool - users just want to know what to use and why. we can teach them more in tutorials as they are created.

2023-02-27 17:22 UTC, astrojuanlu commented
Thanks a lot @lwasser! Is there a way to see a rendered version of the site?

2023-02-27 17:48 UTC, lwasser commented
@astrojuanlu i know that would be great - right? we have a CI build in our other guide that i think i can try to port over here today or tomorrow.

2023-02-27 18:21 UTC, lwasser commented
@astrojuanlu can you see if this works for you - circle ci was setup it just wasnt running on branches / prs! https://app.circleci.com/pipelines/github/pyOpenSci/python-package-guide/131/workflows/1d0c1ca3-f7ff-4b61-a171-54d8409954b0/jobs/107/artifacts you should now be able to click on the circle CI build and go to artifacts to see the book as rendered.

2023-02-27 18:45 UTC, lwasser commented
perfect! thanks for providing the specific link to the packaging section here and for the nudge to fix CI (i forgot i had added this and never got it working! )!

2023-02-27 18:52 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* [awkward](https://github.com/scikit-hep/awkward)
add: https://github.com/poliastro/poliastro/

2023-02-27 23:02 UTC, lwasser commented
latest version of our packaging diagram - for reference (not in this PR as i'm still editing it)
Feedback is welcome on this too as you read through the content!

<img width="1004" alt="Screen Shot 2023-02-27 at 4 01 38 PM" src="https://user-images.githubusercontent.com/7649194/221709002-1a2496f3-a3b4-4fde-ba3e-cc56a19b0af3.png">

2023-02-28 17:45 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Use Other Build Backends,✖ , ✖,✅  ,✖
```suggestion
Default Build Back-end, Flit-core, hatchling, PDM, Poetry-core
Use Other Build Backends,✖ , ✖,✅  ,✖
```

2023-03-02 21:39 UTC, rgommers commented
Nice diagram @lwasser. I like both the structure and the styling. There are a few issues with choices that I see:

- In the "many C/C++ extensions" case, front-end choices:
  - `build` shouldn't be there. It's a universal front-end for building sdists and wheels only, not for development. So it doesn't really fit in with these development workflow frontends. If you want to mention it at all, say it's _the_ tool to use to do releases (sdist, wheels) - and nothing else.
  - DevPy isn't quite ready yet, it has a number of rough edges and isn't even on PyPI yet. So I'd leave that out and only revisit if it's adopted by some projects and ready for general consumption.
  - Poetry should be there as the one alternative to PDM, since it can use arbitrary backends. I think it always can be put side-by-side with PDM.
- For both cases with C/C++ extensions, back-end choices: `hatchling` should not be there, it is limited to pure Python projects only. It's already the default there for pure Python (Hatch includes hatchling as the build backend). So `hatchling` should not appear separately in the diagram.

2023-03-03 01:58 UTC, lwasser commented
Thank you @rgommers !! Ok if you don't mind i have a few points of clarification! Please know that i'm not pushing back rather still fighting a bit with conflicting information in my brain! I just want to get this right! 

> * In the "many C/C++ extensions" case, front-end choices:
>   
>   * `build` shouldn't be there. It's a universal front-end for building sdists and wheels only, not for development. So it doesn't really fit in with these development workflow frontends. If you want to mention it at all, say it's _the_ tool to use to do releases (sdist, wheels) - and nothing else.

OK got it. I played with Meson-Python and it seemed like I needed to use Build to build the SDIST and WHEELS. [Example repo is here. ](https://github.com/pyOpenSci/examplePy/tree/main/example5_meson) which i think is what you're telling me.  

i'm trying to figure out how to talk about Build. it's not a development workflow front end. But you need something when  building a package's SDist and Wheel with a tool like meson-python. Would pulling Build out of the bubble and adding a text note about using it with tools like meson-python and setuptools perhaps work? 

Id love any insight into how help people understand how build fits into this ecosystem. For me i've been confused about build for a while (until i started working on this guide actually) but i've used it for a while too! 🙃 so i want to somehow include it in a way that makes sense. thoughts?

>   * DevPy isn't quite ready yet, it has a number of rough edges and isn't even on PyPI yet. So I'd leave that out and only revisit if it's adopted by some projects and ready for general consumption.

NO PROBLEM. I'll remove it!

>   * Poetry should be there as the one alternative to PDM, since it can use arbitrary backends. I think it always can be put side-by-side with PDM.

OK question about Poetry.  [i actually did a bit of research into it by asking the devs. ](https://github.com/python-poetry/poetry/discussions/7525). It seems like Poetry DOES support non pure python builds but it's undocumented / unsupported [and they are hesitant to document it at all. ](https://github.com/python-poetry/poetry/issues/2740) I also asked about supporting other build backends and it seems as if Poetry is not able to do that either.

I'm worried about suggesting a tool for non pure python builds that doesn't document its support of said builds. 

> * For both cases with C/C++ extensions, back-end choices: `hatchling` should not be there, it is limited to pure Python projects only. It's already the default there for pure Python (Hatch includes hatchling as the build backend). So `hatchling` should not appear separately in the diagram.

i'm happy to remove hatchling. i'm still a bit confused by hatchling as it is my understanding that a dev can write plugins for it that would support more complex builds. But many (if not most?) don't want to do that. maybe my understanding is wrong. And as such, until hatch supports meson-python there is no real support for complex builds. Hatch does plan to support other back ends in the future but certainly doesn't now. 

Many thanks, Ralf. i keep getting this wrong but hopefully i'm atleast moving in the right direction!!

2023-03-03 10:02 UTC, rgommers commented
> i'm trying to figure out how to talk about Build. it's not a development workflow front end. But you need something when building a package's SDist and Wheel with a tool like meson-python. Would pulling Build out of the bubble and adding a text note about using it with tools like meson-python and setuptools perhaps work?

Yes, that sounds like a good idea. 

> I'd love any insight into how help people understand how build fits into this ecosystem. 

My mental model is that I clearly separate between "working on a package" and "releasing a package". Your whole diagram is about the former. `build` is about the latter (side note: it has about the least distinctive name possible, so I usually write `pypa/build` to refer to it).

It'd be useful to have a short separate section about releasing, which is where it should show up. I'd say something about best practice being to create all your release artifacts in a CI job. There, `cibuildwheel` will be using `pypa/build` under the hood to produce wheels, and you also need to produce an sdist with `python -m build --sdist`.

> I'm worried about suggesting a tool for non pure python builds that doesn't document its support of said builds.

This makes sense. Seems like you did your homework about Poetry, so please ignore my comment. I remembered it came up elsewhere and the Poetry devs said "but we can do it, this is how ...". But if it's not documented, then +1 for treating it like it isn't supported. That seems like a good criterion for everything in the diagram, for a tool/feature to be included: is released on PyPI, has decent documentation, and is adopted successfully by at least a few projects.

> i'm still a bit confused by hatchling as it is my understanding that a dev can write plugins for it that would support more complex builds.

This is a plan, it does not exist aside from a design sketch (see [extensionlib docs](https://ofek.dev/extensionlib/history/)). And imho it's not a very good plan at that, but that's besides the point and I could be wrong. Despite the large amount of talking about it, it's only an idea at this point which needs to be implemented and then proven to be useful in practice.

2023-03-12 19:15 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
That reads as if poetry would only support dependencies with upper bounds and PDM would only support dependencies without upper bounds. But that's only the default when using the cli. You can specify upper bounds and open bounds in both tools. Further, the difference is not the "approach to locking files" (in the lock file there is only one specific version, at least per platform, python version, ...), but the default dependency constraint when using the cli to add a dependency.

2023-03-12 19:15 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
In theory that might be true. In practice, there are things that are difficult to mention in a guide (and may change over time) but are often more relevant. E.g. regarding dependency locking there will be special and edge cases that are only supported by one or the other.

2023-03-12 19:15 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +* Poetry pins dependencies using an "upper bound" limit specified with the `^` symbol. See breakout below for more regarding why this is potentially problematic.
```suggestion
* Poetry pins dependencies using an "upper bound" limit specified with the `^` symbol by default. See breakout below for more regarding why this is potentially problematic.
```

2023-03-12 19:15 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +* Doesn't support version control based versioning
```suggestion
* Doesn't support version control based versioning without a plugin
```

?

2023-03-12 19:15 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +Poetry pins dependencies using `^`. This `^` symbol means that there is
```suggestion
Poetry pins dependencies using `^` by default. This `^` symbol means that there is
```

2023-03-13 02:44 UTC, NickleDave requested changes
This has come a long way, you're almost there! I mostly pointed out some minor nits and made some rephrasing suggestions, hope it helps

2023-03-13 02:44 UTC, NickleDave commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
```suggestion
* Using a `src/package-name` layout in combination with a separate `tests/` directory in the root of the project will usually result in a smaller source distribution or wheel, since most packaging tools won't include files outside of `src/` (with the exception of flit). This can make install times faster (especially if you have large amounts of data for tests in your tests folder) and minimize the costs you impose on the Python Package Index (PyPI). Most packaging tools have setting that allow you to explicitly include tests even if you have them in a separate directory in the root of your project. Some Python libraries choose to do this, so that downstream package managers can test whether their own builds from the source distribution are working. This situation arises because [one function of PyPI is to serve as a single source of truth for many downstream package managers, like those on operating systems](https://pypackaging-native.github.io/meta-topics/purposes_of_pypi/). If you are not developing a library that many different package managers build from your source distribution, then you may want to exclude your test suite to minimize install times and PyPI costs. If you want to provide users a way to test that installation worked, consider developing a lightweight alternative, e.g., calling the help or version commands of a command line interface.
```

Trying to rephrase this to emphasize the good part, it's a bit tricky cuz there's multiple interacting things here (src/ + tests/ + which packaging tool you use)

2023-03-13 15:40 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +# Python Package Build Tools
@ofek @frostming i wondered if you both were open to reviewing this page to ensure that i captured Hatch / Hatchling and PDM to your liking as well? many thanks in advance. i'm going to be reworking these pages this week and will potentially merge by friday or early next week if you flag a lot of issues that i need to address.

2023-03-13 21:07 UTC, lwasser commented on index.md
> +All of the modern tools discussed in this guide will help you build an efficient packaging workflow. This section helps you select the one that will work best for you.
```suggestion
All of the modern tools discussed in this guide will help you build an efficient packaging workflow. This section helps you select the tool that will work best for you.
```

2023-03-13 21:08 UTC, lwasser commented on package-structure-code/complex-python-package-builds.md
> +created by Ralf Gommers on Python packaging.](https://pypackaging-native.github.io/)
good point. i saw that extension guide - but it's kind of old - i can't tell when the actual text was updated. the RTD copyright is 2014 but the last commit is 2021. did you notice that? i mean if that is maintained it would be wonderful. we could provide it as a resource maybe?

2023-03-13 21:14 UTC, lwasser commented on package-structure-code/complex-python-package-builds.md
> +2. **Python packages with non-Python extensions:** These packages have additional components called extensions written in other languages (such as `C` or `C++`). If you have a package with non-python
ok questions back at you. 

for style do we want to bold or code highlight language names? i feel like it makes sense to do one of the two. but i know i haven't been consistent. style check - thoughts?

on the other idea i'm not exactly sure how to delineate but we could try your approach and see what folks say. i think generally it is the diff between a few extensions and wrapping an entire API in another language or multiple languages type of deal?

2023-03-13 21:16 UTC, lwasser commented on package-structure-code/intro.md
> +In general these are basic items that should be in any open software repository.
sorry david can you please clarify what you mean here? i'm happy to move the text. i wanted to get at the idea of these are good checks / things to have in any code repo but we use them in pyOpenSci kind of thing...

2023-03-13 21:18 UTC, lwasser commented on package-structure-code/intro.md
> +
```suggestion
The flexibility of the Python programming language lends itself to a diverse
range of tool options for creating a Python package. Python is so flexible that
it is one of the few languages that can be used to wrap around other languages. The ability of Python to wrap other languages one the reasons why you will often hear Python described as a ["glue" language](https://numpy.org/doc/stable/user/c-info.python-as-glue.html)"

```

2023-03-13 21:18 UTC, lwasser commented on package-structure-code/intro.md
> +
added below!

2023-03-13 21:28 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
thanks @radoering can you please help me clarify this so i get the text right? I haven't tried to modify the locking behavior in either tool. but i DID notice that each tool defaulted to poetry:upper bounder; PDM : open bounds

  [it was my understanding that this open bounds might be a future option in poetry but not currently](https://github.com/python-poetry/poetry/discussions/7525#discussioncomment-5001542)?  But the comment says that poetry "supports" other modifiers. but i didn't understand how. Does that mean a user needs to remove the upper bound specifier manually in the lock file or is there indeed a setting that will just turn it off?

Similarly i didn't see a way for PDM to support upper bound only open bounds. can you help me understand how it supports that?

Also are ou able to help me understand the different in the default dependency constraint? do you mean that one defaults to upper bound locking and the other to open bound locking?

Many thanks!! i think i can rewrite if i understand

1. how to use poetry and avoid upper bound locking 
2. if the real only different is the default way of locking (upper bound vs not upper bound)

2023-03-13 21:31 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
got it. are you able to help me with something that is concrete that i could write with confidence? i think you are saying there ARE some potential nuances in how the dependency locking works between the two tools. Do you think someone who is newer to python packaging might need that type of support early on? or is this a more advanced feature to consider? this guide is for beginners. but again i do want to get this right if it's not too edge case focused! i'm happy to add a note that in some cases the way dependency locking happens differs between the two tools - but i think that could be confusing to users if they don't know what to do with that information. (if that makes sense?)

2023-03-13 21:31 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## Hatch
@ofek this is the discussion of hatch :)

2023-03-13 21:32 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +is currently undocumented. Thus we don't recommend it for more complex builds.
```suggestion
is currently undocumented. Thus, we don't recommend it for more complex builds.
```

2023-03-13 21:36 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +* Doesn't support version control based versioning
oh right - actually i should update this as Hatch is the same. there is a vcs plugin. i'll accept this and actually remove that and mention the plugin. you had told me about this I just i think lost it in all of the comments in that other review. thanks so much @radoering !!

2023-03-13 21:38 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +PyPI SDist and Wheel. The SDist (Source Distribution) contains the raw source
ok i didn't know that about the capitalization!

2023-03-13 21:38 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +* [awkward](https://github.com/scikit-hep/awkward)
```suggestion
* [awkward](https://github.com/scikit-hep/awkward)
* [poliastro](https://github.com/poliastro/poliastro/)
```

2023-03-13 21:42 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
i like this but have a question and then a concern.

1. is it really true that install times will be faster? i don't understand how having a few .py test files would actually make things faster. i am asking not because i think the addition is a bad one but because i want to really stick to facts. If the real reason is the data can be large (btw i've always included data in a separate folder outside of tests as i can use it in tutorials too for docs) maybe we have a section on that explicitly as an issue. i'm just not full sure about the install time being a significant reason to put tests outside of src.  we need to stick to facts and ideally things that are less opinionated wherever we can! 
2. this is a lot of text so i'm worried about how much is there about this one topic!! we will also have a section devoted to tests and best practices there. so does all of this belong here now or can we consolidate the message to. be a bit more specific and elaborate more in the tests section? 
thoughts?

2023-03-13 21:44 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
also this - 

`If you are not developing a library that many different package managers build from your source distribution,`

i'm not sure what this means- do you mean if someone publishes on pypi and then also cross publishes on conda-forge? i'm just curious what many different package managers refers to here

2023-03-13 22:16 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency pinning,✖✅ ,Poetry offers dependency pinning however it's default approach can be problematic for some packages. Read below for more.
@radoering modified this everywhere to say "it's default approach"

2023-03-13 22:16 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Poetry, by default, pins dependencies using an "upper bound" limit specified with the `^` symbol by default. See breakout below for more regarding why this is potentially problematic.
@radoering i just removed the git based versioning comment here as the plugin is great and the same as what hatch offers.

2023-03-13 22:17 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +By default, Poetry pins dependencies using `^` by default. This `^` symbol means that there is
hopefully this also is ok now - i've added the by default and just need some clarification on how one would avoid the default upper bound pinning when using poetry.

2023-03-13 22:20 UTC, lwasser commented
@NickleDave et all i did see that the packaging guide uses lowercase sdist but i also see this  where the actual file name is SDist (notice the capitalized SD. 
<img width="295" alt="Screen Shot 2023-03-13 at 4 19 26 PM" src="https://user-images.githubusercontent.com/7649194/224845543-9318d588-09c9-4b28-a50a-e3e1e046de58.png">

so is sdist not capitalized intentionally or just by default there in the other guides?

2023-03-14 01:14 UTC, frostming commented on package-structure-code/complex-python-package-builds.md
> +* pdm, hatch and poetry all have "ways" of supporting c extensions via pdm-build, hatchling and poetry's build back end.
```suggestion
* pdm, hatch and poetry all have "ways" of supporting c extensions via pdm-backend, hatchling and poetry's build back end.
```

2023-03-14 01:14 UTC, frostming commented on package-structure-code/python-package-build-tools.md
> +locking, you can use **PDM** or **Poetry** but not **Hatch**.
We need to mention **build**, which is the recommended tool to build a package but it can't publish.

2023-03-14 01:14 UTC, frostming commented on package-structure-code/python-package-build-tools.md
> +## Build front-end vs. build back-end tools
We'd better keep the style consistent throughout this document. `back end` vs` back-end` vs `backend`, while I prefer the second: `back-end`

2023-03-14 08:12 UTC, aragilar commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
The many package managers would be the various linux distros, things like homebrew etc.

I'd suggest that tests should always be included in the sdist, unless the size of the test data is significant, and then I'd suggest storing such test data outside the package, and allow it to be downloaded (astropy does this, and has pytest tools which make this easy).

2023-03-14 17:35 UTC, NickleDave reviewed
Just adding two replies to your quesitons @lwasser!

2023-03-14 17:35 UTC, NickleDave commented on package-structure-code/intro.md
> +In general these are basic items that should be in any open software repository.
I think it might not be clear from the way it's written now what the other basic items are that you're talking about, since this whole page is about Python package structure and you don't describe what those other items are. I think you mean things like a license, contributing instructions, etc.? Talking about "checks" could just sound like "checking for all the Python package stuff we discuss on this page", until you mention "basic items" in the last sentence. If you want this note to be about those other things I would start by describing them.

2023-03-14 17:35 UTC, NickleDave commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
> is it really true that install times will be faster?

I just mean "if you have a 1 GB source distrib it will take longer to download" (try installing torch or torchvision vs. requests)

> this is a lot of text so i'm worried about how much is there about this one topic!! ... so does all of this belong here now or can we consolidate the message to. be a bit more specific and elaborate more in the tests section?
thoughts?

Yes I agree. I'm not sure if it makes sense to include this in a "pro of the src layout" because it's more like a side effect. I think we need a detailed explanation like this but it probably belongs in the tests section.

> i'm just curious what many different package managers refers to here

what @aragilar said -- linux distros, homebrew, et al. As discussed in the link I added.

> I'd suggest that tests should always be included in the sdist, unless the size of the test data is significant, and then I'd suggest storing such test data outside the package,

This does seem like a good blanket suggestion but it probably is better in the tests section not here in "pros of src/ layout".

Maybe the best thing to do is say something like "Note: People often use a src/ layout in combination with tests in a separate directory in the project root, for more detail see the [tests section](link)" and then say this stuff there

2023-03-15 16:19 UTC, lwasser commented on package-structure-code/intro.md
> +In general these are basic items that should be in any open software repository.
ok got it. thanks!

2023-03-15 16:21 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +## Build front-end vs. build back-end tools
great suggestion! i'll use back-end throughout.

2023-03-15 16:27 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
ok got it! this is super helpful. i'll pull this information into an issue for when we work on the tests section. let me take a stab at adding just a bit of text here on tests and then we can definitely add more information later. 

one more question for you both. Do python packages often publish to homebrew? This was definitely not on my radar but i do know there are many ways to install python itself. so this is good to read for me.

2023-03-15 16:43 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
This is where i'm at now. i just left a note about tests and data and such. i just don't want to overwhelm users with TMI on this page. this paeg just answers the question "how should i structure my package" . so diving into the nuances of testing here i think diverts the goal. With that said i think it's important for users to understand the burden on PyPI associated with lots of data and also installation issues with lots of data - but let's dive into the more in the testing section. Do you both think what i have here is reasonable just for the layout section?
<img width="672" alt="Screen Shot 2023-03-15 at 10 42 10 AM" src="https://user-images.githubusercontent.com/7649194/225379858-4bf193ef-4d7d-434f-b3ff-17af4f6c8bc4.png">

2023-03-15 16:46 UTC, lwasser commented
@all-contributors please add @aragilar for code, review

2023-03-15 17:00 UTC, NickleDave commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
>  Do python packages often publish to homebrew?
Often enough that there's a whole page in the docs about, that includes examples of Python packages that have brew recipes: https://docs.brew.sh/Python-for-Formula-Authors

I don't know that our community uses a ton of brew, but there are some that are really useful to install system wide, to do dev, e.g. pipx and nox
- https://formulae.brew.sh/formula/pipx
- https://formulae.brew.sh/formula/nox

This is the main reason I use brew on Linux too, to avoid some of the pain points of OS-level package managers

2023-03-15 17:04 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +locking, you can use **PDM** or **Poetry** but not **Hatch**.
ah good suggestion. i added this text below to this section!:

If you only need to build your package's sdist and wheel distribution files, then you can stick with PyPA's Build. You'd then use Twine to publish to PyPI.

2023-03-15 17:06 UTC, lwasser commented
@all-contributors  please add @frostming for code, review

2023-03-15 17:10 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
oh you're right. i have installed some things with homebrew that are nox like... many thanks for this i just hadn't considered it. ok so i'm going to open an issue for this NOW so i don't forget and LINK to the discussion here. so when we get to the tests section we can be more clear about the various scenarios to consider for tests and including tests!! many thanks for this discussion.  i keep thinking that i have all of the right things in my head and then realized i missed a use case (like brew etc!) this is why we have this review tho right?!

2023-03-15 17:22 UTC, lwasser commented
@all-contributors please add @radoering for code, review

2023-03-15 17:38 UTC, henryiii commented on package-structure-code/complex-python-package-builds.md
> +   supports additional build setps. In this case, you could use setuptools. However, we suggest that you chose build tool that supports custom build steps such as Hatch with Hatchling or PDM. PDM is
This list item is missing a new line before.

```suggestion
   supports additional build setps. In this case, you could use setuptools. However, we suggest that you chose build tool that supports custom build steps such as Hatch with Hatchling or PDM. PDM is an excellent choice as it allows you to also select your build back-end of choice. We will discuss this at a high level on the complex builds page.
3.**Python packages that have extensions written in different languages (e.g. Fortran and C++) or that have non Python dependencies that are difficult to install (e.g. GDAL)** These packages often have complex build steps (more complex than a package with just a few C extensions for instance). As such, these packages require tools such as [scikit-build](https://scikit-build.readthedocs.io/en/latest/)
```

2023-03-15 17:40 UTC, henryiii commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **pdm.pep517.api** to build the [package's sdist and wheels](python-package-distribution-files-sdist-wheel)
It's `pdm.backend`, and the package is `pdm-backend`.

2023-03-15 17:42 UTC, henryiii commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +The wheel (.whl) is your built binary distribution. **Binary files** are the built / compiled source files. These files are ready to be installed. A wheel (**.whl**) is a **.zip** file containing all
```suggestion
The wheel (.whl) is your built binary distribution. **Binary files** are the built / compiled source files. These files are ready to be installed. A wheel (**.whl**) is a **zip** file containing all of the files needed to directly install your package. All of the files in a wheel are binaries - this means that code is already compiled / built. Wheels are thus faster to install - particularly if you have a package that requires build steps.
```

I'd say it's a zip file, not a .zip file - it doesn't have a .zip extension.

2023-03-15 18:24 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
i think i understand now. i played with PDM. it has many options for constraint locking approaches which is great! i'm still searching for how to implement another locking approach with poetry!

2023-03-15 18:26 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +### Python package build front-ends
TODO: i just realized there is another big difference between flit, setuptools and the other three - some have an init workflow that creates your package structure for you. Whereas flit init for instance only creates the .toml file and adds a license. it relies on the user to create the structure.

also the way it creates the toml needs to be. noted as by default it assumes dynamic version and description. so if you try to do flit init and then build it will fail by default unless you already have everything setup.

i'm not sure if the readme needs to be added as `file = ` somewhere or what dynamic description means so need to look into this.

2023-03-15 18:27 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +### Python package build front-ends
this is particularly important for a new user. it would be nice to be able to create a structure, add code and install without running into errors that you don't understand initially.

2023-03-15 18:43 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +There are a several different build tools that you can use to [create your Python package's _sdist_ and _wheel_ distributions](python-package-distribution-files-sdist-wheel). Below, we discuss the fe
@takluyver  i'm sorry for not tagging you sooner. i've been reaching out to packaging package maintainers to get input on our writeup that compares the various tools. Flit is included in this document and i wanted to make sure that you were happy with how we represent Flit here! IF you have time - this PR is large but you can focus on this specific markdown file.  here is the page rendered as of an hour ago - https://output.circle-artifacts.com/output/job/55cc93e3-ad23-497d-adc5-d4442dac70df/artifacts/0/html/package-structure-code/python-package-build-tools.html i can post another update when i push another round of review responses this afternoon as well.

if you have time to read and review i'd appreciate it! many thanks!

2023-03-15 19:14 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +### Python package build front-ends
PDM does the same but it includes a READMe.MD and a pyproject.toml only - no license file

2023-03-16 00:34 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
PDM is on homebrew - that was the one i installed recently - i forgot about this!

2023-03-16 00:34 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
does the text above satisfy your concerns abotu this section (coupled with the issue to add more content to tests when we create that content?)

2023-03-16 00:38 UTC, lwasser commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **pdm.pep517.api** to build the [package's sdist and wheels](python-package-distribution-files-sdist-wheel)
Ah let's fix this - many thanks @henryiii ! i think i get confused as pdm has two backend choices when you work through pdm init! i'll make this pdm.backend i am not sure where i got hte .api part from maybe the other backend  🤷‍♀️

2023-03-16 00:41 UTC, lwasser commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **pdm.pep517.api** to build the [package's sdist and wheels](python-package-distribution-files-sdist-wheel)
oh actually i see where i got it. it was when i selected the second pdm backend option the pep 517 one. i still don't fully understand where there are two in the pdm init workflow

for reference:

```
❯ pdm init 

Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /Users/leahawasser/mambaforge/envs/myenv/bin/python (3.10)
1. /opt/homebrew/bin/python3.11 (3.11)
2. /opt/homebrew/bin/python3.10 (3.10)
3. /Users/leahawasser/mambaforge/envs/myenv/bin/python3.10 (3.10)
4. /usr/bin/python3 (3.8)
Please select (0): 3

Using Python interpreter: /Users/leahawasser/mambaforge/envs/myenv/bin/python3.10 (3.10)

Is the project a library that is installable?
A few more questions will be asked to include a project name and build backend [y/n] (n): y

Project name (testme): testme

Project version (0.1.0): 0.1

Project description (): A cool package.

Which build backend to use?
0. pdm-pep517
1. setuptools
2. flit-core
3. hatchling
4. pdm-backend
Please select (0): 4
```

2023-03-16 00:42 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +The wheel (.whl) is your built binary distribution. **Binary files** are the built / compiled source files. These files are ready to be installed. A wheel (**.whl**) is a **.zip** file containing all
perfect. thanks!

2023-03-16 00:46 UTC, lwasser commented
Ok y'all. i *think* i've captured everyone's comments today. let me know if you catch anything else. we can potentially merge this tomorrow or i'm ok with going live monday if more edits trickle in as well.  :) many thanks for everyone's feedback on this second round of reviews. i think we've improved this chapter SIGNIFICANTLY from the first iteration

2023-03-16 05:48 UTC, AllanSovereignJG commented
It sounds like you are providing an update on a pull request that has addressed feedback from a previous discussion (#23). Some highlights of the changes you've made include suggesting (but not requiring) the use of a "src/" layout for beginners to make testing easier, while still reviewing the more common flat layout. Additionally, you've added information on the poetry package manager and updated the table of front-end tools. You've also focused on providing high-level information on the tools without getting bogged down in details, with the intention of providing more in-depth tutorials later on. Overall, it seems like you've made good progress on addressing the feedback and improving the PR.

2023-03-16 06:11 UTC, ofek reviewed
Awesome work here!!!

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +- packageVersion: 1.1.0
The casing might lead readers to think that these are special names in some way but they do not correspond to any official metadata so I think we should not do that:

```suggestion
- name: stravalib
- version: 1.1.0
```

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-structure.md
> +There are several core directories that should be included in all Python packages:
I think rather than package we mean to say source distribution? Test and documentation files should not be included in wheels

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-structure.md
> +- **package-name/**: this is the directory that contains the code for your Python project. It is normally named using your project's name.
Perhaps we should omit or change this since it is possible to ship more than one package in a project, for example https://github.com/psf/black/tree/main/src

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
```suggestion
that includes tests within the **src/** directory.
```

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-structure.md
> +  package rather than on the flat files imported directly from your package. If you run your tests on your flat files, you may be missing issues that users encounter when your package is installed.
Can we please mention the reason is that Python adds the current directory to the front of the module search path?

2023-03-16 06:11 UTC, ofek commented on package-structure-code/python-package-structure.md
> +  **src/package-name** directory, `tests/` and `docs/`are in the root directory.
Rather than `src/package-name` can we say `src/` because it's not uncommon for the name of the package directory to differ from the project name

2023-03-16 06:11 UTC, ofek commented
>> For both cases with C/C++ extensions, back-end choices: hatchling should not be there, it is limited to pure Python projects only. It's already the default there for pure Python (Hatch includes hatchling as the build backend). So hatchling should not appear separately in the diagram.

> i'm still a bit confused by hatchling as it is my understanding that a dev can write plugins for it that would support more complex builds.

>> This is a plan, it does not exist aside from a design sketch (see [extensionlib docs](https://ofek.dev/extensionlib/history/)). And imho it's not a very good plan at that, but that's besides the point and I could be wrong. Despite the large amount of talking about it, it's only an idea at this point which needs to be implemented and then proven to be useful in practice.

@lwasser is completely correct here in that Hatchling has a rather robust plugin system that allows for users to execute arbitrary code, including building extensions. I'm actually rather perplexed how one can think otherwise since it is well documented and there are a bunch of plugins enumerated on the site.

extensionlib is an effort to standardize

2023-03-16 11:25 UTC, rgommers commented on package-structure-code/complex-python-package-builds.md
> +Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build back-end h
That was a private comment from before you announced that Hatch will be supporting PEP 517 backends in a future release. That said, your replies here are certainly not encouraging. See https://github.com/pyOpenSci/python-package-guide/pull/55#issuecomment-1471770866 for my full reply.

@lwasser you may want to clean up these working notes before merging this PR.

2023-03-16 14:39 UTC, ofek commented
> you are being pretty unhelpful to users and community members who want to understand what to use

I try my absolute best to answer questions from users and document every feature, all in my free time. If you have concrete ideas on how I can be more "helpful" in my responses or in the documentation please let me know.

> there's not even a single example, you are just waving your hands and it feels like you're trying to sell vaporware

There are docs on how to write a custom build hook. There is no example specific for setuptools because my assumption was that if one is knowledgeable enough to be building extensions with it then one necessarily would know how to execute a build of the extension modules in one's custom script.

What do you think? I can add an example if you want

> stumbled over [hatchling/metadata/classifiers.py](https://github.com/pypa/hatch/blob/63b692e3ac7c4156edbbf382b849eaa8707607eb/backend/src/hatchling/metadata/classifiers.py#L434). You're adding metadata for Cython, CUDA, Delphi, and everything else under the sun - really?

This is synced every so often from https://github.com/pypa/trove-classifiers to avoid a dependency. These classifiers are used at build time to ensure one does not define an unknown classifier. I'm not sure what you find surprising about this, can you please explain?

> A generic plugin system is not support for compiled code.

Right, in principle I totally agree with that but PDM has the same level of support (you write a custom script) and that is listed here as explicit support

2023-03-16 16:51 UTC, lwasser commented on images/python-package-tools-decision-tree.png
i appreciate this, @ofek thank you! I recently aded that envt management item because for instance i am a conda user. and i had an environment that with hatch i had to kind of figure out how to get it to recognize. i actually was a bit confused on how to do this and found a plugin that support conda, but i haven't had time to try it. 

Alternatively when i ran pdm init it just found my conda environment and asked me if i wanted to use it. so that is what inspired me to add environment manager to that box because with hatch there were some additional steps. 

perhaps you can help me understand how you view environments with folks using hatch. maybe there is another angle that i need to consider such as those who ONLY want to pick create sdist and wheel who may not need any envt help. i just ran into this issue pretty quickly with hatch given my workflows.

2023-03-16 16:55 UTC, lwasser commented on package-structure-code/complex-python-package-builds.md
> +Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build back-end h
goodness this is MY MISTAKE. @ofek @rgommers i messed up here and acknowledge this 100%. I've just pushed a new version without all of my notes. 

@ofek this was indeed a private comment and you know I also may have misread / translated it so please do not give ralf a hard time about this here. blame ME 1000% 

i hadn't intended to push my notes to GitHub i was just managing SO MUCH feedback that i needed things in one place to best get all of the comments into the document.

Ralf - please accept my profound apologies for my notes about conversations and such being public here in this PR. i'm not going through and removing ANY OTHER Instance of notes to myself that are more than just a reference link.

2023-03-16 16:57 UTC, lwasser commented on package-structure-code/complex-python-package-builds.md
> +Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build back-end h
Since this might go to email: i fixed the comment above - i am NOW going through and removing ALL notes from these pages. again my mistake. it wont happen again!

2023-03-16 16:59 UTC, lwasser commented on index.md
>  <!--
removed locally.

2023-03-16 17:00 UTC, lwasser commented on package-structure-code/intro.md
> +### Python packaging resources that we love
removed locally

2023-03-16 17:02 UTC, henryiii commented on package-structure-code/python-package-structure.md
> +  package rather than on the flat files imported directly from your package. If you run your tests on your flat files, you may be missing issues that users encounter when your package is installed.
And modern versions (3.11+) have an option (`PYTHONSAFEPATH` / `-P`) that disables this, which makes the flat structure less disadvantaged (but it's not default!).

2023-03-16 17:04 UTC, ofek commented on images/python-package-tools-decision-tree.png
I haven't tried Conda with PDM but maybe it supports that OOTB? My point is that Hatch doesn't require you to use the environment features, but if you choose to, arbitrary environments are supported via plugins

2023-03-16 17:07 UTC, henryiii commented
As far as I know, PDM-backend, Hatchling, and Poetry-core are all identical right now in their support for compiled extensions - basically you can sort of make it work in some common situations - but things like the wheel tags (when cross-compiling, targeting stable ABI, etc) are probably going to be wrong for all of them. PDM currently has a benefit over Hatch & Poetry in that it can use any backend - Hatch should pick this up too in the near future.

2023-03-16 17:07 UTC, lwasser commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **setuptools_scm** to manage package version updates using version control tags
great question! let me think about this a bit more. the goal of this page is to introduce pyproject.toml files not introduce the tools. i worry that if i also add hatch then i'd have to add poetry and maybe others to be full fair! 

we will have a page in the future on versioning and that might be a nice place to talk about plugins and. and show hatch there. 

the other place i plan to highlight hatch is i'm creating a singular page for each tool - that will be published over the next few weeks. So what i could do is link to that here when i create the hatch page. 

this is the type of page i plan to create for hatch - (this example is flit) it will actually also go on our website :) and i'm happy to link to other tools using hatch there as well too. https://hackmd.io/GkZlPoQgSJSiO1CmLliuiw 

Does that sounds like a good compromise to you?

2023-03-16 17:23 UTC, ofek commented
To elaborate for Hatchling, the usual mechanism for build hooks to define the wheel tag (other than setting the option explicitly) is to enable the [`infer_tag`](https://hatch.pypa.io/latest/plugins/builder/wheel/#build-data) build time option which uses the tag that is most specific to the platform and architecture. As Henry mentioned this doesn't work for cross-compiling so for example I've had to add [detection for certain environment variables](https://github.com/pypa/hatch/pull/672) and [options](https://github.com/pypa/hatch/pull/699) to handle nuances of certain platforms and versions.

2023-03-16 17:42 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +### Python package build front-ends
ok many thanks. i need to test hatch next. maybe that is what i'll do today!! 

i'm working on examples of each tool here, @ofek https://github.com/pyOpenSci/examplePy hatch isn't there yet but it will be it's just taking me time . each readme in that repo will then link to a online blog post about the tool.

2023-03-16 17:48 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
ok SO ... i think i need to change this to say

PDM is the only tool that currently supports other backends such as meson-python that can be used to build non pure python projects. 

something like this:
Both PDM.build and hatch can support additional build steps with custom scripts?

@ofek elsewhere you mentioned that hatchling ONLY supports pure python. please help me understant this script part. 

is is the case that you can use hatchling but then add the custom build steps via a plugin for hatch to run the additional steps outside of using hatchling?

and @frostming does describing pdm and pdm.build as tools that require additional build steps written by the user similar to hatch sound correct to you as well? many thanks

2023-03-16 17:49 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
so essentially neither back end (pdm.build or hatchling) supports  building C++, for example,  extensions. it's the custom build steps that are added to the hatch workflow or the PDM workflow that allow for additional compilation,etc steps?

2023-03-16 17:49 UTC, ofek commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **setuptools_scm** to manage package version updates using version control tags
That sounds fine, but in that case I definitely think you should remove the versioning plugin from this example

2023-03-16 17:51 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
totally. i wondered about this. can you please either reply here or in the other comment. i did see that it natively supported other environments but that you had to install a plugin for it to work with conda. so i might say you will need to install a plugin to use a conda environment?

2023-03-16 17:53 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
Yes that's better.

Hatchling is the only thing involved with building, Hatch the CLI is not relevant here (sorry if the docs don't do a good job of isolating the two yet). Build hooks are at the level of the backend/Hatchling https://hatch.pypa.io/latest/plugins/about/#types

2023-03-16 17:56 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
ok i added this

- Hatch won't by default support Conda environments. [But you can use a plugin for this](https://github.com/OldGrumpyViking/hatch-conda).

2023-03-16 17:59 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
In order to use Conda environments one must use a plugin yes.

I think I see a deeper issue here though with naming. I perceive a conflation between environment _types_ and environment _managers_. Environment types are things such as virtual environments, Conda environments, etc. whereas environment managers are the actual tools like Hatch, tox, nox, etc.

2023-03-16 18:02 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Hatch doesn't provide an end to end beginning workflow in it's documentation.
Sure thing! (and btw i have this critique of all of the tools right now - the docs are not user friendly for beginners). When i go to the hatch [homepage here ](https://hatch.pypa.io/latest/)- i see the very cool logo and overview of the tool. the next page i see is installation. i don't see that beginning to end workflow. 

What i'm looking for in each tool is the simplest way to get to a full package (without additional steps that might confuse users like plugins and such). This is where i think the discussion in the python discourse might apply where they are arguing about the tabs for multiple build back end tools. it just confuses users. 

to get started - i think users for any packaging tool would appreciate a short tutorial that takes them from hatch init through hatch publish without all fo the other bells and whistles. 

i hope that makes sense. i've actually had a hard time digging through the hatch docs to get to that for our examplePy workflow! this isn't saying hatch is bad. but i think the docs could be more clear for beginner users. And i think i'd love see see the same for PDM Flit and maybe poetry but i had an easy time getting started with poetry. i'm not speaking to you with a beginner user lens rather than someone working on a guide who has figured out how to use hatch! i'm looking for a page that gives users an easy win using hatch that is the simplest way to get start using hatch! 

let me know if that makes sense. or if you have questions! 

a tutorial get started page.

2023-03-16 18:18 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Setuptools has a few challenges:
i don't fully understand this and have asked a few others for clarification in case you don't have time to explain. i do understand there are subtle differences between `pip install -e` and a symlink type of editable install. but i don't understand how this relates to IDE's as i do use vscode for example. 

if you could clarify that would be wonderful. i think i have to learn a bit here to better represent this in the docs.

2023-03-16 18:20 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +  **MANIFEST.in** file
yes. this was actually a pain point for me with our stravalib package. and it defaults to adding everything. do you have a suggestion for language to add here by chance? i'm not exactly sure what you mean by precisely as you can use that manifest file but i also haven't played with it extensively. i just saw what it did by default without a manifest file and was surprised

2023-03-16 18:22 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +distribution using pip, pip needs to run a build step first. Sdist is normally stored as a `.tar.gz` archive (often called a "tarball").
ah... good suggestion. let me see what a few others thing in the scientific python community like @stefanv @tupui @henryiii  (and anyone else here in this PR) -- y'all the question is whether we should add the statement above - 

`a source distribution should contain everything required to build a wheel without network access`

2023-03-16 18:25 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +the SDist will also contain a `_version.py` file.
oh you are right. excellent point.

2023-03-16 18:28 UTC, lwasser commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **setuptools_scm** to manage package version updates using version control tags
ah good point! because scm is a specific addition to the pyproj.toml file. this is reasonable. i only have this second example because SO MANY tools use setuptools that i want users to see what that looks like. i just (locally) removed SCM for the deps that was a very good suggestion. will push this all soon.

2023-03-16 18:42 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
BTW i've rewritten this here:
Essentially i'm suggesting pdm as a way for scientists to support meson-python given there is a lot of momentum now in that space towards that build back end given the complexity of scientific packages! but i also noted that hatch can support build hooks.  Hopefully this reads better to you but also i still have this question about build back ends vs front end ui in general (the LONG question above). 

NOTE: You can also use Hatch for non pure python builds. Hatch, similar to PDM, allows you to write your own build hooks or plugins to support custom build steps. But currently, hatch does not support other build back ends. Many of the core scientific packages are moving to meson-python to build their packages. Thus, we appreciate that PDM can work with meson-python specifically.

2023-03-16 18:44 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +<!-- NOTE - add language around the front end means that you have less individual tools in your build - such as nox / make with hatch -->
fixed.

2023-03-16 18:49 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
ahhhh that could be the case. good point!

so now i have another question for you :) 
in my mind - conda / mamba DOES manage my environment. 

For instance, i can use `conda create env` to create a new environment on my maching, activate it and then `conda install` or conda update etc etc. is that not what a environment manager does? (i am not arguing with you i'm trying to better understand how you and others define and distinguish environment type of manager. ) so this is a real question that i've had for a while. 

when i use poetry to manage an envt for example it adds packages and such in the same way i might add a package using conda. BUT of course hatch has the matrix envt stuff that i'd have to manually recreate using conda. many thanks for clarification

2023-03-16 18:58 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +There are several core directories that should be included in all Python packages:
ahhhh. ok SO this has been an ongoing discussion. BUT now i'm realizing that i never asked people about whether tests should ship with the sdist only or sdist and wheels.

There are many who think that tests SHOULD ship to the user in the distribution. and i just thought that would be both the sdist and wheel including tests. some maintainers want to be able to run tests on users machines when there are bugs.  

now docs is another issue that we haven't discussed as much. but i guess the issue is if you don't have the docs locally you can't view them if you don't have internet access. i have mixed feelings about including docs in a build but see the merit of including tests (but not the test data)

Now here on this page, i am actually referring to the directories that need to be included in a repository. 

this is the folders that would be greated in a init method if you were to create a working directory structure for a new package (does that make sense?). So what if i change the language to

directories that should be in your working python package repository or something like that to be more clear? this is not about what's included in the SDist or wheel this is simple - how to layout your package if you are a beginner.

2023-03-16 18:58 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +There are several core directories that should be included in all Python packages:
right now i just changed this locally to: 

Directories that should be in your starting Python package repository

2023-03-16 19:04 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +- **package-name/**: this is the directory that contains the code for your Python project. It is normally named using your project's name.
i've added this
*****

```{admonition} Multiple packages in a src/ folder
:class: tip

In some more advanced cases you may have more than one package in your src/ directory. See [black's GitHub repo](https://github.com/psf/black/tree/main/src) for an example of this. However for most beginners you will likely only have one sub-directory in your src/ folder.
```

let me know if this seems like a reasonable compromise to capture your point without confusing a beginner! it's good to note that there are other more complete examples for users to think about so i'm happy to add little notes and tips throughout!

2023-03-16 19:07 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
i think i understand where you're going with this but i am not sure that will be clear to a user. i'm worried that they might see src/ and not know there should be a sub directory there. 

if they skip adding the package-name subdir then (among other things) they will lose the benefit of running tests on the installed version of their package that src/ provides.

does that make sense? i want to be super clear to users that the structure is `src/other-dir` (where other-dir is most often but maybe not always the package name)

2023-03-16 19:10 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +  package rather than on the flat files imported directly from your package. If you run your tests on your flat files, you may be missing issues that users encounter when your package is installed.
OH!! i just put together the python path and how python prioritizes the current directory technically. i knew it did but wasn't sure what the behind the scenes technical mechanism was. YES let's add this. AND i'll add a note about python 3.11+ as well.

2023-03-16 19:11 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
Conda is a tool that can manage its own environments of course but at the end of the day they are isolated based on some mechanism. The way virtual environments work is explained here https://snarky.ca/how-virtual-environments-work/. It's _how_ they work that differentiates them as an environment type.

You could in practice get pip to work in Conda environments but that is not officially supported and definitely should not be recommended. It's a totally different ecosystem and package metadata is also different

2023-03-16 19:15 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Hatch doesn't provide an end to end beginning workflow in it's documentation.
You just have to continue since installation is by definition the first step, the next page is where you create your first project 😉

2023-03-16 19:17 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +Setuptools has a few challenges:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#editable-install-modules-not-found

This means basically you have no autocomplete or anything

2023-03-16 19:19 UTC, tupui commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
> You could in practice get pip to work in Conda environments but that is not officially supported and definitely should not be recommended. It's a totally different ecosystem and package metadata is also different

True that it's not recommended to mix and might be tricky to discuss in such document. Between us though, I do this quite often. I always have a conda env and install everything from conda. But if something is missing or if I want to point to git sources, etc. then I resort to pip. And this is mostly fine, I really rarely have any issues. (Part of the why I am a lost cause I will maybe never get the drama around packaging as conda just works perfectly for me 😄)

2023-03-16 19:22 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +  **MANIFEST.in** file
I mean 2 things I suppose: one is that the pattern notation and directives are cumbersome to use in comparison to Git patterns and the other is that options in `setup.py` also affect the behavior of what gets included in the source distribution which makes it all the more confusing

2023-03-16 19:24 UTC, ofek commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
Hatch as well https://hatch.pypa.io/latest/install/#homebrew

2023-03-16 19:26 UTC, ofek commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
I do differently understand what you're going for but in this particular instance you're saying to put tests inside the actual package directory not the directory that stores the package directory

2023-03-16 19:28 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
I think you may confuse defining dependency constraints (in the pyproject.toml file) and dependency locking (in a lock file, for poetry: poetry.lock). (Or I'm just confused by your usage of the word "locking". 😉)

Upper bounds and open bounds are only relevant for dependency constraints in the pyproject.toml file, but not for the lock file because there is only one locked version. (If I'm not wrong that should apply to both: poetry and PDM.)

Default: `poetry add tomli` will result in an upper bound. Explicit: `poetry add "tomli>=2.0"` will result in unbounded constraint. However, if there are no conflicts, both approaches (upper bound and unbounded) will result in the same locked version (2.0.1 as of today). And that's only the command line interface. You can edit (or add) constraints in the pyproject.toml file directly.

2023-03-16 19:28 UTC, ofek commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
As an example, the current language makes it so you would start installing and being able to import a `numpy.tests`

2023-03-16 19:32 UTC, ofek commented on package-structure-code/python-package-structure.md
> +- **package-name/**: this is the directory that contains the code for your Python project. It is normally named using your project's name.
Nice!

2023-03-16 19:34 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +  package rather than on the flat files imported directly from your package. If you run your tests on your flat files, you may be missing issues that users encounter when your package is installed.
Ok this is great. I love this suggestion because i think paths and importing packages is a really confusing part of using Python for many users. 

I just added this text locally:
***********
### How Python discovers and prioritizes importing modules
One of the main technical advantages of using the src/ layout, if you are just getting started with a new package, relates to how Python discovers packages. By default, Python adds a module in your current working directory to the  front of the Python module search path.

This means that if you currently in your packages working directory, and your module code lives in the root e.g.: /package-name/module.py, python will discovers package-name/module.py before it the package as installed by pip or conda in a virtual environment.

However, if your package lives in a directory structure that is **src/package-name** then it won't be, by default, added to the Python path. This means that when you run import package, python will be forced to first search the active environment (which has your package installed).

Note that modern Python versions (3.11 and above) do have an option to adjust how the Python path finds modules (`PYTHONSAFEPATH`) however this is still a setting that a user would need to adjust in order to avoid the behavior of Python importing a module from your current working directory first.

2023-03-16 19:36 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +  **src/package-name** directory, `tests/` and `docs/`are in the root directory.
i saw that comment above. i left a note - i like the idea but i'm worried about users reading src/ and thinking their module code needs to live directly in src. i wonder - to address your concern could we just note that sometimes the directory name might be different from the package name ?

2023-03-16 19:38 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +  **src/package-name** directory, `tests/` and `docs/`are in the root directory.
what about language like this: would this address your concerns? they are valid. i get that there could be multiple sub directories or different names too!!

*******

It is important to note here that sometimes when using the src/package-name structure the directory name (e.g. package name) is different from the actual project or package name. What is important to take away here is that you should store your code within a sub directory in **src/**.

2023-03-16 19:40 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
Yes I do it too haha

Upon looking back I have one more example of what I mean, when it is said that:

> in my mind - conda / mamba DOES manage my environment

Those are different environment managers but they are managing a single _type_ of environment. Similarly, one can use containers as a type of environment but use different managers like Docker or podman.

I hope I'm explaining this adequately, there is a clear and very important difference between an environment manager and an environment type.

2023-03-16 19:43 UTC, ofek commented on package-structure-code/python-package-structure.md
> +  **src/package-name** directory, `tests/` and `docs/`are in the root directory.
Yes that sounds perfect

2023-03-16 19:44 UTC, lwasser commented on package-structure-code/python-package-distribution-files-sdist-wheel.md
> +distribution using pip, pip needs to run a build step first. Sdist is normally stored as a `.tar.gz` archive (often called a "tarball").
Ok - i've gotten feedback from a few others! i added / adjusted this text:

*******
**S**ource **D**istributions are referred to as sdist. As the name implies, a SDIST contains the source code; it has not been
built or compiled in any way. Thus, when a user installs your source
distribution using pip, pip needs to run a build step first. For this reason, you could define a source distribution as a compressed archive that contains everything required to build a wheel (except for project dependencies) without network access.

Sdist is normally stored as a `.tar.gz` archive (often called a "tarball"). Thus, when a user installs your source distribution using pip, pip needs to run a build step first.

*****
Note that one of the comments was that it wont contain dependencies and i think that is important for new users to remember. As technically you can't install without network access if you have external dependencies to grab! that actually was a point of confusion for my students ... that internet access mattered when installing packages! so i think it's worth being explicit!

2023-03-16 19:48 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
> So does that mean if someone used hatchling with the pdm from end they could create hooks thats would still allow the hatchling backend to run additional compilation steps? is it that independent.

Yes packages that use Hatchling can be built with anything and the build hooks will still execute

2023-03-16 19:59 UTC, lwasser commented
ok colleagues - i'm taking a needed break from working on this now but appreciate that comments ARE still trickling in! and feel free to continue to add them / respond to what i've changed, etc. 

1. apologies again - all of the comments that were in the text body are NOW removed from the content. MY MISTAKE. please ignore any comments that you did previously read as all are dated. what is important to focus on in this PR is the final text of our guide. i am confident we can merge this SOON. 
2. i just pushed a fresh batch of updates addressing many of the comments here. Knowing that other comments are still coming in. (many thanks for this continued feedback). We are really addressing small bugs and items that i conflated in the text that would be confusing to users - so i appreciate this level of feedback!

More to come soon either later today or in a day or two. i'm now shooting to merge this on Monday next week just to allow these last reviews to come in and be addressed :) thank you all as we are really working well together to get to a guide that i think the community will greatly appreciate. And this is really because of all of you here being willing to spend time working with us on this effort with the shared vision of making python packaging easier to navigate for beginners!!

2023-03-16 20:29 UTC, rgommers commented on package-structure-code/complex-python-package-builds.md
> +Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build back-end h
Thank you @lwasser, and no worries - this kind of thing happens sometimes. I did phrase this more harshly than I would have normally done, so my apologies too.

2023-03-18 14:49 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
In my experience, one example for dependency locking where poetry does better than pdm is multiple-constraints dependencies, in other words if you need a different version of a dependency based on environment markers.

Example:

Dependency definition in pyproject.toml for poetry:

```
[tool.poetry.dependencies]
python = ">=3.7"
flake8 = [
  {version = ">=6.0.0", markers = "python_full_version>='3.8.1'"},
  {version = "<6.0.0", markers = "python_full_version<'3.8.1'"},
]
```

and equivalent definition for pdm:

```
[project]
requires-python = ">=3.7"
dependencies = [
    "flake8>=6.0.0; python_full_version >= \"3.8.1\"",
    "flake8<6.0.0; python_full_version < \"3.8.1\"",
]
```

If you run `poetry lock` and `pdm lock`, you will notice that there are two `flake8` versions (5.0.4 and 6.0.0) in the `poetry.lock` file, but only one version (the one satisfying the last constraint as it seems) in the `pdm.lock` file.

As already mentioned this is only an example. I do not have much experience with pdm but I'm sure you will find examples where pdm does better.

I'll leave it up to you to decide whether something like this is relevant for beginners or only for advanced users.

2023-03-19 08:25 UTC, astrojuanlu commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
@radoering Looks like a bug in PDM that could be reported upstream?

2023-03-19 11:06 UTC, radoering commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
pdm-project/pdm#46

2023-03-20 11:46 UTC, takluyver commented on package-structure-code/python-package-build-tools.md
> +There are a several different build tools that you can use to [create your Python package's _sdist_ and _wheel_ distributions](python-package-distribution-files-sdist-wheel). Below, we discuss the fe
Thanks for the ping. This mostly looks good to me, though there's one detail I think could be changed. The page you linked says:

> Flit supports installing your package in editable mode. However it does use a slightly different syntax from the usual pip install -e . to do so.

`pip install -e .` should work for packages built with Flit, so long as you have a recent version of pip with [PEP 660](https://peps.python.org/pep-0660/) support. Flit also has a command to do editable installs a non-standard way that I happen to like (symlinks), but for a high level overview I'd ignore this and just say that editable installs are fully supported.

2023-03-20 16:26 UTC, lwasser commented on package-structure-code/pyproject-toml-python-package-metadata.md
> +- **setuptools_scm** to manage package version updates using version control tags
scm has been removed!! resolving this!

2023-03-20 16:39 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +  package rather than on the flat files imported directly from your package. If you run your tests on your flat files, you may be missing issues that users encounter when your package is installed.
ok wonderful. im resolving this as i see the emoji above on my suggested text. excellent suggestion that improves our guide @ofek and great note by @henryiii about python 3.11!!

2023-03-20 16:42 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
i'm really leaning towards JUST telling people to place tests in the root of the repository like this:

```
github-repo/
    tests/
    src/package-name
    docs
```    
    
this just feels much simpler. then we can add a note about HOW to include tests (but not big datasets) with the package build if maintainers want. to me this feels like the simplest solution. thoughts?

2023-03-20 17:10 UTC, ofek commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
Yes that is best and most common for the non-flat layout

2023-03-20 17:25 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
ok i've just removed this sentence altogether to avoid confusion :) so it just says:

```
The key characteristic of this layout is that your package
uses a **src/package-name** directory structure. With this layout it is also
common to include your `tests/` directory outside of the package
directory.
```

we've received some feedback that some do want tests to "ship" with the package itself but we can show people how to include them if it is needed rather than confusing people and suggesting there are a few places to "put" tests. many thanks!!

2023-03-20 17:34 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +There are a several different build tools that you can use to [create your Python package's _sdist_ and _wheel_ distributions](python-package-distribution-files-sdist-wheel). Below, we discuss the fe
ok fixed!! i've clarified that it does support editable installs. i've also just added a note about using either pip install -e and the -s option with flit :) many thanks!!

2023-03-20 17:35 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +that includes tests within the **src/package-name** directory.
ok ive fixed this! we only suggests tests outside src/ now!

2023-03-20 18:12 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +versioning. If you are deciding between the two tools, the main difference between these two tools
this breakout now reads:
**************

The functionality of PDM is similar to Poetry. However, PDM also offers
additional, documented support for C extensions and version control based
versioning. As such PDM is preferred for those working on non pure-Python packages.

If you are deciding between the two tools, a smaller difference is the default way that dependencies are added to your pyproject.toml file.

* Poetry by default follows strict semantic versioning adding dependencies to your pyproject.toml file using an upper bounds constraint (`^`). However, you can tell Poetry to not use upper bounds if you wish.
* PDM defaults to open-bounds (`>=`) dependency additions. However, PDM also allows you to specify the way dependencies are added by default. As such, you can also specify upper-bounds (`^`) using PDM.

In either case, beware that strict adherence to semantic
versioning can be problematic in some cases (more below).

Finally there are some nuanced differences in how both tools create lock files which we will not go into detail about here.

2023-03-20 18:20 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Hatch doesn't provide an end to end beginning workflow in it's documentation.
ahhhhh @ofek if you don't mind - i'm gonna suggest a small suggested change. Most users don't click through content in the way that you design it - they bounce around. it was NOT clear to me that section was a "Get started" section or a tutorial. 

my two cents then - is to have a get started section button on the home page and then group that side bar content into a get-started section because right now it's with the "about" content. so users will miss that they are supposed to walk through each page. it also has an introduction page that really is more of a create or initialize a project page. so thats confusing too!

We (pyos) suggest that package maintainers have a get-started section in their docs as well. (here's an example - pandas https://pandas.pydata.org/docs/ ) Then make it clear that those pages represent a linear set of content that a new user work through! 

so maybe it looks something like this 

about 

about 

GET STARTED
* install hatch
* Create project. (introduction is really confusing as a word)
* manage environment
etc..


make is super clear that is a tutorial walk through and change introduction to something more meaningful 

just my two cents!

2023-03-20 18:25 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +By default, Poetry pins dependencies using `^` by default. This `^` symbol means that there is
added this 

******
Poetry, by default, pins dependencies using an "upper bound" limit specified with the `^` symbol by default. However, this behavior can be over-riding by specifying the dependency when you use `Poetry add` as follows: `poetry add "requests>=2.1"` See breakout below for more discussion on issues surrounding upper-bounds pinning.

2023-03-20 18:38 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
ok what i've done to fix this is made two lines in the chart - one for lock files, the other for adding deps

****

Dependency specifications |✅|PDM and Poetry but support managing dependencies. However, their default approach to adding dependencies is different. Poetry uses a default [upper bound lock](https://python-poetry.org/docs/dependency-specification/#version-constraints) `^`. Upper bounds lock means that Poetry will never bump a dependency to the next major version (ie from 1.2 to 2.0). However you can tell Poetry to use an open bounder approach (see below for more and we suggest that you do so). PDM uses an open lock `>=` approach by default but also allows you to [customize how you want to add dependencies](https://pdm.fming.dev/latest/usage/dependency/#about-update-strategy). Thus with PDM you can explicitly tell it to lock using upper bounds like Poetry. Or you can tell it to use other strategies. This makes PDM extremely flexible tools when managing dependencies.
Dependency environment lock files |✅|PDM and Poetry are currently the only tools that create dependency lock files. Lock files are often most useful to developers creating web apps where locking the environment is critical for consistent user experience. For community-used packages, you will likely never want to use a lock file.
****

i will now read through the entire page to ensure my notes on locking envt vs managing dependency constraints is clear and consistent!

2023-03-20 18:38 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Dependency management & lock files ,✅,PDM and Poetry are currently the only tools that support creating dependency lock files. However their approach to locking files is different: Poetry uses an upp
<img width="157" alt="Screen Shot 2023-03-20 at 11 33 25 AM" src="https://user-images.githubusercontent.com/7649194/226435374-0473f84d-fd06-41f6-b14e-77840683b3aa.png">

2023-03-20 18:46 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
> If tests/ are outside of the src/package-name directory, then most high-level packaging tools (e.g., poetry, PDM, hatch) will not by default include them in the distribution package delivered to a 
> user.

David i think your language is important. as i've already been asked this. 

ok i have another really important question related to this thread. important to the scientific ecosystem. when you specify tests including in the distro using hatch, PDM or setuptools / flit is that for both the built wheel AND the sdist ? IE can these tools currently be setup to make tests available to run for the end user?

2023-03-20 18:58 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
ok y'all. i just want to confirm that for scientific packages, it is very important to highlight HOW to ship tests with your package. as such, it seems like i will need to add back the option of tests being here:

src/
    package-name/ 
         tests/ 

because it sounds like that is the ONLY way a maintainer can access the tests on other machines. (if there is another way to ship tests, please tell me). but i'm seeing that we may need to add a note about back about tests living in that package-name dir.

2023-03-20 19:04 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Setuptools has a few challenges:
got it. ok i understand this now @ofek thank you. 

so would it be fair to say the following:
**********
if you are using flit, hatch, PDM, and a current version of pip,  editable installs will support interactive features such as tab completion when using an IDE like VSCODE or pycharm. However if you use `pip install -e .` with setuptools as your back end, you will not have this interactive IDE support.

2023-03-20 19:11 UTC, lwasser commented on images/python-package-tools-decision-tree.png
YES PDM discovers conda envts OOTB when you run `pdm init`

```
❯ pdm init 

Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. . /Users/.../mambaforge/envs/myenv/bin/python (3.10)
1. /opt/homebrew/bin/python3.11 (3.11)
2. /opt/homebrew/bin/python3.10 (3.10)
3. /Users/.../mambaforge/envs/myenv/bin/python3.10 (3.10)
4. /usr/bin/python3 (3.8)
Please select (0): 3
```

let me go back and review this section. i do think i'm conflating environment management tool vs envt type. looking for that other comment about environment type vs envt management tool. because conda still is sitting in my brain as a tool making it hard for me to clarify this part of our guide! if you can think of any ways for me to better explain a management tool vs type this i'd appreciate it!

2023-03-20 19:12 UTC, lwasser commented on package-structure-code/complex-python-package-builds.md
> +Hatch has the worst take on building compiled code by some distance. Unless its author starts developing an understanding of build systems / needs, and implements support for PEP 517 build back-end h
thank you both for the grace!! i think everything (all comments) are now cleared out!!

2023-03-20 19:14 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +write your own plugin for this support.
ok great. hopefully that language i added above is good enough. unresolve this comment please or ping me if it's still not right!

2023-03-20 19:17 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
ok i'm working on this. this was the thread i was looking for. let me read brett's snarky canadian post and see if i can do a better job of distinguishing these two things. i may have more questions. BTW similar to @tupui i mix pip with conda too but ONLY as a last resort when i can't find the package on conda etc. conda always works for me.

2023-03-20 19:26 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +Setuptools has a few challenges:
tab completion -> auto completion

"setuptools as your back end, you will not have this interactive IDE support" + "by default"

2023-03-20 19:39 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Hatch doesn't provide an end to end beginning workflow in it's documentation.
Good suggestion, I will do this 🙂

2023-03-20 19:40 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
can you please help me by providing examples (outside of conda!) of python environment managers and then python envt types please?

would types refer to the different ways you can create an environment such as global vs the _pypackages_ or venv local type of environment?

if so what are examples of envt managers? i think this will help me differentiate better. in my mind an envt mgr is a tool that allows you to create, add, update, remove virtual python environments that have specific python kernels attached to them. many thanks.

2023-03-20 19:41 UTC, ofek commented on package-structure-code/python-package-structure.md
> +installing your package. However, you can chose to add them to the package archive. When tests are not included in the package archive your package size will be slightly smaller.
> is it indeed possible to ship tests to a user if the tests dir lives outside of src? it seems like it may not be but i welcome input here.

Yes, with Hatchling either of:

- https://hatch.pypa.io/latest/config/build/#forced-inclusion
- https://hatch.pypa.io/latest/config/build/#rewriting-paths

2023-03-20 19:43 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +  **MANIFEST.in** file
ok so i haven't actually worked on our manifest file yet. 

> one is that the pattern notation and directives are cumbersome to use in comparison to Git patterns 

are you saying that there is some sort of regex needed to specify patters in the. manifest.in file for setuptools that are cumbersome to use? vs what you'd use in a .gitignore file?

> options in setup.py also affect the behavior of what gets included in the source distribution which makes it all the more confusing

this i'm less familiar with. can you please clarify so i can add a bit of language?

2023-03-20 19:44 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +- **package-name/**: this is the directory that contains the code for your Python project. It is normally named using your project's name.
perfect! resolving this!

2023-03-20 19:52 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
> can you please help me by providing examples (outside of conda!) of python environment managers and then python envt types please?

- Hatch supports virtual environments OOTB with support for other environment types via plugins
- tox/nox supports virtual environments
- PDM supports virtual environments and `__pypackages__`

> in my mind an envt mgr is a tool that allows you to create, add, update, remove virtual python environments that have specific python kernels attached to them

Correct except for the word `virtual`. Virtual environments are a particular way of providing isolation, but there are others. The best example analogy I think is one I mentioned above:

> one can use containers as a type of environment but use different managers like Docker or podman

2023-03-20 19:56 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +  **MANIFEST.in** file
https://packaging.python.org/en/latest/guides/using-manifest-in/

2023-03-20 20:09 UTC, ofek commented on package-structure-code/python-package-structure.md
> +There are several core directories that should be included in all Python packages:
> seems like for scientific packages we may want to just ALWAYS ship tests ie include them in src/package-name/ directory

I'm not sure precisely what makes scientific package users different than the majority of users that don't want tests shipped, but this is not my domain so whatever you want to do is likely best.

Please keep in mind that hosting is provided for free so it doesn't seem responsible to recommend shipping a potentially large directory in the wheel, especially since scientific packages have compiled extensions so there might be dozens of wheels per release.

2023-03-20 20:19 UTC, lwasser commented on package-structure-code/python-package-structure.md
> +There are several core directories that should be included in all Python packages:
i need to dig a bit more into this. i hear you on the pypi warehouse side of things and size.

2023-03-20 20:24 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
ok i really appreciate your patience. i think clarifying that word "virtual" which i've used generally (and it sounds like incorrectly) for a while is what is hitting home. I get it now i think i'll try to rewrite. 

does hatch support adding dependencies and checking versions? [i found this](https://hatch.pypa.io/latest/config/dependency/) . but is the idea that a user should manually add deps to the  pyproject.toml file? many thanks. i'm going to go back through this file in a bit to clarify dependencies, lock files and environments more.

2023-03-20 20:28 UTC, lwasser commented
@rgommers question for you: should we suggest that EVERYONE creating scientific software ship tests with a package distribution so that it can be run locally on user's machines? I know from @stefanv that many scientific packages find it crucial to have tests shipped with a package (in the wheels) so they can be run on various installations. 

However shipping tests even without data places a small but increasing over time package size burden on PyPI / warehouse's storage resources. so i'm trying to come up with a recommendation that doesn't tax PyPI but also satisfies the scientific ecosystems needs. any thoughts on this?

2023-03-20 20:51 UTC, rgommers commented
> should we suggest that EVERYONE creating scientific software ship tests with a package distribution so that it can be run locally on user's machines?

Maybe not necessary for the audience of this guide. For large projects it's important because we get a ton of bugs related to differences in CPU features, compilers and numerical libraries like BLAS, etc. (this is indeed different for numerical libraries vs. something like a web dev package). In practice those are very tricky to debug, and one of the best things to make a dent in that is ask users to run something like `python -c "import numpy; numpy.test()"`. If the instructions are multi-step, downloading tests from a Git repo, finding the right branch etc., that won't work.

For small packages with a limited amount of compiled code this is all less relevant though. For such packages I'd say they should include tests in their sdists, but not necessarily install those tests.

2023-03-20 21:36 UTC, ofek commented on package-structure-code/python-package-build-tools.md
> +- Doesn't allow you to select what environment manager you use. <!-- (is this right??) -->
Yes the dependency constraints are satisfied, but adding manually is required until I add commands for that

2023-03-20 23:23 UTC, lwasser commented
> For small packages with a limited amount of compiled code this is all less relevant though. For such packages I'd say they should include tests in their sdists, but not necessarily install those tests.

oh many thanks for this, Ralf!! very helpful. we've been having debates around this topic. 

****************

everyone - i've just pushed up a new batch of edits. i think i'm getting closer to getting the loose ends nailed down. 
i've switched language about environment mgt  focusing on each tool managing the environment for users but allowing users to select the environment type of their choice - and how that selection happens is different across tools. PDM finds conda envs right away, hatch needs a plugin, etc. !

i've also clarified some of the language around dependency management and upper bounds being a default for tools rather than the only way to do things. each tool has options. I've also clarified that lock files are completely separate. (they were conflated in the previous text)

feel free to give the text on the packaging tools page another round of review if you wish. the only item i have not formalized yet is the tests being shipped with the package by default or not but that will come in the next day. i think a new realistic goal is to merge by thursday morning mountain time in the USA (in ~2 days) - which leaves tonight tomorrow and all day wednesday for more thoughts to trickle in. 

and i'll review the flowchart diagram once more as well as i think i have to clarify environment management there too. 

we are SO CLOSE. thank you all for the input and feedback as it's clarified a lot!

2023-03-21 16:56 UTC, lwasser commented
> This has come a long way, you're almost there! I mostly pointed out some minor nits and made some rephrasing suggestions, hope it helps

thank you @NickleDave i think we are indeed in the home stretch!! what a wonderful feeling after all of this time.

2023-03-21 17:03 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +so it might be similar to Poetry in that regard -->
wonderful - ok i hope i've clarified the language around package managers in the guide! i've also mentioned that plugin for hatch. many thanks. i'm going to resolve this BUT if you find anything that seems off still please ping me here.

2023-03-21 17:04 UTC, lwasser commented on images/python-package-tools-decision-tree.png
ok i think i've addressed this. i was absolutely conflating several concepts. If you think something is still off /wrong ping me. i'm going to resolve this as completed for now but am happy to revisit if i need to!

2023-03-21 17:10 UTC, lwasser commented on package-structure-code/python-package-build-tools.md
> +Setuptools has a few challenges:
ok  - better? (see below)

****
Setuptools does not support interactive features such as auto / tab completion by default if you are working in an IDE like VSCODE and using an editable install for development. [See notes here about pylance support](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#editable-install-modules-not-found). In comparison, tools such as flit, hatch, PDM support interactive features such as tab / auto completion when using an IDE like VSCODE or pycharm (as long as your version of pip is current!).

2023-03-22 18:32 UTC, lwasser commented
ok y'all. i think we're ready to merge today!! once merged - if you catch any other issues with the text, feel free to open issues about them! this is a living document that we can continue to refine and update as we learn more and get more eyes on the content.

2023-03-22 18:34 UTC, merged

2023-03-22 18:58 UTC, ofek commented
Great job!

2023-03-27 22:03 UTC, lwasser commented
hi y'all - one last reminder - i will merge [this pr ](https://github.com/pyOpenSci/python-package-guide/pull/20) with the zenodo doi information tomorrow (tuesday mar 28) and create a release of this repo at that time. feel free to update / comment on the pr that is open if any of your information if missing. many thanks y'all for the comments already there (i just committed them!)